# Takeaways from that dude's research (3 articles)

1. Spatial clustering and centroid clustering are broken, relies on picker to self optimise within that coordinate, so doesn't help in complying to protocol strictly

2.

In [202]:
import pandas as pd
import numpy as np
import datetime as dt
import random as rand
from collections import Counter
import itertools
from ast import literal_eval
import statistics

In [107]:
df = pd.read_csv('df_lines.csv')   #df_lines

In [103]:
df.head(20)

,Unnamed: 0,S/N,DATE,OrderNumber,SKU,PCS,ReferenceID,Location,Alley_Number,Cellule,Coord,AlleyCell,Size,N_lines,OrderID,WaveID
4803,4803,4803,12/1/2018,3752394,230976,1,230976,A1022101,A10,22,"[20.75, 22.5]",A1022,"(260, 180)",2,1.0,0
4778,4778,4778,12/1/2018,3752964,440472,1,440472,A1008102,A10,8,"[20.75, 12.0]",A1008,"(350, 140)",6,2.0,0
4769,4769,4769,12/1/2018,3753076,399573,1,399573,A1119504,A11,19,"[19.5, 21.0]",A1119,"(330, 120)",1,3.0,0
4853,4853,4853,12/1/2018,3753012,364970,1,364970,A0518403,A05,18,"[37.75, 19.5]",A0518,"(240, 300)",1,4.0,1
4805,4805,4805,12/1/2018,3752393,230976,1,230976,A1022101,A10,22,"[20.75, 22.5]",A1022,"(260, 180)",2,5.0,1
4807,4807,4807,12/1/2018,3752392,230976,1,230976,A1022101,A10,22,"[20.75, 22.5]",A1022,"(260, 180)",2,6.0,1
4832,4832,4832,12/1/2018,3752215,349675,1,349675,A1101304,A11,1,"[19.5, 6.0]",A1101,"(290, 340)",1,7.0,2
4833,4833,4833,12/1/2018,3752213,308581,1,308581,A0816404,A08,16,"[28.0, 18.0]",A0816,"(260, 80)",1,8.0,2
4834,4834,4834,12/1/2018,3753147,348815,1,348815,A0904101,A09,4,"[24, 9.0]",A0904,"(200, 160)",2,9.0,2
4835,4835,4835,12/1/2018,3753147,397345,1,397345,A0914202,A09,14,"[24, 16.5]",A0914,"(240, 180)",2,9.0,3
4836,4836,4836,12/1/2018,3753142,254222,1,254222,A0719102,A07,19,"[32.5, 21.0]",A0719,"(290, 120)",1,10.0,4
4837,4837,4837,12/1/2018,3753139,398717,1,398717,A0603404,A06,3,"[35.75, 9.0]",A0603,"(160, 260)",2,11.0,4
4838,4838,4838,12/1/2018,3753139,458557,1,458557,A1019204,A10,19,"[22.75, 21.0]",A1019,"(170, 100)",2,11.0,4
4839,4839,4839,12/1/2018,3753140,358961,1,358961,A0908101,A09,8,"[24, 12.0]",A0908,"(250, 300)",2,12.0,4
4840,4840,4840,12/1/2018,3753140,388046,1,388046,A0920304,A09,20,"[24, 21.0]",A0920,"(130, 40)",2,12.0,5
4831,4831,4831,12/1/2018,3752234,367542,1,367542,A1016201,A10,16,"[20.75, 18.0]",A1016,"(400, 360)",1,13.0,6
4841,4841,4841,12/1/2018,3753137,372093,1,372093,A1001201,A10,1,"[22.75, 6.0]",A1001,"(340, 300)",1,14.0,6
4843,4843,4843,12/1/2018,3753130,452650,1,452650,A0901304,A09,1,"[26, 6.0]",A0901,"(120, 140)",1,15.0,6
4844,4844,4844,12/1/2018,3753126,374214,1,374214,A0106404,A01,6,"[50.75, 10.5]",A0106,"(250, 380)",1,16.0,7
4845,4845,4845,12/1/2018,3753127,397345,1,397345,A0914202,A09,14,"[24, 16.5]",A0914,"(240, 180)",1,17.0,7

In [14]:

df.describe(include="all")

,Unnamed: 0,S/N,DATE,OrderNumber,SKU,PCS,ReferenceID,Location,Alley_Number,Cellule,Coord,AlleyCell,Size
count,13204.000000,13204.000000,13204,1.320400e+04,13204.000000,13204.000000,13204.000000,13204,13204,13204.000000,13204,13204,13204
unique,NaN,NaN,16,NaN,NaN,NaN,NaN,1050,11,NaN,205,205,580
top,NaN,NaN,12/3/2018,NaN,NaN,NaN,NaN,A1119504,A10,NaN,"[19.5, 21.0]",A1119,"(330, 120)"
freq,NaN,NaN,1713,NaN,NaN,NaN,NaN,430,2117,NaN,455,455,470
mean,6601.500000,3092.163435,NaN,3.771021e+06,368809.279537,1.344820,368809.279537,NaN,NaN,10.857089,NaN,NaN,NaN
std,3811.810812,2009.089432,NaN,1.387932e+04,74463.371052,0.621086,74463.371052,NaN,NaN,6.211302,NaN,NaN,NaN
min,0.000000,0.000000,NaN,3.752213e+06,17769.000000,1.000000,17769.000000,NaN,NaN,1.000000,NaN,NaN,NaN
25%,3300.750000,1451.000000,NaN,3.759561e+06,335152.000000,1.000000,335152.000000,NaN,NaN,6.000000,NaN,NaN,NaN
50%,6601.500000,2902.000000,NaN,3.767632e+06,374263.000000,1.000000,374263.000000,NaN,NaN,10.000000,NaN,NaN,NaN
75%,9902.250000,4396.250000,NaN,3.780497e+06,431861.000000,2.000000,431861.000000,NaN,NaN,16.000000,NaN,NaN,NaN
max,13203.000000,8175.000000,NaN,3.815480e+06,466974.000000,25.000000,466974.000000,NaN,NaN,22.000000,NaN,NaN,NaN

In [19]:
def get_unique_count(col_name):
    return len(df[col_name].unique())

In [20]:
# Num of unique orders
get_unique_count('OrderNumber')

3584

In [22]:
# Num of unique Dates
get_unique_count('DATE')

16

## Check if each order has unique SKUs

In [65]:
df[ordernum_col].value_counts()#.unique()
freqs = df[ordernum_col].value_counts()
num_orders_with_n_orderlines = Counter(freqs)
print(num_orders_with_n_orderlines)

Counter({1: 2642, 2: 652, 3: 179, 4: 70, 5: 21, 6: 15, 10: 2, 7: 2, 8: 1})

In [ ]:

# Mapping Order lines
# df_nline = pd.DataFrame(df.groupby(['OrderNumber'])['SKU'].count())

unique_order_nums = df[ordernum_col].unique()
for uon in unique_order_nums:
    this_order = df[df[ordernum_col] == uon]
    print(len(this_order['SKU'].unique()))
    print(len(this_order['SKU'].index))
    
    print("=" * 100)

## Let's assume we this whole list is for one day

## Let DATE just be the date order is confirmed, and create another column TIME_TO_PICK be the latest time to pick finish.

In [54]:
def get_rand(this_range):
    return rand.randint(this_range[0], this_range[1])

In [58]:
pick_time_col = "TIME_TO_PICK"
ordernum_col = "OrderNumber"
seed = 1234
hour_range = (8,18)
min_range = (0,59)
ordernum_to_picktime = {}

rand.seed(seed)

for x in df[ordernum_col].unique():
    rand_hour = get_rand(hour_range)
    rand_min = get_rand(min_range)
    ordernum_to_picktime[x] = dt.time(rand_hour, rand_min)

In [59]:
def get_pick_time(x):
    return ordernum_to_picktime[x[ordernum_col]]

df[pick_time_col] = df.apply(get_pick_time,axis=1)

In [60]:
df.head()

,Unnamed: 0,S/N,DATE,OrderNumber,SKU,PCS,ReferenceID,Location,Alley_Number,Cellule,Coord,AlleyCell,Size,TIME_TO_PICK
0,0,0,12/11/2018,3780678,399573,1,399573,A1119504,A11,19,"[19.5, 21.0]",A1119,"(330, 120)",15:07:00
1,1,1,12/11/2018,3780650,340308,1,340308,A0721204,A07,21,"[32.5, 22.5]",A0721,"(350, 200)",08:05:00
2,2,2,12/11/2018,3780649,399573,1,399573,A1119504,A11,19,"[19.5, 21.0]",A1119,"(330, 120)",17:02:00
3,3,3,12/11/2018,3780645,442025,1,442025,A0706401,A07,6,"[31.25, 10.5]",A0706,"(210, 260)",18:44:00
4,4,4,12/11/2018,3780638,436455,1,436455,A0216107,A02,16,"[47.5, 18.0]",A0216,"(350, 240)",09:06:00

# Create occupancy grid

# #######

In [67]:
# Mapping Order lines
df_nline = pd.DataFrame(df.groupby(['OrderNumber'])['SKU'].count())

In [70]:

def process_lines(df_orderlines):
    ''' Processing of dataframe '''
    # Mapping Order lines
    df_nline = pd.DataFrame(df_orderlines.groupby(['OrderNumber'])['SKU'].count())

    # Lists
    list_ord = list(df_nline.index.astype(int).values)
    list_lines = list(df_nline['SKU'].values.astype(int))

    # Mapping
    dict_nline = dict(zip(list_ord, list_lines))
    df_orderlines['N_lines'] = df_orderlines['OrderNumber'].map(dict_nline)

    # Processing
    df_mono, df_multi = df_orderlines[df_orderlines['N_lines'] == 1], df_orderlines[df_orderlines['N_lines'] > 1]
    del df_orderlines

    return df_mono, df_multi

mono, multi = process_lines(df)

In [75]:
def orderlines_mapping(df_orderlines, orders_number):
	'''Mapping orders with wave number'''
	df_orderlines.sort_values(by='DATE', ascending = True, inplace = True)
	# Unique order numbers list
	list_orders = df_orderlines.OrderNumber.unique()
	dict_map = dict(zip(list_orders, [i for i in range(1, len(list_orders))]))
	# Order ID mapping
	df_orderlines['OrderID'] = df_orderlines['OrderNumber'].map(dict_map)
	# Grouping Orders by Wave of orders_number 
	df_orderlines['WaveID'] = (df_orderlines.OrderID%orders_number == 0).shift(1).fillna(0).cumsum()
	# Counting number of Waves
	waves_number = df_orderlines.WaveID.max() + 1
	return df_orderlines, waves_number

In [79]:
lines, wave_num = orderlines_mapping(df, 3)

In [91]:
(lines.OrderID%4 == 0).shift(1).fillna(0)#.cumsum()

4803        0
4778    False
4769    False
4853    False
4805     True
        ...
1205    False
1206    False
1207    False
1209    False
3614    False
Name: OrderID, Length: 5000, dtype: object

In [100]:
list_locs = list(df['Coord'].apply(lambda t: literal_eval(t)).values)
list_locs.sort()
# List of unique coordinates
[print(k) for k,_ in itertools.groupby(list_locs)]
# list_locs = list(k for k,_ in itertools.groupby(list_locs))

[15.25, 6.0]
[15.25, 9.0]
[15.25, 10.5]
[15.25, 12.0]
[15.25, 21.0]
[19.5, 6.0]
[19.5, 9.0]
[19.5, 10.5]
[19.5, 12.0]
[19.5, 13.5]
[19.5, 15.0]
[19.5, 16.5]
[19.5, 18.0]
[19.5, 19.5]
[19.5, 21.0]
[20.75, 6.0]
[20.75, 9.0]
[20.75, 10.5]
[20.75, 12.0]
[20.75, 13.5]
[20.75, 15.0]
[20.75, 16.5]
[20.75, 18.0]
[20.75, 19.5]
[20.75, 21.0]
[20.75, 22.5]
[22.75, 6.0]
[22.75, 9.0]
[22.75, 10.5]
[22.75, 12.0]
[22.75, 13.5]
[22.75, 15.0]
[22.75, 16.5]
[22.75, 18.0]
[22.75, 19.5]
[22.75, 21.0]
[22.75, 22.5]
[24, 6.0]
[24, 9.0]
[24, 10.5]
[24, 12.0]
[24, 13.5]
[24, 15.0]
[24, 16.5]
[24, 18.0]
[24, 19.5]
[24, 21.0]
[24, 22.5]
[26, 6.0]
[26, 9.0]
[26, 10.5]
[26, 12.0]
[26, 13.5]
[26, 15.0]
[26, 16.5]
[26, 18.0]
[26, 19.5]
[26, 21.0]
[26, 22.5]
[28.0, 6.0]
[28.0, 9.0]
[28.0, 10.5]
[28.0, 12.0]
[28.0, 13.5]
[28.0, 15.0]
[28.0, 16.5]
[28.0, 18.0]
[28.0, 21.0]
[28.0, 22.5]
[29.25, 6.0]
[29.25, 9.0]
[29.25, 10.5]
[29.25, 12.0]
[29.25, 13.5]
[29.25, 18.0]
[31.25, 6.0]
[31.25, 9.0]
[31.25, 10.5]
[31.25, 12.0]
[31.25, 13.5]
[31.25, 16.5]
[31.25, 18.0]
[31.25, 19.5]
[31.25, 21.0]
[31.25, 22.5]
[32.5, 6.0]
[32.5, 9.0]
[32.5, 10.5]
[32.5, 12.0]
[32.5, 13.5]
[32.5, 15.0]
[32.5, 16.5]
[32.5, 18.0]
[32.5, 19.5]
[32.5, 21.0]
[32.5, 22.5]
[34.5, 6.0]
[34.5, 9.0]
[34.5, 10.5]
[34.5, 12.0]
[34.5, 13.5]
[34.5, 15.0]
[34.5, 16.5]
[34.5, 18.0]
[34.5, 19.5]
[34.5, 21.0]
[34.5, 22.5]
[35.75, 9.0]
[35.75, 10.5]
[35.75, 12.0]
[35.75, 13.5]
[35.75, 15.0]
[35.75, 16.5]
[35.75, 18.0]
[35.75, 19.5]
[35.75, 21.0]
[35.75, 22.5]
[37.75, 6.0]
[37.75, 9.0]
[37.75, 10.5]
[37.75, 12.0]
[37.75, 13.5]
[37.75, 15.0]
[37.75, 16.5]
[37.75, 18.0]
[37.75, 19.5]
[37.75, 21.0]
[39.0, 9.0]
[39.0, 10.5]
[39.0, 12.0]
[39.0, 13.5]
[39.0, 15.0]
[39.0, 16.5]
[39.0, 18.0]
[39.0, 19.5]
[41.0, 9.0]
[41.0, 10.5]
[41.0, 12.0]
[41.0, 13.5]
[41.0, 15.0]
[41.0, 16.5]
[41.0, 18.0]
[41.0, 19.5]
[41.0, 21.0]
[41.0, 22.5]
[42.25, 6.0]
[42.25, 9.0]
[42.25, 10.5]
[42.25, 12.0]
[42.25, 13.5]
[42.25, 15.0]
[42.25, 16.5]
[42.25, 18.0]
[44.25, 6.0]
[44.25, 9.0]
[44.25, 10.5]
[44.25, 12.0]
[44.25, 13.5]
[44.25, 15.0]
[44.25, 16.5]
[44.25, 18.0]
[44.25, 19.5]
[44.25, 21.0]
[44.25, 22.5]
[45.5, 6.0]
[45.5, 10.5]
[45.5, 12.0]
[45.5, 13.5]
[45.5, 15.0]
[45.5, 16.5]
[45.5, 18.0]
[45.5, 19.5]
[45.5, 21.0]
[45.5, 22.5]
[47.5, 6.0]
[47.5, 9.0]
[47.5, 10.5]
[47.5, 12.0]
[47.5, 13.5]
[47.5, 15.0]
[47.5, 16.5]
[47.5, 18.0]
[47.5, 19.5]
[47.5, 21.0]
[47.5, 22.5]
[48.75, 6.0]
[48.75, 9.0]
[48.75, 10.5]
[48.75, 12.0]
[48.75, 13.5]
[48.75, 16.5]
[48.75, 19.5]
[48.75, 21.0]
[48.75, 22.5]
[50.75, 6.0]
[50.75, 9.0]
[50.75, 10.5]
[50.75, 12.0]
[50.75, 13.5]
[52.0, 6.0]
[52.0, 9.0]
[52.0, 10.5]
[52.0, 12.0]
[52.0, 13.5]
[52.0, 15.0]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [99]:
list_locs

[[15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 6.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 9.0],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 10.5],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 12.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [15.25, 21.0],
 [19.5, 6.0],
 [19.5, 6.0],
 [19.5, 6.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 9.0],
 [19.5, 10.5],
 [19.5, 10.5],
 [19.5, 10.5],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 12.0],
 [19.5, 13.5],
 [19.5, 13.5],
 [19.5, 13.5],
 [19.5, 13.5],
 [19.5, 15.0],
 [19.5, 15.0],
 [19.5, 15.0],
 [19.5, 15.0],
 [19.5, 15.0],
 [19.5, 15.0],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 16.5],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 18.0],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 19.5],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [19.5, 21.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 6.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 9.0],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 10.5],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 [20.75, 12.0],
 ...]

In [74]:
# Alley Coordinates on y-axis
y_low, y_high = 5.5, 50
# Origin Location
origin_loc = [0, y_low]
df_waves, df_results = simulate_batch(1, 10, y_low, y_high, origin_loc, 1000, df) #num_orders

NameError: name 'simulate_batch' is not defined

In [101]:
test = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})

test.groupby(['Animal'])\

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_13888/1294718826.py, line 5)

## Methodology of experimentation
1. Shuffle the locations of SKUs as it may be skewed to SKUs too near or too far from the starting point. Alternatively, swap the starting point from bottom left to top right.

2.

## Group orders by First Come First serve 

## Constraints
1. Whole number of invoice

## Assumptions
1. N = 10, should it even be necessary? 
2. I can sort the DATE field, which is when the order that must be fulfilled by

In [229]:
N = 10
pallet_size = {
    "w": 100,
    "l": 120
}
def dict2df(cur_dict,cols):
    cur_df = pd.DataFrame(columns = cols)
    for k,v in cur_dict.items():
        cur_df = pd.concat([cur_df,v])
    return cur_df
def sortOrdersFCFS(df):
    col = 'OrderNumber'
    unique_orders = df[col].unique()
    print(unique_orders)
    order_num_to_lines = {}
    for uon in unique_orders:
        order_num_to_lines[uon] = df[df[col] == uon]
#     print(order_num_to_lines)
    
    return dict2df(order_num_to_lines, df.columns), order_num_to_lines#pd.DataFrame.from_dict(order_num_to_lines,orient='index')

def total_area_lines(lines):
    total_area = 0
#     print(lines)
#     print(type(lines))
    for idx, line in lines.iterrows():
#         print(line)
        w = line["Size"][0] / 10
        l = line["Size"][1] / 10
        qty = line["PCS"]
        area = w * l * qty
        total_area += area
    return total_area

def batch_FCFS(otld,n_max = 100):#otld df
    """returns a list of batches, each batch is a list of order numbers"""
    on_col = 'OrderNumber'
    unique_orders = df[on_col].unique()
#     batch_id = 0
    batch_list = []
    cur_batch = [] # order numbers only
    cur_size = 0
    max_size = pallet_size["w"] * pallet_size["l"]
    for uon in unique_orders:
        lines = otld[uon] #df[df[on_col] == uon]
        order_area = total_area_lines(lines)
#         print(f'order_area: {order_area}')
        if (cur_size + order_area) > max_size or len(cur_batch) >= n_max:
            # Num of orders in batch
            print(len(cur_batch))
            batch_list.append(cur_batch)
            cur_size = 0
            cur_batch = []
            continue
        cur_batch.append(uon)
        cur_size += order_area
    
    # NUM OF BATCHES
    print(len(batch_list))
    return batch_list

def batch_SINGLE_ORDER():
    on_col = 'OrderNumber'
    unique_orders = df[on_col].unique()
    return [[x] for x in unique_orders]

def coords_str_to_list(df, col):
    return list(df[col].apply(lambda t: literal_eval(t)).values)

def gen_SKU_dict(df):
#     df['SKU']
    sku_dict = {}
    for idx, row in df.iterrows():
        this_SKU = row['SKU']
        sku_dict[this_SKU] = row[['Size','Coord','AlleyCell','Alley_Number','Location']]
    return sku_dict

In [134]:
df['Coord'] = coords_str_to_list(df,'Coord')
df['Size'] = coords_str_to_list(df,'Size')

In [230]:
sorted_df = df.sort_values(by='DATE')

In [231]:
order_sorted_df,order_to_lines_dict = sortOrdersFCFS(sorted_df)

[3752394 3753500 3753577 ... 3774694 3774695 3774666]

In [262]:
batch_list = batch_FCFS(order_to_lines_dict,10)
# batch_list = batch_SINGLE_ORDER()

10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
6
10
10
4
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
7
10
10
10
10
10
10
10
10
10
10
1
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
7
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
9
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
328

In [233]:
# sorted_sku_df = df.sort_values(by='SKU')
sku_dict = gen_SKU_dict(sorted_df)  #sku_dict[230976]

In [257]:
y_low, y_high = 5.5, 50
def get_walk_dist(p1,p2):
    """Cur assumption, floorplan is a simple layout of rows"""
    # Start Point
    x1, y1 = p1[0], p1[1]
    # End Point
    x2, y2 = p2[0], p2[1]
    # Distance x-axis
    distance_x = abs(x2 - x1)
    # Distance y-axis
    if x1 == x2:
        distance_y1 = abs(y2 - y1)
        distance_y2 = distance_y1
    else:
        distance_y1 = y_high - y1 + y_high - y2
        distance_y2 = (y1 - y_low) + (y2 - y_low)
    # Minimum distance on y-axis 
    distance_y = min(distance_y1, distance_y2)
    # Total distance
    distance = distance_x + distance_y
    return int(distance)
def zig_zag_routing(list_locs, cur_pos):
    """Just returns the distance following zig zag"""
    
    total_dist = 0
    for loc in list_locs:
        total_dist += get_walk_dist(cur_pos, loc)
        cur_pos = loc
    return total_dist

# def zig_zag_routing_w_sku(sku_df, cur_pos):
#     """Returns total zig zag distance + walking distance per SKU"""
    
#     total_dist = 0
#     for loc in list_locs:
#         total_dist += get_walk_dist(cur_pos, loc)
#         cur_pos = loc
#     return total_dist


def sort_locations(list_locs):
    return sorted(list_locs)

def sort_loc_df(sku_df):
#     print(sku_df.head())
#     print(sku_df['Coord'])
    return sku_df.sort_values(by="Coord")

#sku 2 dist

def get_sku_piece_counts(otld):
    on_col = 'OrderNumber'
    unique_orders = df[on_col].unique()
    sku_pieces = {}
    for uon in unique_orders:
        for idx, row in otld[uon].iterrows():
            cur_sku = row['SKU']
            if cur_sku in sku_pieces:
                sku_pieces[cur_sku] += row["PCS"]
            else:
                sku_pieces[cur_sku] = row["PCS"]
    return sku_pieces

def get_total_walking_dist(batch_list,otld,sku_dict): #batch
    cur_positions = [[0, 5.5], [100, y_high]]
    total_dists = []
    batch_dists = []
    for cur_pos in cur_positions:
        total_dist = 0
        for batch in batch_list:
            list_locs = []
            skus = set()
            for order_num in batch:
                for idx, line in otld[order_num].iterrows():
                    skus.add(line['SKU'])
            for sku in skus:
                list_locs.append(sku_dict[sku]['Coord'])
            sorted_list_locs = sort_locations(list_locs)
#             print(sorted_list_locs[:10])
            batch_dist = zig_zag_routing(sorted_list_locs,cur_pos)
            
            batch_dists.append(batch_dist)
            total_dist += batch_dist
        print(f"total_dist: {total_dist}")
        print(batch_dists[-10:])
        total_dists.append(total_dist)
    return sum(total_dists) / len(total_dists), batch_dists

def get_walking_dist_per_sku(batch_list,otld,sku_dict): #batch
    cur_positions = [[5.5, y_low], [50, y_high]]
    total_dists = []
    batch_dists = []
    sku_dists = {}
    for cur_pos in cur_positions:
        total_dist = 0
        for batch in batch_list:
            list_locs = []
            sku_df = pd.DataFrame()
            skus = set()
            for order_num in batch:
                for idx, line in otld[order_num].iterrows():
                    skus.add(line['SKU'])
            for sku in skus:
#                 sku_df = pd.concat([sku_df,sku_dict[sku]],axis=1)
                sku_df = sku_df.append(sku_dict[sku],ignore_index=True)
            sku_df = sort_loc_df(sku_df)
            batch_dist = zig_zag_routing(sku_df['Coord'],cur_pos)
            for sku in skus:
                if sku in sku_dists:
                    sku_dists[sku].append(batch_dist)
                else:
                    sku_dists[sku] = []
            batch_dists.append(batch_dist)
            total_dist += batch_dist
        total_dists.append(total_dist)
    return sum(total_dists) / len(total_dists), batch_dists, sku_dists

In [263]:
avg_total_dist, batch_dists = get_total_walking_dist(batch_list,order_to_lines_dict,sku_dict)

total_dist: 65146
[150, 146, 171, 142, 157, 144, 216, 188, 195, 140]
total_dist: 93700
[236, 242, 249, 227, 261, 248, 294, 271, 273, 244]

In [264]:
avg_total_dist

79423.0

In [206]:
sku_pieces = get_sku_piece_counts(order_to_lines_dict)

In [ ]:
avg_total_dist, batch_dists,sku_dist = get_walking_dist_per_sku(batch_list,order_to_lines_dict,sku_dict)

0     [47.5, 18.0]
1      [39.0, 9.0]
2    [31.25, 10.5]
3    [44.25, 12.0]
4     [42.25, 9.0]
5     [32.5, 21.0]
6    [20.75, 21.0]
7     [32.5, 22.5]
8     [19.5, 21.0]
9    [44.25, 10.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [44.25, 10.5]
2      [34.5, 12.0]
3     [44.25, 22.5]
4     [31.25, 16.5]
5      [20.75, 9.0]
6       [47.5, 6.0]
7     [22.75, 15.0]
8     [35.75, 13.5]
9     [22.75, 15.0]
10     [41.0, 13.5]
11     [19.5, 21.0]
12     [39.0, 12.0]
Name: Coord, dtype: object
0      [44.25, 6.0]
1      [45.5, 13.5]
2      [39.0, 12.0]
3      [45.5, 22.5]
4     [44.25, 22.5]
5     [15.25, 21.0]
6     [44.25, 21.0]
7      [19.5, 19.5]
8     [31.25, 16.5]
9      [19.5, 21.0]
10       [26, 21.0]
11    [44.25, 13.5]
Name: Coord, dtype: object
0    [44.25, 16.5]
1     [32.5, 15.0]
2    [37.75, 21.0]
3     [32.5, 21.0]
4    [35.75, 22.5]
5    [37.75, 15.0]
6        [24, 9.0]
7    [44.25, 16.5]
8     [19.5, 21.0]
9     [45.5, 19.5]
Name: Coord, dtype: object
0      [34.5, 16.5]
1     [37.75, 13.5]
2     [22.75, 12.0]
3     [31.25, 13.5]
4      [34.5, 15.0]
5      [20.75, 9.0]
6      [34.5, 15.0]
7       [47.5, 6.0]
8      [19.5, 21.0]
9      [41.0, 15.0]
10     [34.5, 15.0]
11       [24, 10.5]
Name: Coord, dtype: object
0     [45.5, 13.5]
1       [24, 19.5]
2       [24, 16.5]
3    [42.25, 12.0]
4    [20.75, 16.5]
5       [26, 15.0]
6    [44.25, 15.0]
7       [24, 18.0]
8      [34.5, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1       [32.5, 6.0]
2      [34.5, 13.5]
3     [44.25, 12.0]
4      [20.75, 9.0]
5      [45.5, 16.5]
6        [24, 18.0]
7        [26, 19.5]
8      [34.5, 10.5]
9        [26, 21.0]
10    [20.75, 12.0]
11     [41.0, 10.5]
12       [24, 21.0]
13        [24, 9.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0      [44.25, 9.0]
1     [37.75, 21.0]
2        [26, 16.5]
3      [32.5, 21.0]
4        [26, 22.5]
5     [22.75, 15.0]
6     [42.25, 13.5]
7      [41.0, 10.5]
8      [48.75, 9.0]
9        [24, 18.0]
10     [39.0, 15.0]
Name: Coord, dtype: object
0    [44.25, 12.0]
1     [47.5, 10.5]
2    [37.75, 13.5]
3    [22.75, 12.0]
4    [37.75, 16.5]
5    [29.25, 10.5]
6    [31.25, 12.0]
7     [41.0, 13.5]
8    [42.25, 16.5]
9      [28.0, 9.0]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [24, 21.0]
2        [24, 19.5]
3      [34.5, 21.0]
4      [20.75, 9.0]
5       [52.0, 9.0]
6      [32.5, 18.0]
7        [26, 15.0]
8        [26, 10.5]
9     [22.75, 12.0]
10     [45.5, 16.5]
11       [26, 13.5]
12    [20.75, 12.0]
13    [20.75, 12.0]
Name: Coord, dtype: object
0     [44.25, 21.0]
1       [28.0, 9.0]
2      [28.0, 16.5]
3         [24, 9.0]
4      [41.0, 15.0]
5     [29.25, 13.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11       [26, 21.0]
12       [24, 21.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [32.5, 6.0]
1        [26, 6.0]
2    [42.25, 15.0]
3    [31.25, 12.0]
4    [20.75, 10.5]
5     [32.5, 12.0]
6       [24, 12.0]
7        [26, 6.0]
8    [20.75, 15.0]
9     [52.0, 13.5]
Name: Coord, dtype: object
0      [28.0, 15.0]
1       [28.0, 6.0]
2     [22.75, 22.5]
3      [20.75, 6.0]
4     [20.75, 10.5]
5         [26, 6.0]
6        [24, 15.0]
7      [42.25, 9.0]
8     [22.75, 15.0]
9        [24, 12.0]
10     [50.75, 9.0]
11     [41.0, 15.0]
12        [24, 9.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0    [44.25, 21.0]
1     [19.5, 13.5]
2     [41.0, 10.5]
3    [22.75, 13.5]
4     [28.0, 16.5]
5        [24, 6.0]
6     [22.75, 6.0]
7       [24, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [44.25, 21.0]
2     [22.75, 21.0]
3      [32.5, 12.0]
4     [15.25, 21.0]
5      [39.0, 12.0]
6      [20.75, 6.0]
7     [37.75, 12.0]
8      [45.5, 16.5]
9     [35.75, 21.0]
10     [20.75, 6.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 9.0]
1       [26, 21.0]
2        [24, 6.0]
3     [41.0, 13.5]
4     [41.0, 15.0]
5    [20.75, 18.0]
6     [50.75, 9.0]
7    [22.75, 19.5]
8       [24, 10.5]
9       [24, 21.0]
Name: Coord, dtype: object
0     [42.25, 12.0]
1     [22.75, 12.0]
2       [32.5, 6.0]
3     [44.25, 21.0]
4     [42.25, 12.0]
5      [32.5, 21.0]
6     [15.25, 10.5]
7     [42.25, 10.5]
8     [42.25, 13.5]
9       [32.5, 6.0]
10     [41.0, 13.5]
11     [41.0, 15.0]
12     [19.5, 12.0]
Name: Coord, dtype: object
0        [24, 9.0]
1    [22.75, 10.5]
2        [24, 9.0]
3       [24, 13.5]
4    [29.25, 13.5]
5       [26, 15.0]
6    [22.75, 10.5]
7     [50.75, 9.0]
8     [52.0, 13.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0    [20.75, 22.5]
1    [37.75, 13.5]
2    [22.75, 12.0]
3    [37.75, 18.0]
4    [22.75, 15.0]
5    [31.25, 10.5]
6        [24, 6.0]
7        [24, 9.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 12.0]
1     [37.75, 13.5]
2        [24, 13.5]
3     [22.75, 12.0]
4      [41.0, 19.5]
5     [42.25, 10.5]
6      [41.0, 19.5]
7      [45.5, 10.5]
8        [24, 18.0]
9     [22.75, 12.0]
10    [42.25, 15.0]
11     [28.0, 22.5]
12    [20.75, 12.0]
13     [41.0, 15.0]
14    [20.75, 12.0]
15    [20.75, 12.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0         [26, 6.0]
1     [22.75, 16.5]
2        [24, 21.0]
3        [24, 13.5]
4        [24, 19.5]
5         [26, 6.0]
6     [22.75, 18.0]
7      [44.25, 9.0]
8      [45.5, 16.5]
9     [20.75, 18.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1        [26, 15.0]
2        [24, 21.0]
3        [26, 16.5]
4        [24, 16.5]
5     [20.75, 22.5]
6      [47.5, 22.5]
7      [32.5, 13.5]
8      [39.0, 15.0]
9     [15.25, 12.0]
10    [20.75, 16.5]
11    [20.75, 10.5]
12     [28.0, 13.5]
13     [28.0, 13.5]
14        [24, 9.0]
15       [24, 21.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1       [39.0, 9.0]
2     [37.75, 16.5]
3      [41.0, 16.5]
4     [22.75, 12.0]
5     [22.75, 12.0]
6     [20.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [22.75, 16.5]
11        [24, 6.0]
12       [24, 19.5]
13    [37.75, 18.0]
14     [19.5, 21.0]
15    [22.75, 13.5]
16     [45.5, 22.5]
17    [20.75, 12.0]
18     [34.5, 12.0]
19    [22.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 16.5]
1      [15.25, 6.0]
2     [20.75, 22.5]
3      [34.5, 16.5]
4      [37.75, 9.0]
5     [35.75, 15.0]
6       [28.0, 9.0]
7      [34.5, 15.0]
8     [15.25, 10.5]
9      [19.5, 21.0]
10     [32.5, 18.0]
11       [24, 12.0]
12       [24, 12.0]
13       [24, 10.5]
14     [22.75, 6.0]
15       [24, 13.5]
Name: Coord, dtype: object
0      [45.5, 19.5]
1      [44.25, 6.0]
2     [22.75, 12.0]
3     [44.25, 16.5]
4     [48.75, 12.0]
5     [37.75, 15.0]
6      [39.0, 15.0]
7      [19.5, 21.0]
8         [24, 6.0]
9      [45.5, 15.0]
10     [19.5, 19.5]
11    [35.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 18.0]
1        [26, 10.5]
2      [20.75, 9.0]
3      [32.5, 22.5]
4      [20.75, 9.0]
5     [35.75, 13.5]
6     [35.75, 22.5]
7     [44.25, 22.5]
8     [42.25, 12.0]
9      [19.5, 21.0]
10    [20.75, 10.5]
11     [28.0, 13.5]
12    [35.75, 21.0]
13    [22.75, 18.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1      [34.5, 16.5]
2     [35.75, 13.5]
3     [44.25, 16.5]
4     [35.75, 16.5]
5      [37.75, 6.0]
6      [32.5, 21.0]
7         [24, 9.0]
8       [47.5, 9.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11     [41.0, 10.5]
12     [28.0, 10.5]
13    [20.75, 12.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1      [44.25, 6.0]
2     [37.75, 12.0]
3     [20.75, 10.5]
4     [37.75, 21.0]
5      [42.25, 9.0]
6         [24, 9.0]
7      [19.5, 21.0]
8      [31.25, 9.0]
9     [20.75, 12.0]
10    [22.75, 12.0]
11       [24, 21.0]
Name: Coord, dtype: object
0     [20.75, 12.0]
1      [41.0, 16.5]
2     [20.75, 12.0]
3      [44.25, 9.0]
4      [39.0, 10.5]
5     [22.75, 15.0]
6     [20.75, 18.0]
7      [19.5, 21.0]
8     [22.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11       [26, 16.5]
12    [22.75, 15.0]
13    [42.25, 10.5]
14     [22.75, 6.0]
Name: Coord, dtype: object
0      [42.25, 9.0]
1     [20.75, 10.5]
2      [32.5, 22.5]
3     [22.75, 15.0]
4       [19.5, 9.0]
5     [15.25, 10.5]
6       [32.5, 9.0]
7        [26, 15.0]
8      [39.0, 12.0]
9      [50.75, 9.0]
10     [41.0, 15.0]
11     [28.0, 10.5]
12     [28.0, 15.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1         [24, 9.0]
2     [44.25, 19.5]
3      [45.5, 19.5]
4     [48.75, 12.0]
5      [34.5, 13.5]
6     [22.75, 18.0]
7      [47.5, 10.5]
8      [19.5, 21.0]
9      [31.25, 9.0]
10       [26, 12.0]
Name: Coord, dtype: object
0      [32.5, 19.5]
1     [44.25, 21.0]
2     [22.75, 13.5]
3      [19.5, 18.0]
4       [19.5, 9.0]
5     [22.75, 15.0]
6     [15.25, 10.5]
7      [45.5, 10.5]
8     [42.25, 10.5]
9      [52.0, 13.5]
10       [24, 13.5]
Name: Coord, dtype: object
0    [37.75, 13.5]
1       [24, 13.5]
2    [22.75, 12.0]
3        [24, 9.0]
4       [26, 10.5]
5    [20.75, 18.0]
6     [41.0, 13.5]
7     [19.5, 21.0]
8        [24, 6.0]
9     [50.75, 9.0]
Name: Coord, dtype: object
0     [37.75, 21.0]
1     [20.75, 12.0]
2     [44.25, 22.5]
3        [24, 13.5]
4        [26, 16.5]
5     [44.25, 10.5]
6     [44.25, 21.0]
7      [34.5, 10.5]
8       [39.0, 9.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11    [22.75, 12.0]
12        [24, 9.0]
13    [20.75, 12.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [47.5, 10.5]
1     [32.5, 18.0]
2     [47.5, 13.5]
3     [32.5, 19.5]
4       [26, 22.5]
5     [20.75, 6.0]
6     [19.5, 21.0]
7    [35.75, 12.0]
8     [22.75, 6.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 16.5]
2      [34.5, 15.0]
3      [47.5, 16.5]
4     [35.75, 12.0]
5      [45.5, 10.5]
6      [45.5, 10.5]
7      [32.5, 22.5]
8      [19.5, 21.0]
9      [35.75, 9.0]
10    [22.75, 21.0]
11    [48.75, 16.5]
Name: Coord, dtype: object
0      [32.5, 19.5]
1       [39.0, 9.0]
2      [28.0, 18.0]
3      [31.25, 9.0]
4     [22.75, 16.5]
5        [26, 18.0]
6        [24, 12.0]
7        [24, 12.0]
8     [44.25, 13.5]
9     [20.75, 16.5]
10     [47.5, 22.5]
11     [19.5, 21.0]
12     [39.0, 16.5]
13     [28.0, 21.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0      [45.5, 10.5]
1       [39.0, 9.0]
2     [22.75, 15.0]
3       [41.0, 9.0]
4     [22.75, 12.0]
5      [19.5, 21.0]
6     [20.75, 12.0]
7     [20.75, 12.0]
8      [34.5, 15.0]
9      [47.5, 12.0]
10    [22.75, 19.5]
11      [52.0, 6.0]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 9.0]
2     [31.25, 21.0]
3        [26, 13.5]
4      [44.25, 9.0]
5     [31.25, 21.0]
6      [20.75, 9.0]
7      [39.0, 15.0]
8      [45.5, 10.5]
9       [47.5, 6.0]
10      [47.5, 9.0]
11     [32.5, 19.5]
12       [24, 16.5]
13       [24, 16.5]
14     [19.5, 21.0]
15      [39.0, 9.0]
16    [48.75, 19.5]
17    [48.75, 21.0]
18     [19.5, 18.0]
19      [47.5, 9.0]
Name: Coord, dtype: object
0      [15.25, 6.0]
1      [37.75, 6.0]
2     [37.75, 13.5]
3        [24, 21.0]
4     [22.75, 12.0]
5     [48.75, 12.0]
6     [15.25, 21.0]
7     [22.75, 21.0]
8     [44.25, 12.0]
9     [15.25, 10.5]
10     [32.5, 18.0]
11     [19.5, 21.0]
12       [24, 13.5]
Name: Coord, dtype: object
0     [48.75, 10.5]
1      [42.25, 9.0]
2     [22.75, 12.0]
3      [20.75, 9.0]
4     [35.75, 13.5]
5     [22.75, 15.0]
6      [41.0, 13.5]
7      [19.5, 21.0]
8      [45.5, 22.5]
9     [44.25, 10.5]
10     [52.0, 12.0]
11       [24, 21.0]
Name: Coord, dtype: object

0      [47.5, 21.0]
1       [47.5, 6.0]
2      [32.5, 18.0]
3      [45.5, 19.5]
4      [22.75, 6.0]
5     [44.25, 21.0]
6     [22.75, 13.5]
7        [24, 12.0]
8        [24, 12.0]
9      [44.25, 9.0]
10     [19.5, 21.0]
11    [37.75, 10.5]
12    [35.75, 19.5]
Name: Coord, dtype: object
0       [24, 19.5]
1    [44.25, 10.5]
2     [32.5, 21.0]
3      [34.5, 6.0]
4     [45.5, 10.5]
5    [35.75, 22.5]
6      [47.5, 9.0]
7     [19.5, 21.0]
8     [44.25, 9.0]
9    [44.25, 22.5]
Name: Coord, dtype: object
0       [26, 10.5]
1    [48.75, 12.0]
2    [22.75, 13.5]
3        [26, 6.0]
4     [32.5, 19.5]
5     [39.0, 19.5]
6      [47.5, 9.0]
7     [19.5, 21.0]
8       [24, 10.5]
9    [35.75, 21.0]
Name: Coord, dtype: object
0      [39.0, 18.0]
1      [45.5, 12.0]
2      [32.5, 19.5]
3     [35.75, 13.5]
4        [26, 22.5]
5       [32.5, 6.0]
6     [35.75, 10.5]
7     [44.25, 18.0]
8      [19.5, 21.0]
9     [31.25, 10.5]
10     [34.5, 22.5]
Name: Coord, dtype: object
0     [34.5, 21.0]
1     [34.5, 15.0]
2     [20.75, 9.0]
3     [32.5, 19.5]
4    [22.75, 15.0]
5    [35.75, 22.5]
6     [45.5, 19.5]
7      [47.5, 9.0]
8     [19.5, 21.0]
9    [20.75, 18.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1     [29.25, 13.5]
2     [22.75, 22.5]
3      [32.5, 18.0]
4     [35.75, 21.0]
5     [48.75, 12.0]
6      [41.0, 21.0]
7     [22.75, 15.0]
8         [26, 6.0]
9      [45.5, 12.0]
10    [20.75, 10.5]
11       [24, 21.0]
12     [47.5, 21.0]
Name: Coord, dtype: object
0       [24, 19.5]
1     [22.75, 6.0]
2     [20.75, 9.0]
3       [26, 22.5]
4     [19.5, 21.0]
5        [24, 6.0]
6       [26, 13.5]
7    [44.25, 22.5]
Name: Coord, dtype: object
0      [44.25, 9.0]
1      [47.5, 18.0]
2     [35.75, 21.0]
3      [19.5, 18.0]
4     [37.75, 16.5]
5      [20.75, 9.0]
6     [31.25, 12.0]
7     [22.75, 15.0]
8      [19.5, 21.0]
9      [28.0, 22.5]
10     [50.75, 9.0]
Name: Coord, dtype: object
0        [24, 21.0]
1        [26, 19.5]
2     [37.75, 13.5]
3     [42.25, 10.5]
4      [34.5, 15.0]
5        [26, 22.5]
6        [26, 19.5]
7      [32.5, 12.0]
8     [44.25, 10.5]
9      [20.75, 6.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [47.5, 10.5]
1       [24, 19.5]
2     [20.75, 9.0]
3    [44.25, 21.0]
4      [39.0, 9.0]
5     [29.25, 6.0]
6       [24, 18.0]
7    [37.75, 18.0]
8     [28.0, 16.5]
9    [31.25, 22.5]
Name: Coord, dtype: object
0         [26, 6.0]
1      [34.5, 12.0]
2      [41.0, 15.0]
3     [37.75, 13.5]
4        [24, 19.5]
5     [44.25, 10.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [37.75, 21.0]
9     [15.25, 21.0]
10    [22.75, 21.0]
11     [19.5, 21.0]
12       [26, 13.5]
13       [24, 18.0]
14     [39.0, 15.0]
15     [19.5, 15.0]
16    [37.75, 10.5]
Name: Coord, dtype: object
0      [37.75, 6.0]
1        [24, 19.5]
2     [37.75, 13.5]
3        [24, 19.5]
4     [22.75, 12.0]
5     [44.25, 10.5]
6     [22.75, 13.5]
7      [50.75, 6.0]
8     [44.25, 21.0]
9      [35.75, 9.0]
10    [31.25, 13.5]
11        [24, 9.0]
12       [24, 21.0]
13       [24, 13.5]
Name: Coord, dtype: object
0     [20.75, 9.0]
1     [32.5, 18.0]
2       [26, 18.0]
3    [20.75, 21.0]
4     [19.5, 21.0]
5    [22.75, 10.5]
6       [26, 15.0]
7       [26, 13.5]
8     [41.0, 15.0]
9     [28.0, 16.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1     [44.25, 10.5]
2      [22.75, 6.0]
3     [44.25, 21.0]
4      [32.5, 15.0]
5      [45.5, 22.5]
6        [24, 12.0]
7      [41.0, 13.5]
8       [32.5, 6.0]
9      [19.5, 12.0]
10    [42.25, 10.5]
11     [45.5, 15.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 15.0]
1    [22.75, 12.0]
2     [52.0, 15.0]
3    [48.75, 12.0]
4     [45.5, 18.0]
5    [31.25, 21.0]
6    [22.75, 15.0]
7     [19.5, 21.0]
8     [41.0, 15.0]
9    [42.25, 15.0]
Name: Coord, dtype: object
0      [28.0, 12.0]
1      [20.75, 9.0]
2      [32.5, 12.0]
3        [26, 22.5]
4        [24, 13.5]
5     [42.25, 15.0]
6         [26, 6.0]
7      [45.5, 15.0]
8      [47.5, 13.5]
9     [35.75, 12.0]
10     [45.5, 21.0]
11        [24, 9.0]
Name: Coord, dtype: object
0     [22.75, 21.0]
1        [24, 19.5]
2        [26, 21.0]
3         [24, 6.0]
4       [28.0, 9.0]
5     [29.25, 10.5]
6     [44.25, 21.0]
7       [39.0, 9.0]
8     [44.25, 10.5]
9      [19.5, 21.0]
10     [45.5, 16.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [35.75, 18.0]
1      [41.0, 22.5]
2      [45.5, 22.5]
3      [19.5, 19.5]
4     [22.75, 15.0]
5     [15.25, 10.5]
6     [37.75, 15.0]
7     [37.75, 16.5]
8     [44.25, 13.5]
9      [19.5, 21.0]
10      [32.5, 6.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 10.5]
1      [32.5, 18.0]
2         [24, 6.0]
3     [44.25, 16.5]
4     [31.25, 16.5]
5      [20.75, 9.0]
6      [20.75, 9.0]
7     [42.25, 15.0]
8      [19.5, 21.0]
9        [26, 21.0]
10     [34.5, 18.0]
11       [24, 12.0]
12     [19.5, 19.5]
13     [45.5, 10.5]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [34.5, 12.0]
1    [37.75, 21.0]
2    [22.75, 12.0]
3     [47.5, 10.5]
4     [19.5, 21.0]
Name: Coord, dtype: object
0     [37.75, 21.0]
1        [26, 22.5]
2     [29.25, 13.5]
3     [29.25, 13.5]
4     [37.75, 21.0]
5      [20.75, 9.0]
6     [22.75, 15.0]
7     [42.25, 13.5]
8      [41.0, 15.0]
9      [34.5, 16.5]
10        [26, 9.0]
11     [44.25, 9.0]
12     [19.5, 21.0]
13    [20.75, 18.0]
14     [41.0, 15.0]
15     [28.0, 18.0]
16     [41.0, 12.0]
17     [47.5, 16.5]
18    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [34.5, 12.0]
2      [28.0, 18.0]
3      [32.5, 15.0]
4      [20.75, 9.0]
5     [48.75, 12.0]
6      [41.0, 10.5]
7        [26, 22.5]
8      [45.5, 10.5]
9      [32.5, 18.0]
10     [19.5, 21.0]
11    [22.75, 10.5]
12       [24, 10.5]
13     [22.75, 6.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [20.75, 9.0]
1     [34.5, 15.0]
2     [20.75, 9.0]
3    [22.75, 15.0]
4       [24, 15.0]
5     [19.5, 21.0]
6     [28.0, 21.0]
Name: Coord, dtype: object
0        [24, 18.0]
1     [35.75, 21.0]
2      [20.75, 9.0]
3     [31.25, 16.5]
4        [24, 16.5]
5     [44.25, 19.5]
6        [26, 19.5]
7      [19.5, 21.0]
8     [44.25, 15.0]
9      [39.0, 12.0]
10     [47.5, 18.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1        [24, 13.5]
2     [42.25, 12.0]
3     [44.25, 16.5]
4      [20.75, 9.0]
5      [20.75, 9.0]
6      [34.5, 13.5]
7     [35.75, 10.5]
8      [41.0, 13.5]
9      [19.5, 21.0]
10    [35.75, 12.0]
11     [45.5, 13.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [22.75, 12.0]
2      [42.25, 9.0]
3      [34.5, 21.0]
4      [20.75, 9.0]
5     [15.25, 10.5]
6     [22.75, 15.0]
7     [20.75, 21.0]
8      [45.5, 22.5]
9      [19.5, 21.0]
10        [24, 6.0]
11     [41.0, 15.0]
12     [45.5, 15.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1      [52.0, 12.0]
2     [37.75, 13.5]
3      [20.75, 9.0]
4         [24, 9.0]
5     [20.75, 13.5]
6      [20.75, 9.0]
7        [26, 22.5]
8     [22.75, 15.0]
9     [37.75, 19.5]
10     [19.5, 21.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1      [47.5, 10.5]
2        [24, 10.5]
3      [20.75, 9.0]
4     [37.75, 12.0]
5      [48.75, 9.0]
6     [22.75, 21.0]
7     [15.25, 21.0]
8     [15.25, 21.0]
9     [22.75, 15.0]
10     [32.5, 22.5]
11    [42.25, 10.5]
12     [47.5, 10.5]
13       [24, 10.5]
Name: Coord, dtype: object
0     [22.75, 21.0]
1        [26, 10.5]
2     [20.75, 22.5]
3      [47.5, 21.0]
4     [44.25, 15.0]
5      [52.0, 13.5]
6      [41.0, 15.0]
7     [44.25, 12.0]
8      [32.5, 10.5]
9     [44.25, 12.0]
10    [42.25, 18.0]
11    [42.25, 16.5]
12       [24, 10.5]
13     [20.75, 6.0]
14       [24, 10.5]
15     [45.5, 15.0]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [47.5, 10.5]
2      [28.0, 18.0]
3      [44.25, 9.0]
4      [20.75, 9.0]
5     [48.75, 12.0]
6     [22.75, 21.0]
7        [26, 22.5]
8     [22.75, 15.0]
9     [15.25, 21.0]
10    [15.25, 21.0]
11    [44.25, 13.5]
12     [39.0, 12.0]
13     [41.0, 18.0]
14       [24, 18.0]
Name: Coord, dtype: object
0     [41.0, 16.5]
1       [24, 21.0]
2        [26, 6.0]
3       [26, 22.5]
4       [26, 15.0]
5     [41.0, 10.5]
6    [42.25, 16.5]
7     [41.0, 18.0]
8       [24, 10.5]
9     [50.75, 9.0]
Name: Coord, dtype: object
0     [20.75, 22.5]
1      [47.5, 10.5]
2      [41.0, 15.0]
3     [35.75, 21.0]
4     [15.25, 21.0]
5     [22.75, 21.0]
6     [20.75, 12.0]
7       [32.5, 9.0]
8       [28.0, 9.0]
9      [41.0, 15.0]
10        [24, 6.0]
11       [24, 12.0]
12    [35.75, 19.5]
13       [24, 10.5]
Name: Coord, dtype: object

0      [45.5, 13.5]
1     [31.25, 12.0]
2      [41.0, 13.5]
3       [32.5, 6.0]
4        [26, 22.5]
5        [24, 13.5]
6         [24, 9.0]
7      [41.0, 16.5]
8      [41.0, 15.0]
9        [26, 22.5]
10       [24, 10.5]
11       [24, 10.5]
Name: Coord, dtype: object
0     [37.75, 21.0]
1     [35.75, 21.0]
2      [20.75, 9.0]
3      [34.5, 18.0]
4     [22.75, 18.0]
5         [24, 9.0]
6     [48.75, 10.5]
7        [24, 16.5]
8      [19.5, 16.5]
9     [22.75, 10.5]
10     [41.0, 15.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [34.5, 9.0]
1      [20.75, 9.0]
2       [52.0, 6.0]
3        [26, 22.5]
4      [32.5, 21.0]
5       [28.0, 6.0]
6     [22.75, 12.0]
7      [41.0, 10.5]
8      [28.0, 21.0]
9         [26, 6.0]
10     [45.5, 15.0]
11     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1        [24, 16.5]
2        [24, 13.5]
3     [29.25, 13.5]
4     [37.75, 21.0]
5      [20.75, 9.0]
6      [34.5, 15.0]
7        [26, 22.5]
8         [24, 9.0]
9      [31.25, 6.0]
10     [32.5, 18.0]
11     [41.0, 16.5]
12    [22.75, 19.5]
13       [26, 15.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1      [28.0, 18.0]
2      [47.5, 19.5]
3      [20.75, 9.0]
4        [26, 22.5]
5     [22.75, 15.0]
6       [19.5, 9.0]
7     [15.25, 10.5]
8        [24, 12.0]
9      [41.0, 13.5]
10     [28.0, 16.5]
11     [41.0, 15.0]
12    [31.25, 12.0]
Name: Coord, dtype: object
0     [47.5, 12.0]
1     [32.5, 22.5]
2     [45.5, 22.5]
3       [26, 19.5]
4    [44.25, 21.0]
5     [32.5, 19.5]
6       [24, 10.5]
7     [32.5, 22.5]
8    [44.25, 15.0]
9     [41.0, 18.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [47.5, 10.5]
2        [24, 21.0]
3        [24, 19.5]
4      [47.5, 13.5]
5      [45.5, 15.0]
6        [26, 16.5]
7      [20.75, 6.0]
8     [20.75, 21.0]
9         [24, 6.0]
10     [22.75, 6.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1       [39.0, 9.0]
2        [24, 13.5]
3        [24, 21.0]
4      [45.5, 13.5]
5        [24, 19.5]
6     [48.75, 13.5]
7      [20.75, 9.0]
8     [44.25, 12.0]
9      [41.0, 10.5]
10    [42.25, 15.0]
11       [24, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1      [34.5, 12.0]
2      [41.0, 10.5]
3      [34.5, 16.5]
4      [41.0, 10.5]
5        [26, 22.5]
6     [22.75, 18.0]
7     [31.25, 16.5]
8     [31.25, 16.5]
9      [28.0, 13.5]
10       [26, 13.5]
11       [26, 19.5]
12    [20.75, 10.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [47.5, 21.0]
2     [35.75, 21.0]
3      [28.0, 18.0]
4     [44.25, 21.0]
5     [22.75, 21.0]
6      [39.0, 19.5]
7     [20.75, 16.5]
8      [47.5, 22.5]
9     [20.75, 18.0]
10     [41.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 6.0]
2     [20.75, 22.5]
3      [28.0, 18.0]
4      [42.25, 9.0]
5      [47.5, 21.0]
6      [20.75, 9.0]
7     [44.25, 21.0]
8      [19.5, 19.5]
9      [37.75, 6.0]
10    [15.25, 21.0]
11     [41.0, 13.5]
12        [26, 9.0]
13    [44.25, 10.5]
14     [47.5, 21.0]
15    [20.75, 16.5]
16    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1        [24, 21.0]
2        [24, 19.5]
3      [20.75, 9.0]
4      [48.75, 6.0]
5         [24, 9.0]
6      [20.75, 6.0]
7      [41.0, 13.5]
8      [34.5, 12.0]
9     [22.75, 12.0]
10    [22.75, 12.0]
11     [19.5, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 15.0]
1     [45.5, 22.5]
2     [45.5, 22.5]
3     [32.5, 21.0]
4    [44.25, 21.0]
5     [19.5, 21.0]
6       [24, 13.5]
7     [22.75, 6.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 19.5]
1        [24, 15.0]
2     [44.25, 21.0]
3      [20.75, 9.0]
4        [24, 16.5]
5      [41.0, 13.5]
6        [24, 12.0]
7     [20.75, 12.0]
8        [24, 16.5]
9      [41.0, 15.0]
10       [24, 18.0]
11     [52.0, 13.5]
12    [35.75, 19.5]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [47.5, 21.0]
2      [45.5, 13.5]
3     [44.25, 10.5]
4      [34.5, 12.0]
5      [22.75, 6.0]
6      [20.75, 6.0]
7     [29.25, 13.5]
8         [26, 6.0]
9        [24, 12.0]
10     [19.5, 21.0]
11     [20.75, 6.0]
12     [28.0, 22.5]
13       [24, 10.5]
Name: Coord, dtype: object
0        [26, 15.0]
1      [45.5, 13.5]
2     [44.25, 19.5]
3     [31.25, 22.5]
4     [22.75, 16.5]
5      [20.75, 9.0]
6     [22.75, 10.5]
7        [26, 18.0]
8      [41.0, 12.0]
9      [19.5, 21.0]
10     [44.25, 9.0]
11     [34.5, 12.0]
12    [42.25, 15.0]
13     [47.5, 21.0]
14       [24, 16.5]
Name: Coord, dtype: object
0      [39.0, 18.0]
1       [39.0, 9.0]
2        [26, 10.5]
3     [37.75, 19.5]
4        [24, 15.0]
5     [20.75, 21.0]
6        [24, 12.0]
7        [24, 12.0]
8      [31.25, 6.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11    [22.75, 12.0]
12     [41.0, 10.5]
13    [22.75, 10.5]
14      [28.0, 9.0]
15    [20.75, 12.0]
16       [24, 10.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1      [15.25, 9.0]
2     [22.75, 12.0]
3        [24, 13.5]
4        [26, 16.5]
5        [26, 19.5]
6      [20.75, 9.0]
7      [42.25, 6.0]
8     [42.25, 12.0]
9     [15.25, 10.5]
10    [22.75, 15.0]
11     [19.5, 21.0]
12      [47.5, 9.0]
13     [44.25, 6.0]
14       [24, 18.0]
15    [37.75, 15.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0      [41.0, 22.5]
1      [15.25, 6.0]
2      [31.25, 6.0]
3      [34.5, 12.0]
4     [37.75, 13.5]
5     [20.75, 12.0]
6     [50.75, 10.5]
7     [22.75, 15.0]
8     [22.75, 12.0]
9      [41.0, 19.5]
10     [41.0, 15.0]
11     [45.5, 10.5]
12     [52.0, 13.5]
13    [20.75, 12.0]
14    [35.75, 13.5]
Name: Coord, dtype: object
0     [45.5, 13.5]
1    [44.25, 19.5]
2    [20.75, 21.0]
3    [22.75, 15.0]
4        [26, 6.0]
5     [32.5, 10.5]
6    [37.75, 21.0]
7     [45.5, 19.5]
8     [19.5, 21.0]
9     [19.5, 16.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [45.5, 13.5]
2      [45.5, 22.5]
3        [24, 13.5]
4      [28.0, 18.0]
5      [47.5, 21.0]
6     [20.75, 13.5]
7         [26, 6.0]
8      [19.5, 21.0]
9     [31.25, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [19.5, 16.5]
2     [20.75, 10.5]
3     [37.75, 13.5]
4     [22.75, 12.0]
5     [44.25, 21.0]
6     [44.25, 12.0]
7     [22.75, 21.0]
8     [15.25, 21.0]
9      [45.5, 10.5]
10    [15.25, 21.0]
11     [19.5, 21.0]
12        [24, 6.0]
13    [20.75, 15.0]
14    [44.25, 10.5]
15    [22.75, 13.5]
Name: Coord, dtype: object
0    [20.75, 16.5]
1     [45.5, 12.0]
2     [45.5, 22.5]
3       [24, 19.5]
4    [22.75, 12.0]
5     [31.25, 6.0]
6    [35.75, 22.5]
7     [19.5, 21.0]
8       [24, 10.5]
9     [41.0, 15.0]
Name: Coord, dtype: object
0       [24, 19.5]
1       [24, 19.5]
2        [24, 6.0]
3        [26, 6.0]
4     [41.0, 10.5]
5       [26, 22.5]
6    [20.75, 21.0]
7     [41.0, 10.5]
8     [50.75, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 6.0]
2        [24, 21.0]
3     [20.75, 10.5]
4      [37.75, 9.0]
5        [24, 19.5]
6      [20.75, 9.0]
7      [41.0, 10.5]
8      [52.0, 13.5]
9        [26, 22.5]
10    [22.75, 21.0]
11    [22.75, 15.0]
12    [15.25, 21.0]
13    [15.25, 21.0]
14       [26, 15.0]
15    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 19.5]
1        [26, 16.5]
2        [24, 19.5]
3      [20.75, 9.0]
4     [48.75, 12.0]
5        [26, 22.5]
6     [29.25, 13.5]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10       [26, 10.5]
11       [24, 10.5]
Name: Coord, dtype: object
0     [31.25, 22.5]
1       [39.0, 9.0]
2     [42.25, 16.5]
3        [24, 19.5]
4     [44.25, 16.5]
5      [34.5, 16.5]
6      [45.5, 15.0]
7        [24, 12.0]
8      [19.5, 21.0]
9      [44.25, 9.0]
10    [37.75, 12.0]
11       [24, 21.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1     [37.75, 13.5]
2     [37.75, 12.0]
3        [24, 19.5]
4     [22.75, 12.0]
5     [44.25, 21.0]
6      [20.75, 9.0]
7      [20.75, 9.0]
8       [34.5, 6.0]
9     [44.25, 22.5]
10       [26, 10.5]
11    [35.75, 10.5]
12    [37.75, 18.0]
13     [19.5, 21.0]
14    [44.25, 22.5]
15    [42.25, 13.5]
Name: Coord, dtype: object
0     [34.5, 12.0]
1     [45.5, 13.5]
2     [44.25, 6.0]
3    [31.25, 12.0]
4    [37.75, 21.0]
5      [47.5, 6.0]
6     [47.5, 16.5]
7     [39.0, 12.0]
8     [41.0, 15.0]
Name: Coord, dtype: object
0       [47.5, 9.0]
1      [42.25, 6.0]
2      [20.75, 9.0]
3      [41.0, 16.5]
4      [32.5, 19.5]
5      [32.5, 12.0]
6     [22.75, 15.0]
7      [20.75, 6.0]
8      [19.5, 21.0]
9      [45.5, 15.0]
10     [41.0, 15.0]
11    [44.25, 10.5]

Name: Coord, dtype: object
0     [41.0, 22.5]
1     [47.5, 21.0]
2     [47.5, 18.0]
3    [44.25, 12.0]
4    [42.25, 12.0]
5    [20.75, 13.5]
6     [19.5, 12.0]
7    [20.75, 18.0]
8     [41.0, 15.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1        [24, 19.5]
2      [42.25, 6.0]
3     [20.75, 12.0]
4        [24, 15.0]
5     [22.75, 15.0]
6        [24, 12.0]
7     [44.25, 22.5]
8         [24, 9.0]
9      [19.5, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12       [26, 18.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [41.0, 10.5]
1      [20.75, 9.0]
2      [47.5, 22.5]
3      [20.75, 9.0]
4     [44.25, 22.5]
5     [22.75, 15.0]
6     [44.25, 22.5]
7     [22.75, 21.0]
8     [35.75, 22.5]
9     [42.25, 15.0]
10     [19.5, 21.0]
11     [19.5, 12.0]
12     [31.25, 6.0]
13     [41.0, 15.0]
14     [45.5, 19.5]
Name: Coord, dtype: object
0     [15.25, 9.0]
1    [20.75, 15.0]
2    [22.75, 10.5]
3     [32.5, 21.0]
4    [22.75, 15.0]
5     [44.25, 9.0]
6     [19.5, 21.0]
7    [37.75, 15.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 13.5]
2      [52.0, 12.0]
3        [26, 10.5]
4     [44.25, 21.0]
5     [31.25, 16.5]
6     [15.25, 12.0]
7     [31.25, 22.5]
8      [19.5, 21.0]
9     [35.75, 12.0]
10    [44.25, 13.5]
11     [45.5, 19.5]
Name: Coord, dtype: object
0    [37.75, 21.0]
1    [37.75, 19.5]
2        [26, 6.0]
3     [32.5, 21.0]
4       [26, 22.5]
5    [20.75, 12.0]
6    [20.75, 12.0]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [28.0, 15.0]
1     [45.5, 13.5]
2    [42.25, 16.5]
3        [24, 6.0]
4    [42.25, 15.0]
5    [22.75, 12.0]
6    [22.75, 12.0]
7    [20.75, 12.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0     [31.25, 12.0]
1     [37.75, 21.0]
2      [20.75, 9.0]
3      [20.75, 9.0]
4     [35.75, 16.5]
5      [41.0, 10.5]
6      [22.75, 6.0]
7      [45.5, 16.5]
8      [34.5, 15.0]
9        [24, 18.0]
10     [52.0, 13.5]
11     [50.75, 9.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 10.5]
1    [22.75, 10.5]
2    [22.75, 15.0]
3     [20.75, 6.0]
4       [26, 19.5]
5        [24, 6.0]
6     [41.0, 10.5]
7     [20.75, 6.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1     [20.75, 15.0]
2      [47.5, 10.5]
3        [24, 19.5]
4        [24, 18.0]
5     [29.25, 10.5]
6     [15.25, 21.0]
7     [22.75, 15.0]
8     [20.75, 18.0]
9      [41.0, 15.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [37.75, 9.0]
2     [37.75, 16.5]
3     [20.75, 13.5]
4      [47.5, 16.5]
5     [15.25, 21.0]
6      [41.0, 10.5]
7     [22.75, 21.0]
8     [15.25, 21.0]
9     [15.25, 21.0]
10     [19.5, 21.0]
11       [26, 22.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [34.5, 12.0]
1       [24, 13.5]
2     [20.75, 9.0]
3       [26, 22.5]
4    [20.75, 21.0]
5     [19.5, 21.0]
6       [24, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1         [24, 6.0]
2       [39.0, 9.0]
3         [24, 6.0]
4         [26, 6.0]
5     [48.75, 12.0]
6     [22.75, 21.0]
7     [15.25, 21.0]
8     [15.25, 21.0]
9        [26, 22.5]
10        [24, 9.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1        [26, 15.0]
2        [24, 13.5]
3      [22.75, 6.0]
4     [20.75, 15.0]
5     [29.25, 13.5]
6        [24, 16.5]
7      [20.75, 9.0]
8     [15.25, 21.0]
9     [22.75, 21.0]
10    [15.25, 21.0]
11    [15.25, 21.0]
12        [24, 9.0]
13       [24, 18.0]
14       [24, 10.5]
Name: Coord, dtype: object
0    [20.75, 18.0]
Name: Coord, dtype: object
0      [32.5, 19.5]
1     [37.75, 13.5]
2      [45.5, 22.5]
3     [22.75, 12.0]
4     [22.75, 12.0]
5      [39.0, 18.0]
6     [35.75, 21.0]
7      [20.75, 9.0]
8         [26, 6.0]
9      [47.5, 22.5]
10       [24, 12.0]
11     [31.25, 6.0]
12     [19.5, 21.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [24, 19.5]
2        [24, 10.5]
3      [45.5, 16.5]
4      [41.0, 10.5]
5      [28.0, 21.0]
6      [28.0, 12.0]
7     [44.25, 10.5]
8     [22.75, 12.0]
9     [20.75, 10.5]
10    [20.75, 10.5]
11     [41.0, 15.0]
12    [20.75, 10.5]
13     [22.75, 6.0]
14     [32.5, 12.0]
Name: Coord, dtype: object
0       [24, 16.5]
1       [26, 10.5]
2     [19.5, 18.0]
3    [20.75, 12.0]
4       [26, 12.0]
5        [24, 9.0]
6        [26, 6.0]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [34.5, 16.5]
1      [39.0, 9.0]
2    [48.75, 12.0]
3    [44.25, 19.5]
4    [37.75, 18.0]
5       [24, 10.5]
6       [26, 13.5]
7     [50.75, 9.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [28.0, 15.0]
1     [29.25, 10.5]
2      [20.75, 9.0]
3        [24, 12.0]
4     [20.75, 12.0]
5         [24, 9.0]
6        [24, 12.0]
7     [37.75, 12.0]
8      [41.0, 10.5]
9        [24, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1     [22.75, 22.5]
2     [20.75, 12.0]
3       [19.5, 9.0]
4         [24, 9.0]
5     [20.75, 13.5]
6        [24, 18.0]
7     [22.75, 12.0]
8        [26, 15.0]
9        [26, 15.0]
10     [50.75, 6.0]
11    [20.75, 12.0]
12    [20.75, 12.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1        [24, 21.0]
2         [26, 6.0]
3      [47.5, 22.5]
4      [28.0, 12.0]
5         [24, 9.0]
6      [41.0, 18.0]
7        [24, 18.0]
8       [39.0, 9.0]
9        [26, 16.5]
10     [41.0, 15.0]
11    [20.75, 16.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [26, 12.0]
2         [24, 6.0]
3      [34.5, 16.5]
4      [47.5, 22.5]
5      [41.0, 10.5]
6     [22.75, 18.0]
7      [20.75, 9.0]
8     [20.75, 10.5]
9        [24, 15.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 16.5]
1    [29.25, 10.5]
2     [41.0, 10.5]
3    [15.25, 12.0]
4        [24, 9.0]
5    [20.75, 18.0]
6       [24, 15.0]
7       [24, 10.5]
8       [24, 21.0]
9    [48.75, 16.5]
Name: Coord, dtype: object
0       [28.0, 6.0]
1      [32.5, 15.0]
2      [41.0, 18.0]
3      [20.75, 6.0]
4        [24, 10.5]
5        [26, 16.5]
6     [22.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9      [41.0, 15.0]
10     [28.0, 16.5]
11       [24, 10.5]
12    [22.75, 21.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1       [34.5, 9.0]
2      [19.5, 13.5]
3      [47.5, 22.5]
4       [32.5, 6.0]
5         [24, 9.0]
6       [19.5, 9.0]
7     [15.25, 10.5]
8      [22.75, 6.0]
9     [37.75, 18.0]
10    [22.75, 12.0]
11    [20.75, 10.5]
12    [22.75, 12.0]
13        [26, 6.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0    [42.25, 18.0]
1    [35.75, 21.0]
2    [20.75, 10.5]
3     [41.0, 16.5]
4    [22.75, 22.5]
5    [42.25, 12.0]
6     [41.0, 15.0]
7       [24, 18.0]
8     [41.0, 13.5]
9    [35.75, 13.5]
Name: Coord, dtype: object
0       [32.5, 9.0]
1     [22.75, 12.0]
2     [44.25, 15.0]
3        [24, 21.0]
4        [24, 13.5]
5     [37.75, 21.0]
6      [41.0, 13.5]
7      [47.5, 22.5]
8     [15.25, 10.5]
9     [22.75, 13.5]
10       [24, 12.0]
11    [35.75, 13.5]
Name: Coord, dtype: object
0        [26, 16.5]
1        [24, 13.5]
2        [24, 19.5]
3     [37.75, 21.0]
4     [44.25, 21.0]
5     [22.75, 13.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12       [24, 21.0]
13     [28.0, 15.0]
Name: Coord, dtype: object
0      [52.0, 13.5]
1     [20.75, 22.5]
2        [26, 10.5]
3         [26, 6.0]
4         [24, 9.0]
5     [22.75, 12.0]
6        [26, 19.5]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 10.5]
10    [20.75, 12.0]
Name: Coord, dtype: object
0    [20.75, 22.5]
1     [15.25, 9.0]
2       [24, 18.0]
3     [20.75, 9.0]
4     [32.5, 21.0]
5    [37.75, 18.0]
6    [22.75, 15.0]
7        [24, 6.0]
8       [24, 21.0]
Name: Coord, dtype: object
0       [28.0, 6.0]
1        [24, 19.5]
2        [24, 12.0]
3         [26, 6.0]
4      [41.0, 13.5]
5         [24, 9.0]
6        [26, 10.5]
7     [20.75, 13.5]
8      [28.0, 10.5]
9     [35.75, 19.5]
10    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 10.5]
1        [24, 13.5]
2     [31.25, 19.5]
3      [28.0, 12.0]
4     [48.75, 16.5]
5      [20.75, 9.0]
6      [20.75, 6.0]
7      [19.5, 21.0]
8     [29.25, 13.5]
9      [31.25, 9.0]
10    [22.75, 13.5]

Name: Coord, dtype: object
0     [37.75, 12.0]
1       [47.5, 6.0]
2      [45.5, 18.0]
3     [48.75, 12.0]
4      [47.5, 22.5]
5     [31.25, 16.5]
6      [20.75, 9.0]
7       [39.0, 9.0]
8     [22.75, 15.0]
9      [19.5, 21.0]
10     [34.5, 12.0]
11     [34.5, 15.0]
12     [31.25, 9.0]
Name: Coord, dtype: object
0     [37.75, 13.5]
1     [22.75, 12.0]
2      [44.25, 6.0]
3     [44.25, 15.0]
4     [22.75, 12.0]
5      [20.75, 9.0]
6      [41.0, 10.5]
7      [20.75, 9.0]
8      [42.25, 9.0]
9      [32.5, 19.5]
10    [22.75, 15.0]
11     [34.5, 13.5]
12    [44.25, 22.5]
13     [19.5, 21.0]
14     [34.5, 21.0]
15    [35.75, 12.0]
16     [47.5, 12.0]
17     [47.5, 16.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [50.75, 9.0]
2      [31.25, 6.0]
3      [20.75, 9.0]
4       [39.0, 9.0]
5      [45.5, 22.5]
6      [19.5, 21.0]
7      [32.5, 19.5]
8        [26, 13.5]
9      [45.5, 22.5]
10       [24, 15.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 21.0]
1    [44.25, 15.0]
2     [47.5, 12.0]
3    [44.25, 21.0]
4     [19.5, 21.0]
5       [26, 19.5]
6       [24, 10.5]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [37.75, 9.0]
1       [24, 19.5]
2       [24, 13.5]
3     [42.25, 6.0]
4       [24, 13.5]
5       [26, 15.0]
6    [20.75, 10.5]
7       [24, 21.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [47.5, 10.5]
1    [20.75, 13.5]
2        [26, 6.0]
3    [20.75, 13.5]
4     [32.5, 18.0]
5     [44.25, 9.0]
6     [20.75, 6.0]
7    [22.75, 10.5]
8        [24, 9.0]
9     [28.0, 16.5]
Name: Coord, dtype: object
0     [44.25, 18.0]
1      [41.0, 18.0]
2     [20.75, 12.0]
3      [42.25, 9.0]
4     [20.75, 10.5]
5       [28.0, 6.0]
6     [22.75, 15.0]
7      [45.5, 10.5]
8     [44.25, 12.0]
9     [22.75, 12.0]
10    [20.75, 10.5]
11     [45.5, 16.5]
12    [20.75, 12.0]
13     [41.0, 15.0]
14     [52.0, 13.5]
15        [24, 9.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0         [24, 6.0]
1     [31.25, 12.0]
2     [35.75, 16.5]
3         [24, 6.0]
4     [44.25, 21.0]
5         [26, 6.0]
6         [24, 9.0]
7        [26, 15.0]
8      [41.0, 10.5]
9     [48.75, 22.5]
10     [41.0, 15.0]
Name: Coord, dtype: object
0         [24, 6.0]
1     [20.75, 12.0]
2      [45.5, 16.5]
3      [34.5, 19.5]
4        [24, 12.0]
5     [22.75, 15.0]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 10.5]
9     [20.75, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12     [41.0, 15.0]
13    [29.25, 18.0]
Name: Coord, dtype: object
0      [42.25, 9.0]
1      [41.0, 13.5]
2      [47.5, 22.5]
3      [41.0, 10.5]
4       [19.5, 9.0]
5     [15.25, 10.5]
6        [24, 18.0]
7        [26, 16.5]
8     [42.25, 15.0]
9        [26, 13.5]
10    [44.25, 12.0]
Name: Coord, dtype: object
0      [41.0, 15.0]
1        [26, 10.5]
2        [24, 16.5]
3       [28.0, 9.0]
4      [45.5, 12.0]
5     [22.75, 19.5]
6         [26, 6.0]
7      [20.75, 6.0]
8      [41.0, 18.0]
9     [29.25, 12.0]
10     [52.0, 13.5]
11    [20.75, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1     [35.75, 21.0]
2        [26, 12.0]
3        [24, 19.5]
4        [26, 12.0]
5        [26, 12.0]
6         [24, 9.0]
7        [24, 18.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10       [24, 18.0]
11     [48.75, 6.0]
Name: Coord, dtype: object
0      [39.0, 9.0]
1       [24, 21.0]
2    [42.25, 12.0]
3     [22.75, 6.0]
4     [28.0, 16.5]
5    [20.75, 10.5]
6        [24, 6.0]
7       [24, 18.0]
8     [50.75, 9.0]
9       [24, 16.5]
Name: Coord, dtype: object
0      [15.25, 6.0]
1     [37.75, 13.5]
2      [45.5, 22.5]
3     [22.75, 12.0]
4     [44.25, 19.5]
5      [19.5, 18.0]
6         [26, 6.0]
7      [47.5, 22.5]
8      [41.0, 10.5]
9     [22.75, 15.0]
10    [22.75, 21.0]
11    [22.75, 12.0]
12    [15.25, 10.5]
13    [44.25, 18.0]
14     [19.5, 21.0]
15     [32.5, 18.0]
16    [35.75, 19.5]
Name: Coord, dtype: object
0        [26, 12.0]
1       [39.0, 9.0]
2         [24, 6.0]
3     [37.75, 21.0]
4      [20.75, 9.0]
5     [44.25, 21.0]
6         [26, 6.0]
7      [32.5, 19.5]
8        [26, 16.5]
9     [20.75, 10.5]
10     [19.5, 21.0]
11      [52.0, 6.0]
12     [28.0, 15.0]
Name: Coord, dtype: object
0     [48.75, 22.5]
1      [44.25, 6.0]
2      [45.5, 19.5]
3        [24, 18.0]
4        [26, 21.0]
5     [44.25, 16.5]
6     [48.75, 21.0]
7      [20.75, 9.0]
8     [20.75, 12.0]
9      [19.5, 21.0]
10    [44.25, 10.5]
11       [26, 15.0]
12       [24, 10.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1     [44.25, 16.5]
2         [26, 6.0]
3     [44.25, 21.0]
4     [42.25, 12.0]
5      [32.5, 21.0]
6      [22.75, 6.0]
7      [19.5, 21.0]
8      [19.5, 12.0]
9      [31.25, 9.0]
10    [50.75, 12.0]
11       [24, 10.5]
12      [34.5, 9.0]
Name: Coord, dtype: object
0      [41.0, 22.5]
1      [47.5, 21.0]
2      [47.5, 12.0]
3       [34.5, 9.0]
4        [26, 16.5]
5      [52.0, 15.0]
6      [20.75, 9.0]
7      [35.75, 9.0]
8     [22.75, 15.0]
9     [44.25, 15.0]
10     [41.0, 15.0]
11    [35.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1      [45.5, 13.5]
2     [37.75, 21.0]
3     [42.25, 15.0]
4      [20.75, 9.0]
5      [41.0, 16.5]
6     [22.75, 13.5]
7       [47.5, 9.0]
8      [32.5, 19.5]
9      [47.5, 18.0]
10     [22.75, 6.0]
11     [28.0, 15.0]
Name: Coord, dtype: object
0     [47.5, 21.0]
1     [20.75, 9.0]
2     [20.75, 9.0]
3     [47.5, 22.5]
4    [42.25, 15.0]
5    [22.75, 12.0]
6     [41.0, 15.0]
7    [22.75, 15.0]
8     [47.5, 16.5]
9     [52.0, 10.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [47.5, 10.5]
2       [47.5, 9.0]
3     [37.75, 21.0]
4     [48.75, 12.0]
5      [20.75, 9.0]
6     [20.75, 10.5]
7      [32.5, 18.0]
8     [22.75, 15.0]
9      [41.0, 18.0]
10    [20.75, 10.5]
11    [20.75, 10.5]
12     [47.5, 15.0]
13    [20.75, 10.5]
Name: Coord, dtype: object
0      [47.5, 10.5]
1      [29.25, 9.0]
2     [22.75, 21.0]
3        [26, 21.0]
4      [20.75, 9.0]
5     [20.75, 22.5]
6         [26, 6.0]
7     [22.75, 21.0]
8        [24, 12.0]
9       [28.0, 9.0]
10    [22.75, 12.0]
11     [47.5, 21.0]
12       [24, 10.5]
Name: Coord, dtype: object
0      [19.5, 18.0]
1        [24, 21.0]
2        [24, 12.0]
3        [24, 19.5]
4     [22.75, 12.0]
5     [37.75, 13.5]
6         [24, 6.0]
7       [28.0, 9.0]
8     [15.25, 10.5]
9     [22.75, 18.0]
10    [22.75, 12.0]
11    [20.75, 10.5]
12        [24, 6.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 19.5]
1     [20.75, 9.0]
2        [26, 6.0]
3    [48.75, 12.0]
4    [22.75, 13.5]
5    [20.75, 10.5]
6     [20.75, 6.0]
7    [20.75, 18.0]
8     [20.75, 6.0]
9     [28.0, 15.0]
Name: Coord, dtype: object
0      [29.25, 9.0]
1     [20.75, 12.0]
2         [26, 6.0]
3      [41.0, 10.5]
4      [42.25, 9.0]
5         [24, 9.0]
6      [45.5, 10.5]
7     [22.75, 15.0]
8     [22.75, 12.0]
9     [22.75, 12.0]
10    [20.75, 12.0]
11     [41.0, 10.5]
12    [20.75, 12.0]
13    [42.25, 13.5]
14    [20.75, 12.0]
15    [22.75, 13.5]
Name: Coord, dtype: object
0      [19.5, 18.0]
1      [41.0, 15.0]
2      [20.75, 9.0]
3       [28.0, 9.0]
4     [15.25, 10.5]
5       [19.5, 9.0]
6     [37.75, 18.0]
7     [22.75, 13.5]
8     [22.75, 15.0]
9     [35.75, 16.5]
10     [28.0, 15.0]
Name: Coord, dtype: object
0      [22.75, 6.0]
1     [20.75, 15.0]
2       [41.0, 9.0]
3        [24, 13.5]
4        [24, 19.5]
5        [26, 16.5]
6        [26, 21.0]
7      [20.75, 9.0]
8     [15.25, 21.0]
9         [24, 9.0]
10    [31.25, 16.5]
11    [31.25, 16.5]
12    [22.75, 15.0]
13    [22.75, 12.0]
14    [20.75, 12.0]
15    [20.75, 12.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0      [41.0, 22.5]
1       [39.0, 9.0]
2     [35.75, 21.0]
3     [37.75, 21.0]
4      [20.75, 9.0]
5     [44.25, 19.5]
6      [20.75, 9.0]
7        [26, 22.5]
8      [20.75, 6.0]
9      [19.5, 21.0]
10      [47.5, 6.0]
11     [28.0, 16.5]
12     [47.5, 19.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1       [41.0, 9.0]
2     [31.25, 22.5]
3       [32.5, 6.0]
4     [35.75, 21.0]
5     [22.75, 19.5]
6     [44.25, 15.0]
7     [22.75, 15.0]
8      [45.5, 22.5]
9     [22.75, 12.0]
10     [34.5, 12.0]
11     [19.5, 21.0]
12    [20.75, 18.0]
13     [50.75, 9.0]
14     [28.0, 16.5]
15      [34.5, 9.0]
Name: Coord, dtype: object
0    [22.75, 16.5]
1       [24, 16.5]
2    [44.25, 22.5]
3    [22.75, 12.0]
4     [47.5, 10.5]
5       [26, 22.5]
6     [19.5, 21.0]
7       [24, 10.5]
8       [24, 21.0]
9        [24, 9.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1      [47.5, 10.5]
2     [42.25, 16.5]
3     [37.75, 21.0]
4     [31.25, 22.5]
5      [47.5, 22.5]
6      [41.0, 10.5]
7      [41.0, 21.0]
8        [26, 15.0]
9      [28.0, 13.5]
10    [22.75, 10.5]
11     [41.0, 10.5]
12     [41.0, 15.0]
13    [20.75, 16.5]
Name: Coord, dtype: object
0      [39.0, 9.0]
1      [19.5, 9.0]
2    [15.25, 10.5]
3    [22.75, 15.0]
4     [34.5, 12.0]
5       [24, 18.0]
6     [19.5, 21.0]
7    [44.25, 22.5]
8      [34.5, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 16.5]
1     [47.5, 10.5]
2       [24, 13.5]
3    [44.25, 21.0]
4    [22.75, 13.5]
5    [42.25, 13.5]
6     [39.0, 12.0]
7     [52.0, 13.5]
8    [37.75, 15.0]
9     [28.0, 15.0]
Name: Coord, dtype: object
0        [26, 16.5]
1        [26, 16.5]
2       [39.0, 9.0]
3     [35.75, 15.0]
4       [52.0, 6.0]
5       [47.5, 9.0]
6     [35.75, 22.5]
7      [19.5, 21.0]
8      [34.5, 15.0]
9      [31.25, 9.0]
10     [28.0, 21.0]
11     [45.5, 15.0]
12    [22.75, 13.5]

Name: Coord, dtype: object
0       [39.0, 9.0]
1      [45.5, 13.5]
2      [45.5, 10.5]
3        [24, 12.0]
4     [20.75, 10.5]
5     [44.25, 16.5]
6      [20.75, 9.0]
7      [47.5, 22.5]
8      [48.75, 6.0]
9     [22.75, 10.5]
10     [20.75, 6.0]
11     [19.5, 21.0]
12       [24, 21.0]
Name: Coord, dtype: object
0     [32.5, 19.5]
1    [35.75, 15.0]
2    [22.75, 12.0]
3        [26, 6.0]
4     [52.0, 10.5]
5     [34.5, 15.0]
6     [45.5, 21.0]
7    [42.25, 13.5]
8     [19.5, 21.0]
9       [24, 18.0]
Name: Coord, dtype: object
0        [24, 13.5]
1     [22.75, 12.0]
2      [45.5, 18.0]
3      [32.5, 15.0]
4       [39.0, 9.0]
5       [47.5, 9.0]
6       [34.5, 9.0]
7      [41.0, 22.5]
8     [15.25, 10.5]
9      [41.0, 12.0]
10    [20.75, 10.5]
11    [20.75, 21.0]
12    [20.75, 10.5]
13     [19.5, 21.0]
14     [20.75, 6.0]
15     [22.75, 6.0]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [37.75, 13.5]
2      [22.75, 9.0]
3     [22.75, 12.0]
4        [24, 19.5]
5     [35.75, 21.0]
6      [20.75, 9.0]
7     [35.75, 10.5]
8      [34.5, 15.0]
9     [35.75, 22.5]
10    [22.75, 15.0]
11     [19.5, 21.0]
12      [34.5, 9.0]
Name: Coord, dtype: object
0         [26, 6.0]
1        [24, 19.5]
2      [45.5, 21.0]
3     [37.75, 21.0]
4     [44.25, 16.5]
5     [22.75, 13.5]
6         [26, 6.0]
7      [45.5, 19.5]
8     [22.75, 15.0]
9      [39.0, 16.5]
10     [41.0, 15.0]
11     [19.5, 21.0]
12       [24, 16.5]
13       [24, 21.0]
Name: Coord, dtype: object
0     [28.0, 15.0]
1    [35.75, 21.0]
2     [19.5, 18.0]
3    [22.75, 10.5]
4       [26, 22.5]
5     [19.5, 21.0]
6       [24, 18.0]
7      [34.5, 9.0]
Name: Coord, dtype: object
0         [24, 6.0]
1      [37.75, 9.0]
2     [31.25, 16.5]
3      [20.75, 9.0]
4      [32.5, 19.5]
5        [26, 18.0]
6         [24, 9.0]
7     [44.25, 22.5]
8     [44.25, 22.5]
9      [19.5, 21.0]
10      [34.5, 9.0]
Name: Coord, dtype: object
0      [15.25, 6.0]
1     [35.75, 18.0]
2      [31.25, 6.0]
3     [35.75, 21.0]
4      [20.75, 9.0]
5      [19.5, 19.5]
6      [20.75, 9.0]
7     [22.75, 18.0]
8     [15.25, 10.5]
9     [15.25, 10.5]
10     [32.5, 12.0]
11     [41.0, 13.5]
12     [45.5, 15.0]
13     [32.5, 18.0]
14     [19.5, 21.0]
15     [34.5, 16.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [20.75, 9.0]
2     [22.75, 21.0]
3     [35.75, 22.5]
4     [20.75, 16.5]
5     [35.75, 10.5]
6     [35.75, 13.5]
7      [19.5, 21.0]
8      [19.5, 13.5]
9     [20.75, 15.0]
10    [35.75, 21.0]
Name: Coord, dtype: object
0     [22.75, 6.0]
1    [20.75, 15.0]
2       [24, 16.5]
3       [26, 15.0]
4    [15.25, 21.0]
5    [20.75, 12.0]
6     [31.25, 6.0]
7     [41.0, 10.5]
8     [41.0, 15.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0     [15.25, 10.5]
1        [24, 19.5]
2     [37.75, 21.0]
3        [24, 12.0]
4     [22.75, 12.0]
5     [37.75, 12.0]
6         [24, 6.0]
7        [26, 13.5]
8      [28.0, 18.0]
9      [52.0, 13.5]
10    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 10.5]
1        [24, 16.5]
2        [24, 13.5]
3     [37.75, 13.5]
4         [24, 6.0]
5        [26, 21.0]
6       [39.0, 9.0]
7      [42.25, 6.0]
8     [22.75, 12.0]
9     [42.25, 12.0]
10        [24, 9.0]
11     [19.5, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 15.0]
1      [47.5, 10.5]
2      [41.0, 16.5]
3     [44.25, 12.0]
4     [37.75, 21.0]
5     [22.75, 15.0]
6     [22.75, 21.0]
7        [26, 15.0]
8      [45.5, 16.5]
9      [47.5, 19.5]
10     [41.0, 18.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1      [15.25, 9.0]
2     [31.25, 10.5]
3      [32.5, 21.0]
4      [41.0, 21.0]
5         [24, 6.0]
6     [44.25, 10.5]
7      [41.0, 15.0]
8        [24, 18.0]
9      [19.5, 12.0]
10     [45.5, 15.0]
Name: Coord, dtype: object
0      [47.5, 10.5]
1     [31.25, 12.0]
2     [31.25, 12.0]
3     [37.75, 21.0]
4        [24, 18.0]
5        [24, 19.5]
6       [41.0, 9.0]
7       [32.5, 9.0]
8      [41.0, 13.5]
9      [47.5, 16.5]
10     [47.5, 10.5]
11     [41.0, 15.0]
Name: Coord, dtype: object
0       [24, 19.5]
1    [22.75, 10.5]
2       [24, 12.0]
3     [47.5, 13.5]
4       [24, 19.5]
5        [26, 6.0]
6       [26, 15.0]
7     [41.0, 10.5]
8       [26, 21.0]
9    [35.75, 13.5]
Name: Coord, dtype: object
0    [35.75, 21.0]
1        [26, 6.0]
2     [32.5, 21.0]
3     [45.5, 10.5]
4     [32.5, 22.5]
5    [29.25, 13.5]
6     [47.5, 10.5]
7     [41.0, 15.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0      [28.0, 12.0]
1      [28.0, 18.0]
2      [20.75, 9.0]
3      [47.5, 15.0]
4        [26, 22.5]
5     [22.75, 18.0]
6     [20.75, 21.0]
7     [22.75, 12.0]
8      [29.25, 6.0]
9        [26, 15.0]
10     [45.5, 18.0]
11     [19.5, 21.0]
12     [39.0, 12.0]
13     [28.0, 15.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1     [42.25, 16.5]
2      [20.75, 9.0]
3      [32.5, 21.0]
4     [29.25, 13.5]
5         [26, 6.0]
6      [39.0, 12.0]
7     [29.25, 13.5]
8      [19.5, 21.0]
9      [20.75, 6.0]
10     [52.0, 13.5]
11    [15.25, 12.0]
Name: Coord, dtype: object
0        [26, 10.5]
1         [24, 9.0]
2        [24, 21.0]
3        [26, 10.5]
4       [39.0, 9.0]
5         [26, 6.0]
6        [24, 15.0]
7         [24, 9.0]
8        [24, 12.0]
9      [20.75, 6.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [31.25, 12.0]
2     [31.25, 13.5]
3      [19.5, 15.0]
4      [34.5, 15.0]
5     [22.75, 12.0]
6     [22.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11     [20.75, 9.0]
12      [52.0, 9.0]
13    [20.75, 21.0]
14    [22.75, 15.0]
15    [15.25, 10.5]
16     [45.5, 16.5]
17     [41.0, 22.5]
18    [20.75, 18.0]
19       [26, 10.5]
20     [15.25, 6.0]
21     [19.5, 16.5]
22     [41.0, 19.5]
23     [32.5, 18.0]
Name: Coord, dtype: object
0        [24, 13.5]
1     [20.75, 22.5]
2        [24, 19.5]
3       [39.0, 9.0]
4      [20.75, 9.0]
5      [20.75, 9.0]
6      [47.5, 10.5]
7      [19.5, 21.0]
8     [29.25, 13.5]
9      [20.75, 6.0]
10       [24, 13.5]
11       [24, 13.5]
Name: Coord, dtype: object
0     [20.75, 9.0]
1    [22.75, 15.0]
2     [39.0, 18.0]
3     [32.5, 18.0]
4     [19.5, 21.0]
5        [24, 6.0]
6     [45.5, 19.5]
7     [45.5, 22.5]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 12.0]
1     [35.75, 21.0]
2      [20.75, 9.0]
3         [26, 6.0]
4      [34.5, 15.0]
5         [24, 9.0]
6     [22.75, 10.5]
7     [22.75, 12.0]
8         [24, 6.0]
9     [31.25, 16.5]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1      [47.5, 10.5]
2        [24, 19.5]
3      [31.25, 6.0]
4         [24, 6.0]
5      [47.5, 10.5]
6      [44.25, 9.0]
7      [45.5, 22.5]
8      [45.5, 16.5]
9      [39.0, 16.5]
10     [45.5, 15.0]
11    [42.25, 10.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1      [19.5, 18.0]
2      [20.75, 9.0]
3      [20.75, 9.0]
4        [26, 22.5]
5        [26, 18.0]
6        [24, 12.0]
7     [20.75, 12.0]
8     [37.75, 15.0]
9     [35.75, 16.5]
10       [24, 18.0]
11     [48.75, 6.0]
12     [28.0, 15.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1     [22.75, 16.5]
2        [24, 13.5]
3      [20.75, 9.0]
4      [41.0, 13.5]
5     [48.75, 12.0]
6       [28.0, 9.0]
7     [20.75, 15.0]
8      [20.75, 9.0]
9     [29.25, 13.5]
10     [45.5, 16.5]
11    [20.75, 12.0]
12     [28.0, 16.5]
13       [24, 10.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [34.5, 12.0]
2      [34.5, 16.5]
3        [24, 19.5]
4      [20.75, 9.0]
5     [48.75, 12.0]
6      [19.5, 21.0]
7     [22.75, 21.0]
8     [15.25, 21.0]
9     [15.25, 21.0]
10    [37.75, 10.5]
11     [32.5, 12.0]
12       [24, 12.0]
13      [34.5, 6.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 12.0]
1     [20.75, 22.5]
2      [22.75, 6.0]
3        [24, 18.0]
4        [26, 13.5]
5     [44.25, 21.0]
6      [19.5, 19.5]
7      [37.75, 6.0]
8     [15.25, 21.0]
9        [26, 16.5]
10    [20.75, 13.5]
11    [22.75, 12.0]
12    [20.75, 12.0]
13    [20.75, 12.0]
14    [20.75, 12.0]
15       [24, 10.5]
16     [20.75, 6.0]
Name: Coord, dtype: object
0       [24, 19.5]
1    [37.75, 21.0]
2      [39.0, 9.0]
3     [20.75, 9.0]
4        [26, 6.0]
5    [37.75, 12.0]
6       [26, 22.5]
7    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1     [37.75, 13.5]
2     [22.75, 12.0]
3      [19.5, 18.0]
4      [32.5, 18.0]
5      [45.5, 12.0]
6        [24, 16.5]
7     [20.75, 10.5]
8     [20.75, 10.5]
9        [26, 18.0]
10     [28.0, 16.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 13.5]
2        [24, 21.0]
3     [37.75, 21.0]
4     [15.25, 12.0]
5        [26, 22.5]
6     [20.75, 12.0]
7     [20.75, 10.5]
8         [24, 6.0]
9      [20.75, 6.0]
10     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 19.5]
1        [24, 18.0]
2     [20.75, 10.5]
3        [26, 10.5]
4        [24, 16.5]
5     [48.75, 12.0]
6        [26, 16.5]
7     [35.75, 13.5]
8      [20.75, 6.0]
9       [19.5, 9.0]
10        [24, 6.0]
11    [22.75, 19.5]

Name: Coord, dtype: object
0       [24, 19.5]
1       [24, 19.5]
2    [44.25, 21.0]
3     [41.0, 10.5]
4       [24, 15.0]
5       [26, 22.5]
6        [24, 9.0]
7    [20.75, 10.5]
8    [22.75, 13.5]
Name: Coord, dtype: object
0    [39.0, 19.5]
1      [24, 21.0]
2      [24, 21.0]
3      [24, 13.5]
4      [24, 19.5]
5    [22.75, 6.0]
6    [41.0, 10.5]
7    [52.0, 13.5]
8      [26, 10.5]
9       [24, 9.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1        [26, 15.0]
2      [20.75, 9.0]
3        [26, 10.5]
4      [20.75, 9.0]
5        [26, 22.5]
6      [19.5, 13.5]
7     [44.25, 22.5]
8     [35.75, 22.5]
9      [35.75, 9.0]
10     [19.5, 21.0]
11    [31.25, 16.5]
12    [50.75, 13.5]
13    [31.25, 21.0]
Name: Coord, dtype: object
0     [31.25, 22.5]
1       [52.0, 6.0]
2      [44.25, 9.0]
3         [24, 6.0]
4      [20.75, 9.0]
5     [35.75, 21.0]
6        [26, 13.5]
7      [47.5, 16.5]
8      [52.0, 13.5]
9     [22.75, 15.0]
10     [19.5, 21.0]
11       [26, 19.5]
12       [26, 15.0]
13    [48.75, 22.5]
14     [45.5, 19.5]
Name: Coord, dtype: object
0    [37.75, 21.0]
1     [41.0, 10.5]
2    [37.75, 12.0]
3    [44.25, 22.5]
4     [32.5, 18.0]
5     [19.5, 21.0]
6    [22.75, 10.5]
7    [44.25, 10.5]
8     [28.0, 15.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [20.75, 22.5]
2     [44.25, 16.5]
3      [48.75, 6.0]
4     [44.25, 21.0]
5      [48.75, 9.0]
6      [31.25, 6.0]
7      [19.5, 21.0]
8      [20.75, 9.0]
9        [24, 18.0]
10    [31.25, 16.5]
11    [15.25, 10.5]
12     [45.5, 21.0]
13     [20.75, 6.0]
14     [19.5, 21.0]
15     [15.25, 6.0]
16     [19.5, 18.0]
17     [32.5, 18.0]
18     [35.75, 9.0]
Name: Coord, dtype: object
0      [52.0, 12.0]
1      [41.0, 22.5]
2      [20.75, 9.0]
3      [41.0, 19.5]
4      [20.75, 9.0]
5      [32.5, 19.5]
6        [26, 18.0]
7     [35.75, 22.5]
8     [22.75, 15.0]
9        [24, 15.0]
10    [15.25, 12.0]
11     [32.5, 22.5]
12       [26, 22.5]
13     [19.5, 21.0]
14        [26, 9.0]
15     [45.5, 18.0]
16    [20.75, 18.0]
17     [42.25, 6.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [47.5, 21.0]
2     [44.25, 22.5]
3     [20.75, 13.5]
4       [32.5, 9.0]
5      [19.5, 19.5]
6      [41.0, 10.5]
7      [20.75, 9.0]
8      [37.75, 6.0]
9     [15.25, 21.0]
10       [26, 10.5]
11     [32.5, 13.5]
12    [20.75, 21.0]
13    [37.75, 16.5]
14     [19.5, 21.0]
15       [26, 15.0]
16    [35.75, 13.5]
17     [22.75, 9.0]
Name: Coord, dtype: object
0     [15.25, 10.5]
1      [20.75, 9.0]
2      [34.5, 15.0]
3     [15.25, 21.0]
4      [19.5, 18.0]
5     [22.75, 21.0]
6      [32.5, 19.5]
7     [22.75, 16.5]
8      [29.25, 6.0]
9     [44.25, 22.5]
10       [26, 22.5]
11     [32.5, 19.5]
12     [19.5, 21.0]
13     [41.0, 15.0]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [32.5, 16.5]
2      [20.75, 9.0]
3     [15.25, 21.0]
4      [41.0, 10.5]
5     [22.75, 21.0]
6      [32.5, 22.5]
7     [22.75, 10.5]
8      [19.5, 16.5]
9      [19.5, 21.0]
10      [52.0, 9.0]
11       [24, 18.0]
12       [24, 10.5]
Name: Coord, dtype: object
0      [34.5, 16.5]
1      [37.75, 9.0]
2        [24, 19.5]
3         [24, 6.0]
4      [20.75, 9.0]
5         [24, 6.0]
6      [34.5, 13.5]
7      [19.5, 21.0]
8        [26, 15.0]
9         [24, 6.0]
10    [44.25, 22.5]
11    [20.75, 12.0]
12        [24, 9.0]
Name: Coord, dtype: object
0        [24, 13.5]
1        [24, 13.5]
2      [41.0, 22.5]
3     [44.25, 16.5]
4        [24, 19.5]
5      [20.75, 9.0]
6      [45.5, 12.0]
7       [52.0, 6.0]
8      [32.5, 12.0]
9      [20.75, 6.0]
10     [19.5, 21.0]
11       [24, 13.5]
12     [28.0, 15.0]
Name: Coord, dtype: object
0       [24, 16.5]
1    [29.25, 10.5]
2       [24, 19.5]
3     [20.75, 9.0]
4     [20.75, 9.0]
5    [44.25, 16.5]
6     [19.5, 21.0]
7     [41.0, 15.0]
8      [34.5, 9.0]
9        [24, 9.0]
Name: Coord, dtype: object
0      [28.0, 15.0]
1        [24, 19.5]
2     [29.25, 10.5]
3     [35.75, 21.0]
4     [15.25, 21.0]
5     [22.75, 21.0]
6     [20.75, 13.5]
7      [19.5, 21.0]
8      [41.0, 15.0]
9      [47.5, 12.0]
10     [45.5, 13.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [44.25, 6.0]
1       [39.0, 9.0]
2     [44.25, 15.0]
3      [28.0, 12.0]
4     [37.75, 15.0]
5      [22.75, 6.0]
6      [19.5, 21.0]
7     [31.25, 16.5]
8     [42.25, 16.5]
9      [47.5, 12.0]
10      [34.5, 9.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [20.75, 6.0]
1       [52.0, 6.0]
2       [28.0, 6.0]
3      [20.75, 9.0]
4     [37.75, 16.5]
5        [26, 22.5]
6        [26, 16.5]
7     [22.75, 15.0]
8      [19.5, 21.0]
9      [52.0, 13.5]
10      [34.5, 9.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [45.5, 12.0]
2      [20.75, 9.0]
3      [45.5, 21.0]
4     [22.75, 18.0]
5        [24, 16.5]
6      [47.5, 22.5]
7      [19.5, 21.0]
8      [34.5, 12.0]
9      [41.0, 10.5]
10      [34.5, 9.0]
11    [20.75, 12.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [37.75, 13.5]
2        [24, 21.0]
3       [28.0, 6.0]
4     [22.75, 12.0]
5     [44.25, 16.5]
6      [41.0, 15.0]
7     [37.75, 21.0]
8      [32.5, 16.5]
9        [26, 22.5]
10    [20.75, 21.0]
11      [32.5, 9.0]
12     [19.5, 21.0]
13     [22.75, 6.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1     [35.75, 18.0]
2      [22.75, 9.0]
3     [35.75, 21.0]
4      [20.75, 9.0]
5      [20.75, 9.0]
6     [37.75, 21.0]
7      [19.5, 19.5]
8     [44.25, 19.5]
9        [26, 22.5]
10    [15.25, 10.5]
11    [35.75, 22.5]
12     [19.5, 21.0]
13       [26, 15.0]
14      [47.5, 9.0]
15     [47.5, 12.0]
Name: Coord, dtype: object
0      [41.0, 22.5]
1       [39.0, 9.0]
2        [24, 19.5]
3     [37.75, 13.5]
4     [22.75, 12.0]
5      [39.0, 18.0]
6      [20.75, 9.0]
7         [26, 6.0]
8     [20.75, 21.0]
9     [22.75, 15.0]
10     [41.0, 13.5]
11     [19.5, 21.0]
12     [47.5, 19.5]
13     [47.5, 10.5]
14    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 18.0]
1     [22.75, 6.0]
2      [28.0, 9.0]
3       [26, 10.5]
4    [37.75, 21.0]
5     [42.25, 9.0]
6     [41.0, 15.0]
7     [19.5, 21.0]
8       [24, 21.0]
Name: Coord, dtype: object
0        [26, 15.0]
1        [24, 16.5]
2      [45.5, 13.5]
3        [24, 19.5]
4        [26, 16.5]
5        [24, 19.5]
6        [24, 18.0]
7      [22.75, 6.0]
8      [34.5, 19.5]
9      [34.5, 12.0]
10     [19.5, 21.0]
11    [22.75, 10.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [48.75, 10.5]
1     [31.25, 21.0]
2     [44.25, 10.5]
3      [32.5, 18.0]
4      [20.75, 9.0]
5     [35.75, 10.5]
6      [20.75, 9.0]
7     [22.75, 15.0]
8     [37.75, 13.5]
9        [24, 19.5]
10    [37.75, 16.5]
11     [34.5, 13.5]
12    [15.25, 10.5]
13     [19.5, 21.0]
14     [15.25, 6.0]
15      [32.5, 6.0]
16    [22.75, 12.0]
17     [32.5, 18.0]
18     [20.75, 6.0]
Name: Coord, dtype: object
0      [41.0, 22.5]
1      [19.5, 18.0]
2     [35.75, 15.0]
3        [24, 19.5]
4      [19.5, 18.0]
5      [20.75, 9.0]
6     [15.25, 10.5]
7        [24, 15.0]
8     [37.75, 13.5]
9     [31.25, 22.5]
10       [24, 16.5]
11     [19.5, 21.0]
Name: Coord, dtype: object
0     [35.75, 18.0]
1     [20.75, 12.0]
2      [45.5, 19.5]
3     [22.75, 15.0]
4      [41.0, 13.5]
5      [41.0, 13.5]
6      [32.5, 22.5]
7      [19.5, 21.0]
8      [45.5, 22.5]
9        [24, 18.0]
10      [32.5, 9.0]
11    [44.25, 22.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0      [45.5, 22.5]
1      [45.5, 18.0]
2      [41.0, 19.5]
3      [44.25, 9.0]
4      [20.75, 9.0]
5      [19.5, 21.0]
6      [41.0, 10.5]
7      [39.0, 10.5]
8      [41.0, 15.0]
9        [24, 10.5]
10    [35.75, 19.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 18.0]
1     [44.25, 10.5]
2      [47.5, 13.5]
3      [20.75, 9.0]
4      [15.25, 6.0]
5     [35.75, 19.5]
6     [31.25, 16.5]
7     [44.25, 19.5]
8      [45.5, 22.5]
9      [19.5, 21.0]
10      [32.5, 6.0]
11      [19.5, 6.0]
12     [34.5, 15.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [39.0, 18.0]
1      [20.75, 9.0]
2        [26, 22.5]
3     [22.75, 15.0]
4        [26, 10.5]
5      [41.0, 21.0]
6      [48.75, 9.0]
7        [26, 22.5]
8      [19.5, 21.0]
9     [44.25, 10.5]
10     [45.5, 22.5]
11     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1       [32.5, 6.0]
2        [26, 21.0]
3        [26, 10.5]
4       [28.0, 9.0]
5     [22.75, 10.5]
6     [20.75, 21.0]
7     [22.75, 15.0]
8       [47.5, 9.0]
9      [19.5, 21.0]
10     [29.25, 6.0]
Name: Coord, dtype: object
0     [44.25, 12.0]
1      [45.5, 10.5]
2        [24, 21.0]
3      [52.0, 10.5]
4      [20.75, 9.0]
5     [29.25, 10.5]
6        [26, 22.5]
7      [45.5, 10.5]
8     [44.25, 22.5]
9      [19.5, 21.0]
10     [35.75, 9.0]
11    [22.75, 15.0]
12    [44.25, 22.5]
13    [22.75, 21.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0       [26, 10.5]
1     [19.5, 18.0]
2     [20.75, 9.0]
3     [50.75, 9.0]
4    [22.75, 18.0]
5     [39.0, 15.0]
6     [19.5, 21.0]
7     [45.5, 15.0]
8      [34.5, 9.0]
9    [48.75, 21.0]
Name: Coord, dtype: object

0      [47.5, 10.5]
1      [15.25, 6.0]
2       [39.0, 9.0]
3      [32.5, 18.0]
4      [22.75, 6.0]
5         [26, 6.0]
6      [34.5, 15.0]
7      [42.25, 9.0]
8     [15.25, 10.5]
9     [22.75, 15.0]
10      [47.5, 9.0]
11     [19.5, 21.0]
12     [32.5, 18.0]
13    [22.75, 10.5]
14     [41.0, 18.0]
Name: Coord, dtype: object
0     [28.0, 15.0]
1     [20.75, 9.0]
2     [44.25, 9.0]
3     [42.25, 9.0]
4       [26, 22.5]
5     [34.5, 15.0]
6     [19.5, 21.0]
7    [50.75, 13.5]
8     [31.25, 9.0]
9    [35.75, 13.5]
Name: Coord, dtype: object
0         [26, 6.0]
1       [52.0, 6.0]
2      [20.75, 9.0]
3     [15.25, 21.0]
4      [41.0, 19.5]
5       [52.0, 9.0]
6     [22.75, 21.0]
7        [26, 22.5]
8     [22.75, 18.0]
9     [42.25, 15.0]
10     [45.5, 10.5]
11     [19.5, 21.0]
12       [24, 16.5]
13       [26, 13.5]
14     [28.0, 16.5]
Name: Coord, dtype: object
0        [24, 13.5]
1     [37.75, 13.5]
2     [20.75, 10.5]
3     [22.75, 12.0]
4         [24, 9.0]
5     [22.75, 12.0]
6     [22.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9         [24, 9.0]
10     [41.0, 15.0]
11     [52.0, 13.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 10.5]
1     [22.75, 16.5]
2     [20.75, 22.5]
3        [24, 21.0]
4       [19.5, 9.0]
5        [26, 10.5]
6     [15.25, 10.5]
7     [22.75, 10.5]
8     [22.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11       [24, 10.5]
12       [24, 21.0]
Name: Coord, dtype: object
0      [45.5, 22.5]
1         [24, 9.0]
2     [42.25, 16.5]
3        [26, 16.5]
4        [26, 15.0]
5      [41.0, 15.0]
6     [15.25, 10.5]
7       [19.5, 9.0]
8      [34.5, 15.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12     [28.0, 16.5]
Name: Coord, dtype: object
0     [42.25, 16.5]
1      [44.25, 6.0]
2        [24, 19.5]
3      [19.5, 18.0]
4     [44.25, 12.0]
5     [44.25, 21.0]
6       [19.5, 9.0]
7     [15.25, 10.5]
8      [44.25, 9.0]
9         [24, 6.0]
10    [22.75, 12.0]
11    [29.25, 12.0]
12     [45.5, 15.0]
Name: Coord, dtype: object
0        [26, 16.5]
1     [20.75, 22.5]
2      [41.0, 10.5]
3        [24, 12.0]
4     [22.75, 13.5]
5     [48.75, 10.5]
6     [22.75, 15.0]
7        [26, 13.5]
8      [41.0, 15.0]
9      [28.0, 16.5]
10      [34.5, 9.0]
Name: Coord, dtype: object
0       [24, 13.5]
1    [44.25, 16.5]
2    [35.75, 21.0]
3     [19.5, 18.0]
4     [32.5, 21.0]
5    [37.75, 18.0]
6     [19.5, 21.0]
7       [26, 15.0]
8     [28.0, 16.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 13.5]
1       [24, 13.5]
2     [34.5, 12.0]
3     [44.25, 9.0]
4    [48.75, 12.0]
5     [20.75, 9.0]
6    [22.75, 13.5]
7     [28.0, 22.5]
8    [20.75, 12.0]
9     [28.0, 15.0]
Name: Coord, dtype: object
0      [50.75, 9.0]
1     [20.75, 22.5]
2        [26, 15.0]
3        [24, 13.5]
4        [24, 13.5]
5     [44.25, 12.0]
6      [42.25, 9.0]
7     [29.25, 13.5]
8         [24, 6.0]
9      [41.0, 10.5]
10    [29.25, 13.5]
11     [41.0, 15.0]
12     [20.75, 6.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 15.0]
1        [24, 21.0]
2       [39.0, 9.0]
3      [19.5, 18.0]
4        [24, 15.0]
5     [22.75, 13.5]
6      [20.75, 6.0]
7     [35.75, 13.5]
8     [22.75, 10.5]
9       [19.5, 9.0]
10     [45.5, 16.5]
11    [20.75, 18.0]
12    [20.75, 10.5]
13     [28.0, 15.0]
Name: Coord, dtype: object
0    [20.75, 10.5]
1    [37.75, 21.0]
2     [52.0, 13.5]
3    [22.75, 12.0]
4    [22.75, 12.0]
5     [41.0, 15.0]
6       [24, 10.5]
7    [20.75, 12.0]
8        [24, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 13.5]
1     [35.75, 18.0]
2     [37.75, 21.0]
3      [20.75, 9.0]
4      [34.5, 16.5]
5     [22.75, 15.0]
6      [20.75, 6.0]
7      [19.5, 21.0]
8       [39.0, 9.0]
9     [20.75, 15.0]
10     [47.5, 12.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [45.5, 22.5]
2     [22.75, 12.0]
3     [22.75, 12.0]
4      [20.75, 9.0]
5        [26, 22.5]
6      [20.75, 6.0]
7      [19.5, 21.0]
8     [22.75, 15.0]
9      [20.75, 6.0]
10    [44.25, 18.0]
11     [34.5, 13.5]
Name: Coord, dtype: object
0     [37.75, 13.5]
1     [22.75, 12.0]
2       [28.0, 9.0]
3      [20.75, 9.0]
4      [34.5, 15.0]
5      [32.5, 21.0]
6     [22.75, 15.0]
7     [42.25, 15.0]
8      [19.5, 21.0]
9     [20.75, 12.0]
10       [26, 15.0]
11     [47.5, 12.0]
Name: Coord, dtype: object
0        [26, 15.0]
1      [45.5, 22.5]
2     [44.25, 22.5]
3     [20.75, 10.5]
4     [22.75, 12.0]
5     [22.75, 12.0]
6     [37.75, 13.5]
7      [20.75, 9.0]
8      [32.5, 21.0]
9        [24, 13.5]
10    [20.75, 12.0]
11     [34.5, 13.5]
12    [20.75, 12.0]
13     [19.5, 21.0]
14    [20.75, 15.0]
15       [26, 10.5]
16       [24, 21.0]
17    [37.75, 15.0]
Name: Coord, dtype: object
0     [45.5, 22.5]
1     [20.75, 9.0]
2    [35.75, 22.5]
3      [32.5, 6.0]
4     [19.5, 21.0]
5    [31.25, 16.5]
6     [41.0, 15.0]
7     [47.5, 12.0]
8     [52.0, 13.5]
Name: Coord, dtype: object
0    [44.25, 16.5]
1     [20.75, 9.0]
2    [42.25, 12.0]
3     [34.5, 22.5]
4    [31.25, 18.0]
5    [31.25, 22.5]
6     [34.5, 12.0]
7     [19.5, 21.0]
8     [19.5, 12.0]
Name: Coord, dtype: object
0       [24, 21.0]
1     [31.25, 6.0]
2     [20.75, 9.0]
3     [52.0, 10.5]
4     [32.5, 10.5]
5    [44.25, 19.5]
6     [20.75, 6.0]
7     [19.5, 21.0]
8     [41.0, 15.0]
9      [34.5, 9.0]
Name: Coord, dtype: object
0    [37.75, 18.0]
1    [42.25, 12.0]
2    [37.75, 21.0]
3     [20.75, 9.0]
4    [42.25, 12.0]
5      [32.5, 6.0]
6     [19.5, 21.0]
7    [35.75, 13.5]
8    [35.75, 19.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [39.0, 9.0]
1     [20.75, 9.0]
2      [52.0, 6.0]
3       [24, 10.5]
4    [22.75, 10.5]
5     [41.0, 10.5]
6       [24, 21.0]
7    [31.25, 21.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 10.5]
1     [22.75, 12.0]
2     [22.75, 21.0]
3      [20.75, 9.0]
4      [41.0, 10.5]
5       [28.0, 9.0]
6       [39.0, 9.0]
7     [15.25, 10.5]
8      [34.5, 12.0]
9      [47.5, 19.5]
10       [24, 10.5]
11     [41.0, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [37.75, 13.5]
2     [22.75, 12.0]
3        [24, 16.5]
4         [26, 6.0]
5      [41.0, 10.5]
6     [31.25, 13.5]
7      [44.25, 9.0]
8     [22.75, 19.5]
9      [45.5, 16.5]
10       [24, 18.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1         [24, 9.0]
2      [19.5, 18.0]
3     [15.25, 10.5]
4       [47.5, 6.0]
5      [32.5, 18.0]
6         [24, 9.0]
7     [31.25, 16.5]
8     [20.75, 13.5]
9      [41.0, 10.5]
10     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 16.5]
1        [24, 12.0]
2     [35.75, 19.5]
3     [22.75, 12.0]
4        [24, 21.0]
5         [24, 9.0]
6     [37.75, 18.0]
7      [20.75, 6.0]
8        [24, 18.0]
9     [22.75, 10.5]
10     [19.5, 21.0]
11        [24, 6.0]
12       [24, 21.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 13.5]
1        [26, 18.0]
2     [22.75, 12.0]
3        [24, 19.5]
4     [22.75, 10.5]
5      [20.75, 9.0]
6     [48.75, 12.0]
7     [15.25, 10.5]
8     [22.75, 15.0]
9      [45.5, 22.5]
10     [47.5, 22.5]
11     [19.5, 21.0]
12     [19.5, 15.0]
Name: Coord, dtype: object
0     [35.75, 21.0]
1        [24, 13.5]
2        [24, 19.5]
3        [24, 10.5]
4      [32.5, 15.0]
5      [20.75, 9.0]
6      [20.75, 9.0]
7         [26, 6.0]
8       [39.0, 9.0]
9      [41.0, 13.5]
10     [52.0, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 19.5]
2       [39.0, 9.0]
3       [39.0, 9.0]
4      [20.75, 9.0]
5      [37.75, 6.0]
6      [39.0, 16.5]
7        [26, 22.5]
8     [22.75, 15.0]
9     [22.75, 18.0]
10     [20.75, 6.0]
11     [42.25, 6.0]
12     [52.0, 13.5]
13     [22.75, 6.0]
Name: Coord, dtype: object
0     [29.25, 13.5]
1       [39.0, 9.0]
2     [22.75, 16.5]
3      [28.0, 12.0]
4      [32.5, 21.0]
5       [19.5, 9.0]
6     [20.75, 18.0]
7     [15.25, 10.5]
8     [22.75, 15.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11    [20.75, 12.0]
12    [20.75, 13.5]
13       [24, 10.5]
14       [24, 13.5]
Name: Coord, dtype: object
0       [32.5, 6.0]
1      [41.0, 22.5]
2      [28.0, 18.0]
3         [24, 6.0]
4      [20.75, 9.0]
5     [31.25, 12.0]
6     [22.75, 15.0]
7     [20.75, 21.0]
8     [20.75, 13.5]
9        [26, 15.0]
10     [41.0, 18.0]
11       [24, 21.0]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [47.5, 10.5]
2        [24, 19.5]
3        [24, 21.0]
4      [20.75, 9.0]
5        [26, 15.0]
6      [47.5, 19.5]
7     [20.75, 13.5]
8         [24, 6.0]
9      [52.0, 12.0]
10       [24, 18.0]
11       [24, 10.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [47.5, 10.5]
2      [19.5, 21.0]
3     [22.75, 21.0]
4     [15.25, 21.0]
5     [15.25, 21.0]
6      [52.0, 13.5]
7     [42.25, 16.5]
8        [24, 12.0]
9      [19.5, 21.0]
10       [26, 21.0]
11     [41.0, 19.5]
12    [20.75, 18.0]
13       [24, 21.0]
14    [37.75, 10.5]
Name: Coord, dtype: object
0        [24, 6.0]
1       [24, 12.0]
2     [22.75, 9.0]
3    [22.75, 18.0]
4     [32.5, 15.0]
5     [19.5, 21.0]
6     [50.75, 9.0]
7    [22.75, 13.5]

Name: Coord, dtype: object
0     [42.25, 12.0]
1       [39.0, 9.0]
2      [41.0, 22.5]
3        [24, 13.5]
4      [34.5, 18.0]
5     [48.75, 12.0]
6        [26, 22.5]
7     [44.25, 22.5]
8       [19.5, 9.0]
9     [15.25, 10.5]
10     [45.5, 15.0]
11       [24, 21.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1     [42.25, 16.5]
2        [24, 18.0]
3         [26, 6.0]
4     [44.25, 19.5]
5      [41.0, 15.0]
6     [20.75, 12.0]
7        [26, 15.0]
8     [44.25, 10.5]
9        [24, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0         [26, 6.0]
1        [24, 13.5]
2         [26, 6.0]
3        [24, 10.5]
4        [26, 21.0]
5     [44.25, 21.0]
6     [29.25, 10.5]
7     [20.75, 12.0]
8       [32.5, 6.0]
9      [47.5, 16.5]
10     [45.5, 21.0]
11    [20.75, 10.5]
12    [20.75, 10.5]
13    [20.75, 10.5]
14     [47.5, 21.0]
15       [24, 16.5]
16     [52.0, 12.0]
17    [35.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 16.5]
1     [48.75, 16.5]
2       [19.5, 6.0]
3     [44.25, 16.5]
4      [22.75, 6.0]
5     [20.75, 13.5]
6        [24, 15.0]
7      [19.5, 15.0]
8      [19.5, 12.0]
9     [37.75, 19.5]
10      [32.5, 9.0]
11    [42.25, 15.0]
12     [19.5, 21.0]
13     [41.0, 10.5]
14     [41.0, 15.0]
Name: Coord, dtype: object
0        [24, 16.5]
1        [24, 15.0]
2        [26, 18.0]
3      [28.0, 16.5]
4       [45.5, 6.0]
5      [47.5, 16.5]
6      [19.5, 21.0]
7      [41.0, 10.5]
8     [42.25, 16.5]
9        [24, 18.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [39.0, 19.5]
1      [45.5, 13.5]
2         [24, 6.0]
3      [20.75, 9.0]
4      [37.75, 6.0]
5     [22.75, 15.0]
6     [44.25, 18.0]
7     [44.25, 10.5]
8        [26, 16.5]
9      [41.0, 18.0]
10     [45.5, 15.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 16.5]
1     [37.75, 13.5]
2        [24, 10.5]
3     [44.25, 18.0]
4      [47.5, 18.0]
5        [24, 19.5]
6     [22.75, 12.0]
7     [44.25, 21.0]
8      [41.0, 13.5]
9       [47.5, 9.0]
10      [47.5, 9.0]
11     [41.0, 15.0]
12    [20.75, 10.5]
13    [22.75, 13.5]
Name: Coord, dtype: object
0    [42.25, 12.0]
1     [37.75, 6.0]
2      [28.0, 6.0]
3    [22.75, 13.5]
4    [22.75, 13.5]
5    [35.75, 10.5]
6     [35.75, 9.0]
7        [24, 6.0]
8     [45.5, 19.5]
9       [26, 15.0]
Name: Coord, dtype: object
0     [29.25, 13.5]
1       [39.0, 9.0]
2     [37.75, 13.5]
3     [22.75, 12.0]
4     [48.75, 12.0]
5         [24, 9.0]
6     [44.25, 10.5]
7     [20.75, 10.5]
8     [20.75, 10.5]
9      [41.0, 15.0]
10     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 19.5]
1      [41.0, 10.5]
2       [39.0, 9.0]
3      [34.5, 12.0]
4     [22.75, 13.5]
5     [44.25, 21.0]
6     [22.75, 15.0]
7      [32.5, 13.5]
8      [32.5, 22.5]
9       [32.5, 9.0]
10     [29.25, 6.0]
11     [52.0, 13.5]
12    [35.75, 19.5]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [15.25, 6.0]
1        [24, 13.5]
2     [44.25, 21.0]
3      [20.75, 9.0]
4      [20.75, 9.0]
5     [15.25, 10.5]
6     [29.25, 13.5]
7      [19.5, 21.0]
8     [22.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11     [32.5, 18.0]
12    [20.75, 12.0]
13      [34.5, 9.0]
14     [52.0, 10.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1     [37.75, 21.0]
2         [26, 6.0]
3        [24, 16.5]
4      [34.5, 15.0]
5         [24, 6.0]
6      [19.5, 21.0]
7        [26, 21.0]
8     [22.75, 10.5]
9      [45.5, 22.5]
10     [52.0, 13.5]
11     [20.75, 6.0]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [24, 19.5]
2        [24, 19.5]
3         [26, 6.0]
4     [20.75, 12.0]
5     [31.25, 12.0]
6       [32.5, 6.0]
7      [45.5, 10.5]
8     [20.75, 16.5]
9      [39.0, 15.0]
10    [22.75, 12.0]
11       [26, 15.0]
12      [28.0, 9.0]
13    [15.25, 12.0]
Name: Coord, dtype: object
0     [20.75, 15.0]
1        [26, 16.5]
2     [22.75, 12.0]
3     [22.75, 12.0]
4     [44.25, 21.0]
5     [35.75, 21.0]
6     [15.25, 21.0]
7     [20.75, 21.0]
8     [15.25, 21.0]
9        [24, 18.0]
10    [37.75, 12.0]
11    [37.75, 12.0]
12        [24, 6.0]
13     [41.0, 10.5]
14     [19.5, 15.0]
15       [24, 21.0]
Name: Coord, dtype: object
0      [47.5, 10.5]
1     [37.75, 13.5]
2        [24, 21.0]
3     [22.75, 12.0]
4        [24, 13.5]
5     [44.25, 10.5]
6      [47.5, 10.5]
7     [22.75, 13.5]
8      [19.5, 21.0]
9       [39.0, 9.0]
10     [22.75, 9.0]
11     [39.0, 16.5]
12     [47.5, 12.0]
13     [45.5, 19.5]
Name: Coord, dtype: object
0      [44.25, 6.0]
1        [24, 12.0]
2     [20.75, 13.5]
3       [32.5, 6.0]
4     [48.75, 16.5]
5      [32.5, 19.5]
6        [26, 12.0]
7      [45.5, 22.5]
8      [34.5, 12.0]
9      [19.5, 21.0]
10     [47.5, 12.0]
Name: Coord, dtype: object
0      [41.0, 22.5]
1      [42.25, 9.0]
2      [34.5, 19.5]
3     [22.75, 15.0]
4      [29.25, 6.0]
5     [35.75, 16.5]
6      [48.75, 9.0]
7     [22.75, 15.0]
8        [24, 18.0]
9      [19.5, 21.0]
10     [34.5, 18.0]
11     [32.5, 22.5]
12     [45.5, 19.5]
13      [47.5, 9.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 13.5]
1     [37.75, 21.0]
2      [34.5, 19.5]
3      [20.75, 9.0]
4     [20.75, 12.0]
5     [48.75, 12.0]
6     [35.75, 13.5]
7     [22.75, 10.5]
8      [19.5, 21.0]
9     [22.75, 12.0]
10     [28.0, 22.5]
11    [20.75, 12.0]
12     [41.0, 15.0]
13       [24, 10.5]
14       [24, 21.0]
15       [24, 13.5]
Name: Coord, dtype: object
0      [19.5, 18.0]
1      [20.75, 9.0]
2     [35.75, 10.5]
3     [22.75, 15.0]
4      [34.5, 16.5]
5      [39.0, 12.0]
6      [41.0, 16.5]
7      [19.5, 21.0]
8         [24, 6.0]
9      [19.5, 15.0]
10    [35.75, 16.5]
Name: Coord, dtype: object
0     [31.25, 10.5]
1      [22.75, 6.0]
2     [31.25, 22.5]
3     [22.75, 13.5]
4     [42.25, 13.5]
5       [52.0, 9.0]
6      [19.5, 21.0]
7     [37.75, 12.0]
8      [39.0, 12.0]
9        [24, 10.5]
10    [35.75, 13.5]
Name: Coord, dtype: object
0     [28.0, 18.0]
1     [47.5, 21.0]
2    [37.75, 13.5]
3    [37.75, 21.0]
4    [31.25, 13.5]
5    [44.25, 22.5]
6     [19.5, 21.0]
7    [31.25, 16.5]
8     [47.5, 12.0]
9     [34.5, 13.5]
Name: Coord, dtype: object
0    [22.75, 10.5]
1     [20.75, 6.0]
2    [20.75, 21.0]
3    [22.75, 12.0]
4    [31.25, 22.5]
5     [19.5, 21.0]
6    [44.25, 10.5]
7    [31.25, 16.5]
Name: Coord, dtype: object
0     [44.25, 22.5]
1     [42.25, 16.5]
2      [32.5, 18.0]
3        [24, 16.5]
4      [20.75, 9.0]
5      [45.5, 18.0]
6      [45.5, 10.5]
7      [31.25, 9.0]
8     [22.75, 12.0]
9      [19.5, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1       [32.5, 9.0]
2       [52.0, 6.0]
3      [41.0, 16.5]
4     [44.25, 16.5]
5      [20.75, 9.0]
6     [37.75, 21.0]
7      [45.5, 21.0]
8     [35.75, 22.5]
9     [48.75, 21.0]
10     [19.5, 21.0]
11     [19.5, 12.0]
12     [47.5, 10.5]
13    [44.25, 16.5]
Name: Coord, dtype: object
0     [31.25, 19.5]
1      [47.5, 18.0]
2       [34.5, 6.0]
3         [24, 6.0]
4     [31.25, 16.5]
5      [39.0, 18.0]
6         [26, 6.0]
7     [22.75, 18.0]
8      [20.75, 9.0]
9     [44.25, 15.0]
10     [20.75, 6.0]
11    [37.75, 10.5]
12     [19.5, 21.0]
13     [45.5, 12.0]
14      [47.5, 9.0]
15    [20.75, 15.0]
Name: Coord, dtype: object
0      [47.5, 18.0]
1      [45.5, 13.5]
2        [24, 19.5]
3      [20.75, 9.0]
4     [44.25, 21.0]
5     [15.25, 21.0]
6      [32.5, 21.0]
7     [22.75, 21.0]
8     [44.25, 22.5]
9      [20.75, 6.0]
10       [26, 16.5]
11      [34.5, 6.0]
12     [19.5, 21.0]
13      [47.5, 6.0]
14     [45.5, 19.5]
15     [45.5, 15.0]
Name: Coord, dtype: object
0      [31.25, 6.0]
1     [44.25, 16.5]
2      [20.75, 9.0]
3     [31.25, 18.0]
4        [26, 15.0]
5        [26, 12.0]
6     [20.75, 18.0]
7        [24, 12.0]
8      [19.5, 21.0]
9       [47.5, 9.0]
10      [47.5, 9.0]
11       [26, 16.5]
Name: Coord, dtype: object
0        [26, 16.5]
1     [22.75, 12.0]
2      [47.5, 22.5]
3     [20.75, 12.0]
4     [20.75, 12.0]
5      [47.5, 10.5]
6      [22.75, 9.0]
7     [20.75, 12.0]
8      [47.5, 12.0]
9       [28.0, 9.0]
10        [24, 9.0]
11     [45.5, 10.5]
12     [31.25, 6.0]
13     [20.75, 9.0]
14    [31.25, 16.5]
15    [15.25, 21.0]
16    [22.75, 21.0]
17     [19.5, 21.0]
18     [45.5, 16.5]
19     [28.0, 18.0]
Name: Coord, dtype: object
0        [24, 16.5]
1      [47.5, 21.0]
2       [47.5, 6.0]
3      [52.0, 12.0]
4       [34.5, 9.0]
5     [37.75, 21.0]
6      [20.75, 9.0]
7     [44.25, 18.0]
8         [24, 9.0]
9     [15.25, 12.0]
10     [41.0, 13.5]
11    [20.75, 18.0]
12     [41.0, 15.0]
13     [22.75, 6.0]
14     [45.5, 15.0]
Name: Coord, dtype: object
0     [47.5, 21.0]
1    [50.75, 12.0]
2     [20.75, 9.0]
3      [32.5, 9.0]
4       [26, 19.5]
5     [41.0, 10.5]
6     [45.5, 15.0]
7     [41.0, 15.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0      [15.25, 6.0]
1      [45.5, 13.5]
2     [35.75, 21.0]
3        [24, 21.0]
4      [28.0, 18.0]
5        [24, 12.0]
6     [37.75, 13.5]
7      [47.5, 21.0]
8      [45.5, 19.5]
9         [26, 6.0]
10     [41.0, 10.5]
11        [24, 9.0]
12       [24, 12.0]
13     [32.5, 10.5]
14    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 10.5]
1     [31.25, 19.5]
2     [44.25, 19.5]
3      [47.5, 18.0]
4     [48.75, 12.0]
5        [24, 16.5]
6      [19.5, 12.0]
7      [19.5, 21.0]
8     [22.75, 10.5]
9     [20.75, 18.0]
10    [35.75, 16.5]
11      [47.5, 6.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1      [47.5, 10.5]
2      [45.5, 15.0]
3      [19.5, 10.5]
4      [28.0, 12.0]
5      [32.5, 21.0]
6        [24, 12.0]
7      [41.0, 13.5]
8        [26, 15.0]
9         [24, 9.0]
10     [41.0, 10.5]
11     [39.0, 13.5]
12    [35.75, 21.0]
Name: Coord, dtype: object
0     [34.5, 12.0]
1     [47.5, 10.5]
2     [41.0, 21.0]
3       [24, 12.0]
4    [37.75, 10.5]
5     [32.5, 10.5]
6     [41.0, 15.0]
7       [24, 10.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1       [52.0, 6.0]
2     [44.25, 15.0]
3     [42.25, 16.5]
4       [28.0, 6.0]
5       [47.5, 9.0]
6      [52.0, 13.5]
7     [42.25, 18.0]
8     [42.25, 15.0]
9      [50.75, 9.0]
10    [22.75, 18.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [47.5, 22.5]
1    [48.75, 12.0]
2     [28.0, 12.0]
3        [24, 9.0]
4     [44.25, 9.0]
5     [45.5, 15.0]
6    [35.75, 12.0]
7    [20.75, 18.0]
8     [41.0, 15.0]
9     [52.0, 13.5]

Name: Coord, dtype: object
0     [42.25, 12.0]
1     [22.75, 12.0]
2     [42.25, 12.0]
3     [15.25, 10.5]
4      [41.0, 15.0]
5       [28.0, 6.0]
6        [26, 19.5]
7      [41.0, 10.5]
8      [41.0, 15.0]
9      [41.0, 19.5]
10    [35.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1     [22.75, 16.5]
2        [24, 12.0]
3      [41.0, 22.5]
4      [20.75, 9.0]
5     [44.25, 15.0]
6      [47.5, 19.5]
7     [44.25, 22.5]
8     [42.25, 13.5]
9     [22.75, 10.5]
10     [39.0, 12.0]
11     [47.5, 18.0]
Name: Coord, dtype: object
0      [45.5, 13.5]
1         [26, 6.0]
2     [42.25, 12.0]
3      [41.0, 13.5]
4     [22.75, 13.5]
5      [32.5, 10.5]
6      [39.0, 12.0]
7     [35.75, 21.0]
8      [47.5, 10.5]
9      [39.0, 12.0]
10      [34.5, 9.0]
11     [45.5, 18.0]
12    [35.75, 13.5]
Name: Coord, dtype: object
0     [15.25, 9.0]
1     [47.5, 10.5]
2     [47.5, 19.5]
3    [35.75, 13.5]
4    [42.25, 18.0]
5     [41.0, 10.5]
6     [41.0, 15.0]
7     [19.5, 19.5]
8    [22.75, 13.5]
Name: Coord, dtype: object
0         [24, 9.0]
1      [34.5, 21.0]
2      [19.5, 18.0]
3      [41.0, 10.5]
4      [45.5, 12.0]
5     [42.25, 16.5]
6      [47.5, 22.5]
7      [41.0, 15.0]
8         [24, 6.0]
9     [20.75, 18.0]
10     [41.0, 15.0]
11       [26, 10.5]
12       [24, 12.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1     [20.75, 10.5]
2      [28.0, 18.0]
3     [42.25, 12.0]
4      [44.25, 9.0]
5      [47.5, 22.5]
6      [41.0, 15.0]
7      [41.0, 15.0]
8      [41.0, 15.0]
9       [32.5, 6.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 10.5]
1     [22.75, 12.0]
2     [37.75, 21.0]
3         [26, 6.0]
4     [15.25, 10.5]
5     [35.75, 22.5]
6      [19.5, 16.5]
7      [19.5, 21.0]
8     [22.75, 12.0]
9     [29.25, 13.5]
10     [47.5, 15.0]
11    [20.75, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 12.0]
1        [24, 13.5]
2        [24, 16.5]
3      [45.5, 19.5]
4     [20.75, 12.0]
5      [52.0, 13.5]
6     [22.75, 13.5]
7     [48.75, 10.5]
8      [19.5, 21.0]
9     [22.75, 12.0]
10    [22.75, 12.0]
11    [20.75, 12.0]
12    [20.75, 12.0]
13     [47.5, 21.0]
14     [19.5, 19.5]
15     [45.5, 15.0]
16      [52.0, 9.0]
Name: Coord, dtype: object
0      [50.75, 9.0]
1        [24, 13.5]
2      [47.5, 10.5]
3     [20.75, 22.5]
4     [37.75, 21.0]
5     [20.75, 13.5]
6     [22.75, 12.0]
7     [22.75, 15.0]
8         [24, 6.0]
9       [47.5, 9.0]
10    [42.25, 16.5]
11       [24, 10.5]
Name: Coord, dtype: object
0    [20.75, 22.5]
1     [15.25, 9.0]
2    [20.75, 16.5]
3     [19.5, 16.5]
Name: Coord, dtype: object
0    [20.75, 22.5]
1     [19.5, 16.5]
2       [24, 19.5]
3    [20.75, 16.5]
4    [20.75, 16.5]
5    [20.75, 21.0]
6    [22.75, 15.0]
7     [19.5, 10.5]
Name: Coord, dtype: object
0        [24, 16.5]
1      [28.0, 18.0]
2         [26, 6.0]
3       [19.5, 6.0]
4     [22.75, 21.0]
5      [32.5, 21.0]
6         [24, 9.0]
7        [24, 21.0]
8        [24, 12.0]
9      [22.75, 6.0]
10    [20.75, 18.0]
11    [20.75, 10.5]
12     [35.75, 9.0]
Name: Coord, dtype: object
0        [24, 16.5]
1     [20.75, 12.0]
2      [34.5, 19.5]
3         [26, 6.0]
4     [37.75, 19.5]
5      [20.75, 9.0]
6      [32.5, 18.0]
7      [45.5, 22.5]
8      [19.5, 21.0]
9     [22.75, 19.5]
10    [44.25, 13.5]
11     [50.75, 9.0]
12    [20.75, 12.0]
13    [20.75, 19.5]
14     [45.5, 15.0]
15    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1     [42.25, 12.0]
2       [41.0, 9.0]
3      [32.5, 15.0]
4     [42.25, 15.0]
5      [41.0, 13.5]
6        [26, 13.5]
7      [47.5, 19.5]
8      [32.5, 18.0]
9      [45.5, 15.0]
10    [42.25, 16.5]
11     [39.0, 13.5]
12    [35.75, 13.5]
Name: Coord, dtype: object
0       [24, 16.5]
1     [47.5, 19.5]
2        [24, 6.0]
3    [50.75, 12.0]
4      [47.5, 6.0]
5    [50.75, 13.5]
6    [22.75, 12.0]
7    [35.75, 12.0]
8       [24, 10.5]
9     [45.5, 15.0]
Name: Coord, dtype: object
0        [24, 6.0]
1     [41.0, 13.5]
2    [35.75, 22.5]
3      [32.5, 9.0]
4     [45.5, 15.0]
5     [41.0, 10.5]
6     [41.0, 15.0]
7    [44.25, 10.5]
8     [52.0, 13.5]
Name: Coord, dtype: object
0    [35.75, 21.0]
1    [44.25, 15.0]
2     [34.5, 12.0]
3     [32.5, 10.5]
4     [45.5, 15.0]
5    [42.25, 18.0]
6      [47.5, 6.0]
7     [41.0, 10.5]
8      [32.5, 6.0]
9     [45.5, 10.5]
Name: Coord, dtype: object
0     [34.5, 12.0]
1     [45.5, 13.5]
2      [32.5, 6.0]
3    [42.25, 15.0]
4      [32.5, 9.0]
5    [44.25, 21.0]
6     [29.25, 6.0]
7     [45.5, 15.0]
8     [41.0, 10.5]
9     [41.0, 15.0]
Name: Coord, dtype: object
0     [44.25, 15.0]
1      [20.75, 9.0]
2     [22.75, 13.5]
3     [20.75, 13.5]
4       [19.5, 9.0]
5         [24, 9.0]
6     [15.25, 10.5]
7         [26, 6.0]
8     [22.75, 10.5]
9        [26, 15.0]
10     [50.75, 9.0]
11     [52.0, 13.5]
12     [50.75, 9.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1     [22.75, 12.0]
2      [32.5, 12.0]
3       [39.0, 9.0]
4      [41.0, 15.0]
5         [26, 6.0]
6     [15.25, 10.5]
7      [41.0, 13.5]
8      [41.0, 15.0]
9      [47.5, 18.0]
10       [24, 16.5]
Name: Coord, dtype: object
0      [47.5, 13.5]
1      [42.25, 6.0]
2     [44.25, 12.0]
3     [20.75, 15.0]
4      [28.0, 12.0]
5        [24, 22.5]
6         [26, 6.0]
7       [47.5, 9.0]
8     [42.25, 16.5]
9      [41.0, 15.0]
10     [19.5, 19.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 15.0]
1       [47.5, 9.0]
2      [48.75, 6.0]
3     [44.25, 18.0]
4      [35.75, 9.0]
5        [24, 15.0]
6      [45.5, 12.0]
7      [41.0, 10.5]
8      [41.0, 18.0]
9      [41.0, 13.5]
10     [45.5, 18.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 21.0]
1      [47.5, 21.0]
2     [37.75, 12.0]
3     [48.75, 10.5]
4        [24, 15.0]
5     [22.75, 13.5]
6      [39.0, 15.0]
7         [24, 6.0]
8      [39.0, 12.0]
9      [19.5, 19.5]
10     [45.5, 15.0]
Name: Coord, dtype: object
0     [41.0, 16.5]
1       [26, 22.5]
2      [19.5, 9.0]
3     [41.0, 15.0]
4    [15.25, 10.5]
5     [44.25, 9.0]
6     [41.0, 13.5]
7     [41.0, 15.0]
8     [39.0, 16.5]
9     [41.0, 15.0]
Name: Coord, dtype: object
0     [47.5, 18.0]
1      [39.0, 9.0]
2    [31.25, 10.5]
3    [44.25, 12.0]
4     [42.25, 9.0]
5     [32.5, 21.0]
6    [20.75, 21.0]
7     [32.5, 22.5]
8     [19.5, 21.0]
9    [44.25, 10.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [44.25, 10.5]
2      [34.5, 12.0]
3     [44.25, 22.5]
4     [31.25, 16.5]
5      [20.75, 9.0]
6       [47.5, 6.0]
7     [22.75, 15.0]
8     [35.75, 13.5]
9     [22.75, 15.0]
10     [41.0, 13.5]
11     [19.5, 21.0]
12     [39.0, 12.0]
Name: Coord, dtype: object
0      [44.25, 6.0]
1      [45.5, 13.5]
2      [39.0, 12.0]
3      [45.5, 22.5]
4     [44.25, 22.5]
5     [15.25, 21.0]
6     [44.25, 21.0]
7      [19.5, 19.5]
8     [31.25, 16.5]
9      [19.5, 21.0]
10       [26, 21.0]
11    [44.25, 13.5]
Name: Coord, dtype: object
0    [44.25, 16.5]
1     [32.5, 15.0]
2    [37.75, 21.0]
3     [32.5, 21.0]
4    [35.75, 22.5]
5    [37.75, 15.0]
6        [24, 9.0]
7    [44.25, 16.5]
8     [19.5, 21.0]
9     [45.5, 19.5]
Name: Coord, dtype: object
0      [34.5, 16.5]
1     [37.75, 13.5]
2     [22.75, 12.0]
3     [31.25, 13.5]
4      [34.5, 15.0]
5      [20.75, 9.0]
6      [34.5, 15.0]
7       [47.5, 6.0]
8      [19.5, 21.0]
9      [41.0, 15.0]
10     [34.5, 15.0]
11       [24, 10.5]
Name: Coord, dtype: object
0     [45.5, 13.5]
1       [24, 19.5]
2       [24, 16.5]
3    [42.25, 12.0]
4    [20.75, 16.5]
5       [26, 15.0]
6    [44.25, 15.0]
7       [24, 18.0]
8      [34.5, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1       [32.5, 6.0]
2      [34.5, 13.5]
3     [44.25, 12.0]
4      [20.75, 9.0]
5      [45.5, 16.5]
6        [24, 18.0]
7        [26, 19.5]
8      [34.5, 10.5]
9        [26, 21.0]
10    [20.75, 12.0]
11     [41.0, 10.5]
12       [24, 21.0]
13        [24, 9.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0      [44.25, 9.0]
1     [37.75, 21.0]
2        [26, 16.5]
3      [32.5, 21.0]
4        [26, 22.5]
5     [22.75, 15.0]
6     [42.25, 13.5]
7      [41.0, 10.5]
8      [48.75, 9.0]
9        [24, 18.0]
10     [39.0, 15.0]
Name: Coord, dtype: object
0    [44.25, 12.0]
1     [47.5, 10.5]
2    [37.75, 13.5]
3    [22.75, 12.0]
4    [37.75, 16.5]
5    [29.25, 10.5]
6    [31.25, 12.0]
7     [41.0, 13.5]
8    [42.25, 16.5]
9      [28.0, 9.0]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [24, 21.0]
2        [24, 19.5]
3      [34.5, 21.0]
4      [20.75, 9.0]
5       [52.0, 9.0]
6      [32.5, 18.0]
7        [26, 15.0]
8        [26, 10.5]
9     [22.75, 12.0]
10     [45.5, 16.5]
11       [26, 13.5]
12    [20.75, 12.0]
13    [20.75, 12.0]
Name: Coord, dtype: object
0     [44.25, 21.0]
1       [28.0, 9.0]
2      [28.0, 16.5]
3         [24, 9.0]
4      [41.0, 15.0]
5     [29.25, 13.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11       [26, 21.0]
12       [24, 21.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [32.5, 6.0]
1        [26, 6.0]
2    [42.25, 15.0]
3    [31.25, 12.0]
4    [20.75, 10.5]
5     [32.5, 12.0]
6       [24, 12.0]
7        [26, 6.0]
8    [20.75, 15.0]
9     [52.0, 13.5]
Name: Coord, dtype: object
0      [28.0, 15.0]
1       [28.0, 6.0]
2     [22.75, 22.5]
3      [20.75, 6.0]
4     [20.75, 10.5]
5         [26, 6.0]
6        [24, 15.0]
7      [42.25, 9.0]
8     [22.75, 15.0]
9        [24, 12.0]
10     [50.75, 9.0]
11     [41.0, 15.0]
12        [24, 9.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0    [44.25, 21.0]
1     [19.5, 13.5]
2     [41.0, 10.5]
3    [22.75, 13.5]
4     [28.0, 16.5]
5        [24, 6.0]
6     [22.75, 6.0]
7       [24, 13.5]

Name: Coord, dtype: object
0       [39.0, 9.0]
1     [44.25, 21.0]
2     [22.75, 21.0]
3      [32.5, 12.0]
4     [15.25, 21.0]
5      [39.0, 12.0]
6      [20.75, 6.0]
7     [37.75, 12.0]
8      [45.5, 16.5]
9     [35.75, 21.0]
10     [20.75, 6.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 9.0]
1       [26, 21.0]
2        [24, 6.0]
3     [41.0, 13.5]
4     [41.0, 15.0]
5    [20.75, 18.0]
6     [50.75, 9.0]
7    [22.75, 19.5]
8       [24, 10.5]
9       [24, 21.0]
Name: Coord, dtype: object
0     [42.25, 12.0]
1     [22.75, 12.0]
2       [32.5, 6.0]
3     [44.25, 21.0]
4     [42.25, 12.0]
5      [32.5, 21.0]
6     [15.25, 10.5]
7     [42.25, 10.5]
8     [42.25, 13.5]
9       [32.5, 6.0]
10     [41.0, 13.5]
11     [41.0, 15.0]
12     [19.5, 12.0]
Name: Coord, dtype: object
0        [24, 9.0]
1    [22.75, 10.5]
2        [24, 9.0]
3       [24, 13.5]
4    [29.25, 13.5]
5       [26, 15.0]
6    [22.75, 10.5]
7     [50.75, 9.0]
8     [52.0, 13.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0    [20.75, 22.5]
1    [37.75, 13.5]
2    [22.75, 12.0]
3    [37.75, 18.0]
4    [22.75, 15.0]
5    [31.25, 10.5]
6        [24, 6.0]
7        [24, 9.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 12.0]
1     [37.75, 13.5]
2        [24, 13.5]
3     [22.75, 12.0]
4      [41.0, 19.5]
5     [42.25, 10.5]
6      [41.0, 19.5]
7      [45.5, 10.5]
8        [24, 18.0]
9     [22.75, 12.0]
10    [42.25, 15.0]
11     [28.0, 22.5]
12    [20.75, 12.0]
13     [41.0, 15.0]
14    [20.75, 12.0]
15    [20.75, 12.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0         [26, 6.0]
1     [22.75, 16.5]
2        [24, 21.0]
3        [24, 13.5]
4        [24, 19.5]
5         [26, 6.0]
6     [22.75, 18.0]
7      [44.25, 9.0]
8      [45.5, 16.5]
9     [20.75, 18.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1        [26, 15.0]
2        [24, 21.0]
3        [26, 16.5]
4        [24, 16.5]
5     [20.75, 22.5]
6      [47.5, 22.5]
7      [32.5, 13.5]
8      [39.0, 15.0]
9     [15.25, 12.0]
10    [20.75, 16.5]
11    [20.75, 10.5]
12     [28.0, 13.5]
13     [28.0, 13.5]
14        [24, 9.0]
15       [24, 21.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1       [39.0, 9.0]
2     [37.75, 16.5]
3      [41.0, 16.5]
4     [22.75, 12.0]
5     [22.75, 12.0]
6     [20.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [22.75, 16.5]
11        [24, 6.0]
12       [24, 19.5]
13    [37.75, 18.0]
14     [19.5, 21.0]
15    [22.75, 13.5]
16     [45.5, 22.5]
17    [20.75, 12.0]
18     [34.5, 12.0]
19    [22.75, 13.5]
Name: Coord, dtype: object
0     [22.75, 16.5]
1      [15.25, 6.0]
2     [20.75, 22.5]
3      [34.5, 16.5]
4      [37.75, 9.0]
5     [35.75, 15.0]
6       [28.0, 9.0]
7      [34.5, 15.0]
8     [15.25, 10.5]
9      [19.5, 21.0]
10     [32.5, 18.0]
11       [24, 12.0]
12       [24, 12.0]
13       [24, 10.5]
14     [22.75, 6.0]
15       [24, 13.5]
Name: Coord, dtype: object
0      [45.5, 19.5]
1      [44.25, 6.0]
2     [22.75, 12.0]
3     [44.25, 16.5]
4     [48.75, 12.0]
5     [37.75, 15.0]
6      [39.0, 15.0]
7      [19.5, 21.0]
8         [24, 6.0]
9      [45.5, 15.0]
10     [19.5, 19.5]
11    [35.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 18.0]
1        [26, 10.5]
2      [20.75, 9.0]
3      [32.5, 22.5]
4      [20.75, 9.0]
5     [35.75, 13.5]
6     [35.75, 22.5]
7     [44.25, 22.5]
8     [42.25, 12.0]
9      [19.5, 21.0]
10    [20.75, 10.5]
11     [28.0, 13.5]
12    [35.75, 21.0]
13    [22.75, 18.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1      [34.5, 16.5]
2     [35.75, 13.5]
3     [44.25, 16.5]
4     [35.75, 16.5]
5      [37.75, 6.0]
6      [32.5, 21.0]
7         [24, 9.0]
8       [47.5, 9.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11     [41.0, 10.5]
12     [28.0, 10.5]
13    [20.75, 12.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1      [44.25, 6.0]
2     [37.75, 12.0]
3     [20.75, 10.5]
4     [37.75, 21.0]
5      [42.25, 9.0]
6         [24, 9.0]
7      [19.5, 21.0]
8      [31.25, 9.0]
9     [20.75, 12.0]
10    [22.75, 12.0]
11       [24, 21.0]
Name: Coord, dtype: object
0     [20.75, 12.0]
1      [41.0, 16.5]
2     [20.75, 12.0]
3      [44.25, 9.0]
4      [39.0, 10.5]
5     [22.75, 15.0]
6     [20.75, 18.0]
7      [19.5, 21.0]
8     [22.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11       [26, 16.5]
12    [22.75, 15.0]
13    [42.25, 10.5]
14     [22.75, 6.0]
Name: Coord, dtype: object
0      [42.25, 9.0]
1     [20.75, 10.5]
2      [32.5, 22.5]
3     [22.75, 15.0]
4       [19.5, 9.0]
5     [15.25, 10.5]
6       [32.5, 9.0]
7        [26, 15.0]
8      [39.0, 12.0]
9      [50.75, 9.0]
10     [41.0, 15.0]
11     [28.0, 10.5]
12     [28.0, 15.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1         [24, 9.0]
2     [44.25, 19.5]
3      [45.5, 19.5]
4     [48.75, 12.0]
5      [34.5, 13.5]
6     [22.75, 18.0]
7      [47.5, 10.5]
8      [19.5, 21.0]
9      [31.25, 9.0]
10       [26, 12.0]
Name: Coord, dtype: object
0      [32.5, 19.5]
1     [44.25, 21.0]
2     [22.75, 13.5]
3      [19.5, 18.0]
4       [19.5, 9.0]
5     [22.75, 15.0]
6     [15.25, 10.5]
7      [45.5, 10.5]
8     [42.25, 10.5]
9      [52.0, 13.5]
10       [24, 13.5]
Name: Coord, dtype: object
0    [37.75, 13.5]
1       [24, 13.5]
2    [22.75, 12.0]
3        [24, 9.0]
4       [26, 10.5]
5    [20.75, 18.0]
6     [41.0, 13.5]
7     [19.5, 21.0]
8        [24, 6.0]
9     [50.75, 9.0]
Name: Coord, dtype: object
0     [37.75, 21.0]
1     [20.75, 12.0]
2     [44.25, 22.5]
3        [24, 13.5]
4        [26, 16.5]
5     [44.25, 10.5]
6     [44.25, 21.0]
7      [34.5, 10.5]
8       [39.0, 9.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11    [22.75, 12.0]
12        [24, 9.0]
13    [20.75, 12.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [47.5, 10.5]
1     [32.5, 18.0]
2     [47.5, 13.5]
3     [32.5, 19.5]
4       [26, 22.5]
5     [20.75, 6.0]
6     [19.5, 21.0]
7    [35.75, 12.0]
8     [22.75, 6.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 16.5]
2      [34.5, 15.0]
3      [47.5, 16.5]
4     [35.75, 12.0]
5      [45.5, 10.5]
6      [45.5, 10.5]
7      [32.5, 22.5]
8      [19.5, 21.0]
9      [35.75, 9.0]
10    [22.75, 21.0]
11    [48.75, 16.5]
Name: Coord, dtype: object
0      [32.5, 19.5]
1       [39.0, 9.0]
2      [28.0, 18.0]
3      [31.25, 9.0]
4     [22.75, 16.5]
5        [26, 18.0]
6        [24, 12.0]
7        [24, 12.0]
8     [44.25, 13.5]
9     [20.75, 16.5]
10     [47.5, 22.5]
11     [19.5, 21.0]
12     [39.0, 16.5]
13     [28.0, 21.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0      [45.5, 10.5]
1       [39.0, 9.0]
2     [22.75, 15.0]
3       [41.0, 9.0]
4     [22.75, 12.0]
5      [19.5, 21.0]
6     [20.75, 12.0]
7     [20.75, 12.0]
8      [34.5, 15.0]
9      [47.5, 12.0]
10    [22.75, 19.5]
11      [52.0, 6.0]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 9.0]
2     [31.25, 21.0]
3        [26, 13.5]
4      [44.25, 9.0]
5     [31.25, 21.0]
6      [20.75, 9.0]
7      [39.0, 15.0]
8      [45.5, 10.5]
9       [47.5, 6.0]
10      [47.5, 9.0]
11     [32.5, 19.5]
12       [24, 16.5]
13       [24, 16.5]
14     [19.5, 21.0]
15      [39.0, 9.0]
16    [48.75, 19.5]
17    [48.75, 21.0]
18     [19.5, 18.0]
19      [47.5, 9.0]
Name: Coord, dtype: object
0      [15.25, 6.0]
1      [37.75, 6.0]
2     [37.75, 13.5]
3        [24, 21.0]
4     [22.75, 12.0]
5     [48.75, 12.0]
6     [15.25, 21.0]
7     [22.75, 21.0]
8     [44.25, 12.0]
9     [15.25, 10.5]
10     [32.5, 18.0]
11     [19.5, 21.0]
12       [24, 13.5]
Name: Coord, dtype: object
0     [48.75, 10.5]
1      [42.25, 9.0]
2     [22.75, 12.0]
3      [20.75, 9.0]
4     [35.75, 13.5]
5     [22.75, 15.0]
6      [41.0, 13.5]
7      [19.5, 21.0]
8      [45.5, 22.5]
9     [44.25, 10.5]
10     [52.0, 12.0]
11       [24, 21.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1       [47.5, 6.0]
2      [32.5, 18.0]
3      [45.5, 19.5]
4      [22.75, 6.0]
5     [44.25, 21.0]
6     [22.75, 13.5]
7        [24, 12.0]
8        [24, 12.0]
9      [44.25, 9.0]
10     [19.5, 21.0]
11    [37.75, 10.5]
12    [35.75, 19.5]
Name: Coord, dtype: object
0       [24, 19.5]
1    [44.25, 10.5]
2     [32.5, 21.0]
3      [34.5, 6.0]
4     [45.5, 10.5]
5    [35.75, 22.5]
6      [47.5, 9.0]
7     [19.5, 21.0]
8     [44.25, 9.0]
9    [44.25, 22.5]
Name: Coord, dtype: object
0       [26, 10.5]
1    [48.75, 12.0]
2    [22.75, 13.5]
3        [26, 6.0]
4     [32.5, 19.5]
5     [39.0, 19.5]
6      [47.5, 9.0]
7     [19.5, 21.0]
8       [24, 10.5]
9    [35.75, 21.0]
Name: Coord, dtype: object
0      [39.0, 18.0]
1      [45.5, 12.0]
2      [32.5, 19.5]
3     [35.75, 13.5]
4        [26, 22.5]
5       [32.5, 6.0]
6     [35.75, 10.5]
7     [44.25, 18.0]
8      [19.5, 21.0]
9     [31.25, 10.5]
10     [34.5, 22.5]
Name: Coord, dtype: object
0     [34.5, 21.0]
1     [34.5, 15.0]
2     [20.75, 9.0]
3     [32.5, 19.5]
4    [22.75, 15.0]
5    [35.75, 22.5]
6     [45.5, 19.5]
7      [47.5, 9.0]
8     [19.5, 21.0]
9    [20.75, 18.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1     [29.25, 13.5]
2     [22.75, 22.5]
3      [32.5, 18.0]
4     [35.75, 21.0]
5     [48.75, 12.0]
6      [41.0, 21.0]
7     [22.75, 15.0]
8         [26, 6.0]
9      [45.5, 12.0]
10    [20.75, 10.5]
11       [24, 21.0]
12     [47.5, 21.0]
Name: Coord, dtype: object
0       [24, 19.5]
1     [22.75, 6.0]
2     [20.75, 9.0]
3       [26, 22.5]
4     [19.5, 21.0]
5        [24, 6.0]
6       [26, 13.5]
7    [44.25, 22.5]
Name: Coord, dtype: object
0      [44.25, 9.0]
1      [47.5, 18.0]
2     [35.75, 21.0]
3      [19.5, 18.0]
4     [37.75, 16.5]
5      [20.75, 9.0]
6     [31.25, 12.0]
7     [22.75, 15.0]
8      [19.5, 21.0]
9      [28.0, 22.5]
10     [50.75, 9.0]
Name: Coord, dtype: object
0        [24, 21.0]
1        [26, 19.5]
2     [37.75, 13.5]
3     [42.25, 10.5]
4      [34.5, 15.0]
5        [26, 22.5]
6        [26, 19.5]
7      [32.5, 12.0]
8     [44.25, 10.5]
9      [20.75, 6.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [47.5, 10.5]
1       [24, 19.5]
2     [20.75, 9.0]
3    [44.25, 21.0]
4      [39.0, 9.0]
5     [29.25, 6.0]
6       [24, 18.0]
7    [37.75, 18.0]
8     [28.0, 16.5]
9    [31.25, 22.5]
Name: Coord, dtype: object
0         [26, 6.0]
1      [34.5, 12.0]
2      [41.0, 15.0]
3     [37.75, 13.5]
4        [24, 19.5]
5     [44.25, 10.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [37.75, 21.0]
9     [15.25, 21.0]
10    [22.75, 21.0]
11     [19.5, 21.0]
12       [26, 13.5]
13       [24, 18.0]
14     [39.0, 15.0]
15     [19.5, 15.0]
16    [37.75, 10.5]
Name: Coord, dtype: object
0      [37.75, 6.0]
1        [24, 19.5]
2     [37.75, 13.5]
3        [24, 19.5]
4     [22.75, 12.0]
5     [44.25, 10.5]
6     [22.75, 13.5]
7      [50.75, 6.0]
8     [44.25, 21.0]
9      [35.75, 9.0]
10    [31.25, 13.5]
11        [24, 9.0]
12       [24, 21.0]
13       [24, 13.5]
Name: Coord, dtype: object
0     [20.75, 9.0]
1     [32.5, 18.0]
2       [26, 18.0]
3    [20.75, 21.0]
4     [19.5, 21.0]
5    [22.75, 10.5]
6       [26, 15.0]
7       [26, 13.5]
8     [41.0, 15.0]
9     [28.0, 16.5]
Name: Coord, dtype: object

0     [20.75, 22.5]
1     [44.25, 10.5]
2      [22.75, 6.0]
3     [44.25, 21.0]
4      [32.5, 15.0]
5      [45.5, 22.5]
6        [24, 12.0]
7      [41.0, 13.5]
8       [32.5, 6.0]
9      [19.5, 12.0]
10    [42.25, 10.5]
11     [45.5, 15.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 15.0]
1    [22.75, 12.0]
2     [52.0, 15.0]
3    [48.75, 12.0]
4     [45.5, 18.0]
5    [31.25, 21.0]
6    [22.75, 15.0]
7     [19.5, 21.0]
8     [41.0, 15.0]
9    [42.25, 15.0]
Name: Coord, dtype: object
0      [28.0, 12.0]
1      [20.75, 9.0]
2      [32.5, 12.0]
3        [26, 22.5]
4        [24, 13.5]
5     [42.25, 15.0]
6         [26, 6.0]
7      [45.5, 15.0]
8      [47.5, 13.5]
9     [35.75, 12.0]
10     [45.5, 21.0]
11        [24, 9.0]
Name: Coord, dtype: object
0     [22.75, 21.0]
1        [24, 19.5]
2        [26, 21.0]
3         [24, 6.0]
4       [28.0, 9.0]
5     [29.25, 10.5]
6     [44.25, 21.0]
7       [39.0, 9.0]
8     [44.25, 10.5]
9      [19.5, 21.0]
10     [45.5, 16.5]
11    [22.75, 13.5]
Name: Coord, dtype: object
0     [35.75, 18.0]
1      [41.0, 22.5]
2      [45.5, 22.5]
3      [19.5, 19.5]
4     [22.75, 15.0]
5     [15.25, 10.5]
6     [37.75, 15.0]
7     [37.75, 16.5]
8     [44.25, 13.5]
9      [19.5, 21.0]
10      [32.5, 6.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0      [47.5, 10.5]
1      [32.5, 18.0]
2         [24, 6.0]
3     [44.25, 16.5]
4     [31.25, 16.5]
5      [20.75, 9.0]
6      [20.75, 9.0]
7     [42.25, 15.0]
8      [19.5, 21.0]
9        [26, 21.0]
10     [34.5, 18.0]
11       [24, 12.0]
12     [19.5, 19.5]
13     [45.5, 10.5]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [34.5, 12.0]
1    [37.75, 21.0]
2    [22.75, 12.0]
3     [47.5, 10.5]
4     [19.5, 21.0]
Name: Coord, dtype: object
0     [37.75, 21.0]
1        [26, 22.5]
2     [29.25, 13.5]
3     [29.25, 13.5]
4     [37.75, 21.0]
5      [20.75, 9.0]
6     [22.75, 15.0]
7     [42.25, 13.5]
8      [41.0, 15.0]
9      [34.5, 16.5]
10        [26, 9.0]
11     [44.25, 9.0]
12     [19.5, 21.0]
13    [20.75, 18.0]
14     [41.0, 15.0]
15     [28.0, 18.0]
16     [41.0, 12.0]
17     [47.5, 16.5]
18    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [34.5, 12.0]
2      [28.0, 18.0]
3      [32.5, 15.0]
4      [20.75, 9.0]
5     [48.75, 12.0]
6      [41.0, 10.5]
7        [26, 22.5]
8      [45.5, 10.5]
9      [32.5, 18.0]
10     [19.5, 21.0]
11    [22.75, 10.5]
12       [24, 10.5]
13     [22.75, 6.0]
14     [28.0, 15.0]
Name: Coord, dtype: object
0     [20.75, 9.0]
1     [34.5, 15.0]
2     [20.75, 9.0]
3    [22.75, 15.0]
4       [24, 15.0]
5     [19.5, 21.0]
6     [28.0, 21.0]
Name: Coord, dtype: object
0        [24, 18.0]
1     [35.75, 21.0]
2      [20.75, 9.0]
3     [31.25, 16.5]
4        [24, 16.5]
5     [44.25, 19.5]
6        [26, 19.5]
7      [19.5, 21.0]
8     [44.25, 15.0]
9      [39.0, 12.0]
10     [47.5, 18.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1        [24, 13.5]
2     [42.25, 12.0]
3     [44.25, 16.5]
4      [20.75, 9.0]
5      [20.75, 9.0]
6      [34.5, 13.5]
7     [35.75, 10.5]
8      [41.0, 13.5]
9      [19.5, 21.0]
10    [35.75, 12.0]
11     [45.5, 13.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [22.75, 12.0]
2      [42.25, 9.0]
3      [34.5, 21.0]
4      [20.75, 9.0]
5     [15.25, 10.5]
6     [22.75, 15.0]
7     [20.75, 21.0]
8      [45.5, 22.5]
9      [19.5, 21.0]
10        [24, 6.0]
11     [41.0, 15.0]
12     [45.5, 15.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1      [52.0, 12.0]
2     [37.75, 13.5]
3      [20.75, 9.0]
4         [24, 9.0]
5     [20.75, 13.5]
6      [20.75, 9.0]
7        [26, 22.5]
8     [22.75, 15.0]
9     [37.75, 19.5]
10     [19.5, 21.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1      [47.5, 10.5]
2        [24, 10.5]
3      [20.75, 9.0]
4     [37.75, 12.0]
5      [48.75, 9.0]
6     [22.75, 21.0]
7     [15.25, 21.0]
8     [15.25, 21.0]
9     [22.75, 15.0]
10     [32.5, 22.5]
11    [42.25, 10.5]
12     [47.5, 10.5]
13       [24, 10.5]
Name: Coord, dtype: object
0     [22.75, 21.0]
1        [26, 10.5]
2     [20.75, 22.5]
3      [47.5, 21.0]
4     [44.25, 15.0]
5      [52.0, 13.5]
6      [41.0, 15.0]
7     [44.25, 12.0]
8      [32.5, 10.5]
9     [44.25, 12.0]
10    [42.25, 18.0]
11    [42.25, 16.5]
12       [24, 10.5]
13     [20.75, 6.0]
14       [24, 10.5]
15     [45.5, 15.0]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [47.5, 10.5]
2      [28.0, 18.0]
3      [44.25, 9.0]
4      [20.75, 9.0]
5     [48.75, 12.0]
6     [22.75, 21.0]
7        [26, 22.5]
8     [22.75, 15.0]
9     [15.25, 21.0]
10    [15.25, 21.0]
11    [44.25, 13.5]
12     [39.0, 12.0]
13     [41.0, 18.0]
14       [24, 18.0]
Name: Coord, dtype: object
0     [41.0, 16.5]
1       [24, 21.0]
2        [26, 6.0]
3       [26, 22.5]
4       [26, 15.0]
5     [41.0, 10.5]
6    [42.25, 16.5]
7     [41.0, 18.0]
8       [24, 10.5]
9     [50.75, 9.0]
Name: Coord, dtype: object
0     [20.75, 22.5]
1      [47.5, 10.5]
2      [41.0, 15.0]
3     [35.75, 21.0]
4     [15.25, 21.0]
5     [22.75, 21.0]
6     [20.75, 12.0]
7       [32.5, 9.0]
8       [28.0, 9.0]
9      [41.0, 15.0]
10        [24, 6.0]
11       [24, 12.0]
12    [35.75, 19.5]
13       [24, 10.5]
Name: Coord, dtype: object
0      [45.5, 13.5]
1     [31.25, 12.0]
2      [41.0, 13.5]
3       [32.5, 6.0]
4        [26, 22.5]
5        [24, 13.5]
6         [24, 9.0]
7      [41.0, 16.5]
8      [41.0, 15.0]
9        [26, 22.5]
10       [24, 10.5]
11       [24, 10.5]
Name: Coord, dtype: object
0     [37.75, 21.0]
1     [35.75, 21.0]
2      [20.75, 9.0]
3      [34.5, 18.0]
4     [22.75, 18.0]
5         [24, 9.0]
6     [48.75, 10.5]
7        [24, 16.5]
8      [19.5, 16.5]
9     [22.75, 10.5]
10     [41.0, 15.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [34.5, 9.0]
1      [20.75, 9.0]
2       [52.0, 6.0]
3        [26, 22.5]
4      [32.5, 21.0]
5       [28.0, 6.0]
6     [22.75, 12.0]
7      [41.0, 10.5]
8      [28.0, 21.0]
9         [26, 6.0]
10     [45.5, 15.0]
11     [28.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1        [24, 16.5]
2        [24, 13.5]
3     [29.25, 13.5]
4     [37.75, 21.0]
5      [20.75, 9.0]
6      [34.5, 15.0]
7        [26, 22.5]
8         [24, 9.0]
9      [31.25, 6.0]
10     [32.5, 18.0]
11     [41.0, 16.5]
12    [22.75, 19.5]
13       [26, 15.0]
Name: Coord, dtype: object
0     [42.25, 18.0]
1      [28.0, 18.0]
2      [47.5, 19.5]
3      [20.75, 9.0]
4        [26, 22.5]
5     [22.75, 15.0]
6       [19.5, 9.0]
7     [15.25, 10.5]
8        [24, 12.0]
9      [41.0, 13.5]
10     [28.0, 16.5]
11     [41.0, 15.0]
12    [31.25, 12.0]
Name: Coord, dtype: object
0     [47.5, 12.0]
1     [32.5, 22.5]
2     [45.5, 22.5]
3       [26, 19.5]
4    [44.25, 21.0]
5     [32.5, 19.5]
6       [24, 10.5]
7     [32.5, 22.5]
8    [44.25, 15.0]
9     [41.0, 18.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [47.5, 10.5]
2        [24, 21.0]
3        [24, 19.5]
4      [47.5, 13.5]
5      [45.5, 15.0]
6        [26, 16.5]
7      [20.75, 6.0]
8     [20.75, 21.0]
9         [24, 6.0]
10     [22.75, 6.0]
Name: Coord, dtype: object
0      [47.5, 21.0]
1       [39.0, 9.0]
2        [24, 13.5]
3        [24, 21.0]
4      [45.5, 13.5]
5        [24, 19.5]
6     [48.75, 13.5]
7      [20.75, 9.0]
8     [44.25, 12.0]
9      [41.0, 10.5]
10    [42.25, 15.0]
11       [24, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1      [34.5, 12.0]
2      [41.0, 10.5]
3      [34.5, 16.5]
4      [41.0, 10.5]
5        [26, 22.5]
6     [22.75, 18.0]
7     [31.25, 16.5]
8     [31.25, 16.5]
9      [28.0, 13.5]
10       [26, 13.5]
11       [26, 19.5]
12    [20.75, 10.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [47.5, 21.0]
2     [35.75, 21.0]
3      [28.0, 18.0]
4     [44.25, 21.0]
5     [22.75, 21.0]
6      [39.0, 19.5]
7     [20.75, 16.5]
8      [47.5, 22.5]
9     [20.75, 18.0]
10     [41.0, 15.0]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 6.0]
2     [20.75, 22.5]
3      [28.0, 18.0]
4      [42.25, 9.0]
5      [47.5, 21.0]
6      [20.75, 9.0]
7     [44.25, 21.0]
8      [19.5, 19.5]
9      [37.75, 6.0]
10    [15.25, 21.0]
11     [41.0, 13.5]
12        [26, 9.0]
13    [44.25, 10.5]
14     [47.5, 21.0]
15    [20.75, 16.5]
16    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 16.5]
1        [24, 21.0]
2        [24, 19.5]
3      [20.75, 9.0]
4      [48.75, 6.0]
5         [24, 9.0]
6      [20.75, 6.0]
7      [41.0, 13.5]
8      [34.5, 12.0]
9     [22.75, 12.0]
10    [22.75, 12.0]
11     [19.5, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 15.0]
1     [45.5, 22.5]
2     [45.5, 22.5]
3     [32.5, 21.0]
4    [44.25, 21.0]
5     [19.5, 21.0]
6       [24, 13.5]
7     [22.75, 6.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 19.5]
1        [24, 15.0]
2     [44.25, 21.0]
3      [20.75, 9.0]
4        [24, 16.5]
5      [41.0, 13.5]
6        [24, 12.0]
7     [20.75, 12.0]
8        [24, 16.5]
9      [41.0, 15.0]
10       [24, 18.0]
11     [52.0, 13.5]
12    [35.75, 19.5]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 16.5]
1      [47.5, 21.0]
2      [45.5, 13.5]
3     [44.25, 10.5]
4      [34.5, 12.0]
5      [22.75, 6.0]
6      [20.75, 6.0]
7     [29.25, 13.5]
8         [26, 6.0]
9        [24, 12.0]
10     [19.5, 21.0]
11     [20.75, 6.0]
12     [28.0, 22.5]
13       [24, 10.5]
Name: Coord, dtype: object
0        [26, 15.0]
1      [45.5, 13.5]
2     [44.25, 19.5]
3     [31.25, 22.5]
4     [22.75, 16.5]
5      [20.75, 9.0]
6     [22.75, 10.5]
7        [26, 18.0]
8      [41.0, 12.0]
9      [19.5, 21.0]
10     [44.25, 9.0]
11     [34.5, 12.0]
12    [42.25, 15.0]
13     [47.5, 21.0]
14       [24, 16.5]
Name: Coord, dtype: object
0      [39.0, 18.0]
1       [39.0, 9.0]
2        [26, 10.5]
3     [37.75, 19.5]
4        [24, 15.0]
5     [20.75, 21.0]
6        [24, 12.0]
7        [24, 12.0]
8      [31.25, 6.0]
9      [19.5, 21.0]
10    [22.75, 12.0]
11    [22.75, 12.0]
12     [41.0, 10.5]
13    [22.75, 10.5]
14      [28.0, 9.0]
15    [20.75, 12.0]
16       [24, 10.5]

Name: Coord, dtype: object
0     [42.25, 12.0]
1      [15.25, 9.0]
2     [22.75, 12.0]
3        [24, 13.5]
4        [26, 16.5]
5        [26, 19.5]
6      [20.75, 9.0]
7      [42.25, 6.0]
8     [42.25, 12.0]
9     [15.25, 10.5]
10    [22.75, 15.0]
11     [19.5, 21.0]
12      [47.5, 9.0]
13     [44.25, 6.0]
14       [24, 18.0]
15    [37.75, 15.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0      [41.0, 22.5]
1      [15.25, 6.0]
2      [31.25, 6.0]
3      [34.5, 12.0]
4     [37.75, 13.5]
5     [20.75, 12.0]
6     [50.75, 10.5]
7     [22.75, 15.0]
8     [22.75, 12.0]
9      [41.0, 19.5]
10     [41.0, 15.0]
11     [45.5, 10.5]
12     [52.0, 13.5]
13    [20.75, 12.0]
14    [35.75, 13.5]
Name: Coord, dtype: object
0     [45.5, 13.5]
1    [44.25, 19.5]
2    [20.75, 21.0]
3    [22.75, 15.0]
4        [26, 6.0]
5     [32.5, 10.5]
6    [37.75, 21.0]
7     [45.5, 19.5]
8     [19.5, 21.0]
9     [19.5, 16.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1      [45.5, 13.5]
2      [45.5, 22.5]
3        [24, 13.5]
4      [28.0, 18.0]
5      [47.5, 21.0]
6     [20.75, 13.5]
7         [26, 6.0]
8      [19.5, 21.0]
9     [31.25, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [19.5, 16.5]
2     [20.75, 10.5]
3     [37.75, 13.5]
4     [22.75, 12.0]
5     [44.25, 21.0]
6     [44.25, 12.0]
7     [22.75, 21.0]
8     [15.25, 21.0]
9      [45.5, 10.5]
10    [15.25, 21.0]
11     [19.5, 21.0]
12        [24, 6.0]
13    [20.75, 15.0]
14    [44.25, 10.5]
15    [22.75, 13.5]
Name: Coord, dtype: object
0    [20.75, 16.5]
1     [45.5, 12.0]
2     [45.5, 22.5]
3       [24, 19.5]
4    [22.75, 12.0]
5     [31.25, 6.0]
6    [35.75, 22.5]
7     [19.5, 21.0]
8       [24, 10.5]
9     [41.0, 15.0]
Name: Coord, dtype: object
0       [24, 19.5]
1       [24, 19.5]
2        [24, 6.0]
3        [26, 6.0]
4     [41.0, 10.5]
5       [26, 22.5]
6    [20.75, 21.0]
7     [41.0, 10.5]
8     [50.75, 9.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [22.75, 6.0]
2        [24, 21.0]
3     [20.75, 10.5]
4      [37.75, 9.0]
5        [24, 19.5]
6      [20.75, 9.0]
7      [41.0, 10.5]
8      [52.0, 13.5]
9        [26, 22.5]
10    [22.75, 21.0]
11    [22.75, 15.0]
12    [15.25, 21.0]
13    [15.25, 21.0]
14       [26, 15.0]
15    [22.75, 13.5]
Name: Coord, dtype: object
0        [24, 19.5]
1        [26, 16.5]
2        [24, 19.5]
3      [20.75, 9.0]
4     [48.75, 12.0]
5        [26, 22.5]
6     [29.25, 13.5]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10       [26, 10.5]
11       [24, 10.5]
Name: Coord, dtype: object
0     [31.25, 22.5]
1       [39.0, 9.0]
2     [42.25, 16.5]
3        [24, 19.5]
4     [44.25, 16.5]
5      [34.5, 16.5]
6      [45.5, 15.0]
7        [24, 12.0]
8      [19.5, 21.0]
9      [44.25, 9.0]
10    [37.75, 12.0]
11       [24, 21.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1     [37.75, 13.5]
2     [37.75, 12.0]
3        [24, 19.5]
4     [22.75, 12.0]
5     [44.25, 21.0]
6      [20.75, 9.0]
7      [20.75, 9.0]
8       [34.5, 6.0]
9     [44.25, 22.5]
10       [26, 10.5]
11    [35.75, 10.5]
12    [37.75, 18.0]
13     [19.5, 21.0]
14    [44.25, 22.5]
15    [42.25, 13.5]
Name: Coord, dtype: object
0     [34.5, 12.0]
1     [45.5, 13.5]
2     [44.25, 6.0]
3    [31.25, 12.0]
4    [37.75, 21.0]
5      [47.5, 6.0]
6     [47.5, 16.5]
7     [39.0, 12.0]
8     [41.0, 15.0]
Name: Coord, dtype: object
0       [47.5, 9.0]
1      [42.25, 6.0]
2      [20.75, 9.0]
3      [41.0, 16.5]
4      [32.5, 19.5]
5      [32.5, 12.0]
6     [22.75, 15.0]
7      [20.75, 6.0]
8      [19.5, 21.0]
9      [45.5, 15.0]
10     [41.0, 15.0]
11    [44.25, 10.5]
Name: Coord, dtype: object
0     [41.0, 22.5]
1     [47.5, 21.0]
2     [47.5, 18.0]
3    [44.25, 12.0]
4    [42.25, 12.0]
5    [20.75, 13.5]
6     [19.5, 12.0]
7    [20.75, 18.0]
8     [41.0, 15.0]
9    [22.75, 13.5]
Name: Coord, dtype: object
0     [42.25, 12.0]
1        [24, 19.5]
2      [42.25, 6.0]
3     [20.75, 12.0]
4        [24, 15.0]
5     [22.75, 15.0]
6        [24, 12.0]
7     [44.25, 22.5]
8         [24, 9.0]
9      [19.5, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12       [26, 18.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0      [41.0, 10.5]
1      [20.75, 9.0]
2      [47.5, 22.5]
3      [20.75, 9.0]
4     [44.25, 22.5]
5     [22.75, 15.0]
6     [44.25, 22.5]
7     [22.75, 21.0]
8     [35.75, 22.5]
9     [42.25, 15.0]
10     [19.5, 21.0]
11     [19.5, 12.0]
12     [31.25, 6.0]
13     [41.0, 15.0]
14     [45.5, 19.5]
Name: Coord, dtype: object
0     [15.25, 9.0]
1    [20.75, 15.0]
2    [22.75, 10.5]
3     [32.5, 21.0]
4    [22.75, 15.0]
5     [44.25, 9.0]
6     [19.5, 21.0]
7    [37.75, 15.0]
Name: Coord, dtype: object
0      [34.5, 12.0]
1        [24, 13.5]
2      [52.0, 12.0]
3        [26, 10.5]
4     [44.25, 21.0]
5     [31.25, 16.5]
6     [15.25, 12.0]
7     [31.25, 22.5]
8      [19.5, 21.0]
9     [35.75, 12.0]
10    [44.25, 13.5]
11     [45.5, 19.5]
Name: Coord, dtype: object
0    [37.75, 21.0]
1    [37.75, 19.5]
2        [26, 6.0]
3     [32.5, 21.0]
4       [26, 22.5]
5    [20.75, 12.0]
6    [20.75, 12.0]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [28.0, 15.0]
1     [45.5, 13.5]
2    [42.25, 16.5]
3        [24, 6.0]
4    [42.25, 15.0]
5    [22.75, 12.0]
6    [22.75, 12.0]
7    [20.75, 12.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0     [31.25, 12.0]
1     [37.75, 21.0]
2      [20.75, 9.0]
3      [20.75, 9.0]
4     [35.75, 16.5]
5      [41.0, 10.5]
6      [22.75, 6.0]
7      [45.5, 16.5]
8      [34.5, 15.0]
9        [24, 18.0]
10     [52.0, 13.5]
11     [50.75, 9.0]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [41.0, 10.5]
1    [22.75, 10.5]
2    [22.75, 15.0]
3     [20.75, 6.0]
4       [26, 19.5]
5        [24, 6.0]
6     [41.0, 10.5]
7     [20.75, 6.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1     [20.75, 15.0]
2      [47.5, 10.5]
3        [24, 19.5]
4        [24, 18.0]
5     [29.25, 10.5]
6     [15.25, 21.0]
7     [22.75, 15.0]
8     [20.75, 18.0]
9      [41.0, 15.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1      [37.75, 9.0]
2     [37.75, 16.5]
3     [20.75, 13.5]
4      [47.5, 16.5]
5     [15.25, 21.0]
6      [41.0, 10.5]
7     [22.75, 21.0]
8     [15.25, 21.0]
9     [15.25, 21.0]
10     [19.5, 21.0]
11       [26, 22.5]
12    [22.75, 13.5]
Name: Coord, dtype: object
0     [34.5, 12.0]
1       [24, 13.5]
2     [20.75, 9.0]
3       [26, 22.5]
4    [20.75, 21.0]
5     [19.5, 21.0]
6       [24, 13.5]
Name: Coord, dtype: object
0      [22.75, 6.0]
1         [24, 6.0]
2       [39.0, 9.0]
3         [24, 6.0]
4         [26, 6.0]
5     [48.75, 12.0]
6     [22.75, 21.0]
7     [15.25, 21.0]
8     [15.25, 21.0]
9        [26, 22.5]
10        [24, 9.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [39.0, 9.0]
1        [26, 15.0]
2        [24, 13.5]
3      [22.75, 6.0]
4     [20.75, 15.0]
5     [29.25, 13.5]
6        [24, 16.5]
7      [20.75, 9.0]
8     [15.25, 21.0]
9     [22.75, 21.0]
10    [15.25, 21.0]
11    [15.25, 21.0]
12        [24, 9.0]
13       [24, 18.0]
14       [24, 10.5]
Name: Coord, dtype: object
0    [20.75, 18.0]
Name: Coord, dtype: object
0      [32.5, 19.5]
1     [37.75, 13.5]
2      [45.5, 22.5]
3     [22.75, 12.0]
4     [22.75, 12.0]
5      [39.0, 18.0]
6     [35.75, 21.0]
7      [20.75, 9.0]
8         [26, 6.0]
9      [47.5, 22.5]
10       [24, 12.0]
11     [31.25, 6.0]
12     [19.5, 21.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [24, 19.5]
2        [24, 10.5]
3      [45.5, 16.5]
4      [41.0, 10.5]
5      [28.0, 21.0]
6      [28.0, 12.0]
7     [44.25, 10.5]
8     [22.75, 12.0]
9     [20.75, 10.5]
10    [20.75, 10.5]
11     [41.0, 15.0]
12    [20.75, 10.5]
13     [22.75, 6.0]
14     [32.5, 12.0]
Name: Coord, dtype: object
0       [24, 16.5]
1       [26, 10.5]
2     [19.5, 18.0]
3    [20.75, 12.0]
4       [26, 12.0]
5        [24, 9.0]
6        [26, 6.0]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [34.5, 16.5]
1      [39.0, 9.0]
2    [48.75, 12.0]
3    [44.25, 19.5]
4    [37.75, 18.0]
5       [24, 10.5]
6       [26, 13.5]
7     [50.75, 9.0]
8       [24, 10.5]
9    [22.75, 13.5]
Name: Coord, dtype: object
0      [28.0, 15.0]
1     [29.25, 10.5]
2      [20.75, 9.0]
3        [24, 12.0]
4     [20.75, 12.0]
5         [24, 9.0]
6        [24, 12.0]
7     [37.75, 12.0]
8      [41.0, 10.5]
9        [24, 21.0]
10    [22.75, 13.5]
Name: Coord, dtype: object

0        [24, 16.5]
1     [22.75, 22.5]
2     [20.75, 12.0]
3       [19.5, 9.0]
4         [24, 9.0]
5     [20.75, 13.5]
6        [24, 18.0]
7     [22.75, 12.0]
8        [26, 15.0]
9        [26, 15.0]
10     [50.75, 6.0]
11    [20.75, 12.0]
12    [20.75, 12.0]
13    [22.75, 13.5]
Name: Coord, dtype: object
0     [44.25, 12.0]
1        [24, 21.0]
2         [26, 6.0]
3      [47.5, 22.5]
4      [28.0, 12.0]
5         [24, 9.0]
6      [41.0, 18.0]
7        [24, 18.0]
8       [39.0, 9.0]
9        [26, 16.5]
10     [41.0, 15.0]
11    [20.75, 16.5]
Name: Coord, dtype: object
0     [20.75, 22.5]
1        [26, 12.0]
2         [24, 6.0]
3      [34.5, 16.5]
4      [47.5, 22.5]
5      [41.0, 10.5]
6     [22.75, 18.0]
7      [20.75, 9.0]
8     [20.75, 10.5]
9        [24, 15.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 16.5]
1    [29.25, 10.5]
2     [41.0, 10.5]
3    [15.25, 12.0]
4        [24, 9.0]
5    [20.75, 18.0]
6       [24, 15.0]
7       [24, 10.5]
8       [24, 21.0]
9    [48.75, 16.5]
Name: Coord, dtype: object
0       [28.0, 6.0]
1      [32.5, 15.0]
2      [41.0, 18.0]
3      [20.75, 6.0]
4        [24, 10.5]
5        [26, 16.5]
6     [22.75, 12.0]
7     [20.75, 12.0]
8     [20.75, 12.0]
9      [41.0, 15.0]
10     [28.0, 16.5]
11       [24, 10.5]
12    [22.75, 21.0]
Name: Coord, dtype: object
0       [39.0, 9.0]
1       [34.5, 9.0]
2      [19.5, 13.5]
3      [47.5, 22.5]
4       [32.5, 6.0]
5         [24, 9.0]
6       [19.5, 9.0]
7     [15.25, 10.5]
8      [22.75, 6.0]
9     [37.75, 18.0]
10    [22.75, 12.0]
11    [20.75, 10.5]
12    [22.75, 12.0]
13        [26, 6.0]
14    [22.75, 13.5]
Name: Coord, dtype: object
0    [42.25, 18.0]
1    [35.75, 21.0]
2    [20.75, 10.5]
3     [41.0, 16.5]
4    [22.75, 22.5]
5    [42.25, 12.0]
6     [41.0, 15.0]
7       [24, 18.0]
8     [41.0, 13.5]
9    [35.75, 13.5]
Name: Coord, dtype: object
0       [32.5, 9.0]
1     [22.75, 12.0]
2     [44.25, 15.0]
3        [24, 21.0]
4        [24, 13.5]
5     [37.75, 21.0]
6      [41.0, 13.5]
7      [47.5, 22.5]
8     [15.25, 10.5]
9     [22.75, 13.5]
10       [24, 12.0]
11    [35.75, 13.5]
Name: Coord, dtype: object
0        [26, 16.5]
1        [24, 13.5]
2        [24, 19.5]
3     [37.75, 21.0]
4     [44.25, 21.0]
5     [22.75, 13.5]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12       [24, 21.0]
13     [28.0, 15.0]
Name: Coord, dtype: object
0      [52.0, 13.5]
1     [20.75, 22.5]
2        [26, 10.5]
3         [26, 6.0]
4         [24, 9.0]
5     [22.75, 12.0]
6        [26, 19.5]
7     [22.75, 12.0]
8     [20.75, 12.0]
9     [20.75, 10.5]
10    [20.75, 12.0]
Name: Coord, dtype: object
0    [20.75, 22.5]
1     [15.25, 9.0]
2       [24, 18.0]
3     [20.75, 9.0]
4     [32.5, 21.0]
5    [37.75, 18.0]
6    [22.75, 15.0]
7        [24, 6.0]
8       [24, 21.0]
Name: Coord, dtype: object
0       [28.0, 6.0]
1        [24, 19.5]
2        [24, 12.0]
3         [26, 6.0]
4      [41.0, 13.5]
5         [24, 9.0]
6        [26, 10.5]
7     [20.75, 13.5]
8      [28.0, 10.5]
9     [35.75, 19.5]
10    [22.75, 13.5]
Name: Coord, dtype: object
0        [26, 10.5]
1        [24, 13.5]
2     [31.25, 19.5]
3      [28.0, 12.0]
4     [48.75, 16.5]
5      [20.75, 9.0]
6      [20.75, 6.0]
7      [19.5, 21.0]
8     [29.25, 13.5]
9      [31.25, 9.0]
10    [22.75, 13.5]
Name: Coord, dtype: object
0     [37.75, 12.0]
1       [47.5, 6.0]
2      [45.5, 18.0]
3     [48.75, 12.0]
4      [47.5, 22.5]
5     [31.25, 16.5]
6      [20.75, 9.0]
7       [39.0, 9.0]
8     [22.75, 15.0]
9      [19.5, 21.0]
10     [34.5, 12.0]
11     [34.5, 15.0]
12     [31.25, 9.0]
Name: Coord, dtype: object
0     [37.75, 13.5]
1     [22.75, 12.0]
2      [44.25, 6.0]
3     [44.25, 15.0]
4     [22.75, 12.0]
5      [20.75, 9.0]
6      [41.0, 10.5]
7      [20.75, 9.0]
8      [42.25, 9.0]
9      [32.5, 19.5]
10    [22.75, 15.0]
11     [34.5, 13.5]
12    [44.25, 22.5]
13     [19.5, 21.0]
14     [34.5, 21.0]
15    [35.75, 12.0]
16     [47.5, 12.0]
17     [47.5, 16.5]
Name: Coord, dtype: object
0        [24, 13.5]
1      [50.75, 9.0]
2      [31.25, 6.0]
3      [20.75, 9.0]
4       [39.0, 9.0]
5      [45.5, 22.5]
6      [19.5, 21.0]
7      [32.5, 19.5]
8        [26, 13.5]
9      [45.5, 22.5]
10       [24, 15.0]
11    [22.75, 13.5]
Name: Coord, dtype: object
0       [24, 21.0]
1    [44.25, 15.0]
2     [47.5, 12.0]
3    [44.25, 21.0]
4     [19.5, 21.0]
5       [26, 19.5]
6       [24, 10.5]
7    [22.75, 13.5]
Name: Coord, dtype: object
0     [37.75, 9.0]
1       [24, 19.5]
2       [24, 13.5]
3     [42.25, 6.0]
4       [24, 13.5]
5       [26, 15.0]
6    [20.75, 10.5]
7       [24, 21.0]
8    [22.75, 13.5]
Name: Coord, dtype: object
0     [47.5, 10.5]
1    [20.75, 13.5]
2        [26, 6.0]
3    [20.75, 13.5]
4     [32.5, 18.0]
5     [44.25, 9.0]
6     [20.75, 6.0]
7    [22.75, 10.5]
8        [24, 9.0]
9     [28.0, 16.5]
Name: Coord, dtype: object
0     [44.25, 18.0]
1      [41.0, 18.0]
2     [20.75, 12.0]
3      [42.25, 9.0]
4     [20.75, 10.5]
5       [28.0, 6.0]
6     [22.75, 15.0]
7      [45.5, 10.5]
8     [44.25, 12.0]
9     [22.75, 12.0]
10    [20.75, 10.5]
11     [45.5, 16.5]
12    [20.75, 12.0]
13     [41.0, 15.0]
14     [52.0, 13.5]
15        [24, 9.0]
16    [22.75, 13.5]
Name: Coord, dtype: object
0         [24, 6.0]
1     [31.25, 12.0]
2     [35.75, 16.5]
3         [24, 6.0]
4     [44.25, 21.0]
5         [26, 6.0]
6         [24, 9.0]
7        [26, 15.0]
8      [41.0, 10.5]
9     [48.75, 22.5]
10     [41.0, 15.0]
Name: Coord, dtype: object
0         [24, 6.0]
1     [20.75, 12.0]
2      [45.5, 16.5]
3      [34.5, 19.5]
4        [24, 12.0]
5     [22.75, 15.0]
6     [22.75, 12.0]
7     [22.75, 12.0]
8     [20.75, 10.5]
9     [20.75, 12.0]
10    [20.75, 12.0]
11    [20.75, 12.0]
12     [41.0, 15.0]
13    [29.25, 18.0]
Name: Coord, dtype: object
0      [42.25, 9.0]
1      [41.0, 13.5]
2      [47.5, 22.5]
3      [41.0, 10.5]
4       [19.5, 9.0]
5     [15.25, 10.5]
6        [24, 18.0]
7        [26, 16.5]
8     [42.25, 15.0]
9        [26, 13.5]
10    [44.25, 12.0]
Name: Coord, dtype: object
0      [41.0, 15.0]
1        [26, 10.5]
2        [24, 16.5]
3       [28.0, 9.0]
4      [45.5, 12.0]
5     [22.75, 19.5]
6         [26, 6.0]
7      [20.75, 6.0]
8      [41.0, 18.0]
9     [29.25, 12.0]
10     [52.0, 13.5]
11    [20.75, 12.0]
12    [22.75, 13.5]
Name: Coord, dtype: object

In [261]:
dist_per_sku = {}
for k,v in sku_dist.items():
    dist_per_sku[k] = sum(v) / len(v)
    
# print(dist_per_sku)
max_sku,min_sku = max(dist_per_sku, key=dist_per_sku.get),min(dist_per_sku, key=dist_per_sku.get)
max_dist,min_dist = max(dist_per_sku.values()),min(dist_per_sku.values())
print(f"max_dist,min_dist: {max_dist},{min_dist}")

max_dist,min_dist: 183.0,28.0

## Group order lines by 1 hour pick times, with N max order lines per group/so long as can fit on pallet

## Constraints
2. Size of SKU_size * pieces for each orderlines in the invoice(s) should fit on w * l pallet/trolley
3. A single route fulfils ALL orderlines within the group



### Current assumptions
1. User can pick unlimited pieces of each SKU in the group (i.e. no piece limit, all same size)
2. A warehouse workflow that orders are being delivered out throughout the day (e.g. certain ecommerce sub-operations)
3. Order fulilment times assumed the time to be delivered out so that drivers can successfully deliver goods on time

In [102]:
N = 10

# Group orders by spatial closeness of majority of goods

## Constraints
1. A group consists of integer number of invoices
2. Size of SKU_size * pieces for each orderlines in the invoice(s) should fit on w * l pallet/trolley
3. A single route fulfils ALL orderlines within the invoice(s) in the group

## Assumption
1. A picking flow where everything is packed in the day, only to be delivered the following morning. Hence all invoices share the same "order fulfilment"

## Compare to
1. Group orders by First Come First Serve (i.e. batch orders based on as-is order in system)
2. 

# WHAT NOT TO DO
1. No condensing the closest point of centroid. It's fake haha

## Future considerations
2. Priority tags
3. Installments

In [119]:
def filter_by_date(df,date):
    return df[df['DATE'] == date]

unique_dates = df['DATE'].unique()
for u_d in unique_dates:
    this_df = filter_by_date(df,u_d)
    print(this_df.head(10))

   Unnamed: 0  S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
0           0    0  12/11/2018      3780678  399573    1       399573
1           1    1  12/11/2018      3780650  340308    1       340308
2           2    2  12/11/2018      3780649  399573    1       399573
3           3    3  12/11/2018      3780645  442025    1       442025
4           4    4  12/11/2018      3780638  436455    1       436455
5           5    5  12/11/2018      3780641  403849    1       403849
6           6    6  12/11/2018      3780633  439405    1       439405
7           7    7  12/11/2018      3780621  419207    2       419207
8           8    8  12/11/2018      3780621  447663    1       447663
9           9    9  12/11/2018      3780618  364507    1       364507

   Location Alley_Number  Cellule          Coord AlleyCell        Size
0  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
1  A0721204          A07       21   [32.5, 22.5]     A0721  (350, 200)
2  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
3  A0706401          A07        6  [31.25, 10.5]     A0706  (210, 260)
4  A0216107          A02       16   [47.5, 18.0]     A0216  (350, 240)
5  A0308201          A03        8  [44.25, 12.0]     A0308  (260, 360)
6  A0403203          A04        3   [42.25, 9.0]     A0403  (150, 120)
7  A0503203          A05        3    [39.0, 9.0]     A0503  (170, 160)
8  A1020501          A10       20  [20.75, 21.0]     A1020  (100, 140)
9  A0306503          A03        6  [44.25, 10.5]     A0306   (50, 180)
     Unnamed: 0  S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
169         169  169  12/3/2018      3756186  452650    1       452650
170         170  170  12/3/2018      3755674  395246    1       395246
171         171  171  12/3/2018      3755671  395245    1       395245
172         172  172  12/3/2018      3755612  348940    1       348940
173         173  173  12/3/2018      3755610  335346    1       335346
174         174  174  12/3/2018      3755572  452659    1       452659
175         175  175  12/3/2018      3755561  434125    1       434125
176         176  176  12/3/2018      3755548  335346    1       335346
177         177  177  12/3/2018      3755539  348799    1       348799
178         178  178  12/3/2018      3755497  450078    1       450078

     Location Alley_Number  Cellule          Coord AlleyCell        Size
169  A0901304          A09        1      [26, 6.0]     A0901  (120, 140)
170  A0707504          A07        7   [32.5, 12.0]     A0707  (320, 380)
171  A0708403          A07        8  [31.25, 12.0]     A0708   (410, 60)
172  A0411203          A04       11  [42.25, 15.0]     A0411  (100, 180)
173  A1011303          A10       11  [22.75, 15.0]     A1011  (430, 300)
174  A0908204          A09        8     [24, 12.0]     A0908  (210, 300)
175  A0912502          A09       12     [24, 15.0]     A0912   (90, 200)
176  A1011303          A10       11  [22.75, 15.0]     A1011  (430, 300)
177  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
178  A0904104          A09        4      [24, 9.0]     A0904  (140, 180)
     Unnamed: 0  S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
310         310  310  12/4/2018      3759739  260229    1       260229
311         311  311  12/4/2018      3759739  295637    1       295637
312         312  312  12/4/2018      3759739  295640    1       295640
313         313  313  12/4/2018      3759739  445809    1       445809
314         314  314  12/4/2018      3759728  102179    1       102179
315         315  315  12/4/2018      3759728  399573    1       399573
316         316  316  12/4/2018      3759726  351020    1       351020
317         317  317  12/4/2018      3759717  370781    1       370781
318         318  318  12/4/2018      3759716  424784    1       424784
319         319  319  12/4/2018      3759716  440736    1       440736

     Location Alley_Number  Cellule          Coord AlleyCell        Size
310  A0920303          A09       20     [24, 21.0]     A0920   (90, 280)
311  A0810404          A08       10   [28.0, 13.5]     A0810  (130, 140)
312  A0810503          A08       10   [28.0, 13.5]     A0810  (150, 180)
313  A0709301          A07        9   [32.5, 13.5]     A0709  (190, 160)
314  A0305303          A03        5   [45.5, 10.5]     A0305  (140, 240)
315  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
316  A0902102          A09        2      [24, 6.0]     A0902   (310, 40)
317  A1008402          A10        8  [20.75, 12.0]     A1008  (300, 280)
318  A0516102          A05       16  [37.75, 18.0]     A0516  (100, 340)
319  A1013401          A10       13  [22.75, 16.5]     A1013  (320, 380)
     Unnamed: 0  S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
505         505  505  12/5/2018      3763386  440469    1       440469
506         506  506  12/5/2018      3763386  440470    1       440470
507         507  507  12/5/2018      3763386  440472    1       440472
508         508  508  12/5/2018      3763386  440473    1       440473
509         509  509  12/5/2018      3763386  444228    1       444228
510         510  510  12/5/2018      3763383  349867    1       349867
511         511  511  12/5/2018      3763385  348799    1       348799
512         512  512  12/5/2018      3763385  372093    1       372093
513         513  513  12/5/2018      3763381  219195    1       219195
514         514  514  12/5/2018      3763380  215340    1       215340

     Location Alley_Number  Cellule          Coord AlleyCell        Size
505  A1007401          A10        7  [22.75, 12.0]     A1007  (400, 220)
506  A1007403          A10        7  [22.75, 12.0]     A1007   (390, 60)
507  A1008102          A10        8  [20.75, 12.0]     A1008  (350, 140)
508  A1008203          A10        8  [20.75, 12.0]     A1008   (90, 340)
509  A0910201          A09       10     [24, 13.5]     A0910  (410, 140)
510  A0719104          A07       19   [32.5, 21.0]     A0719  (100, 300)
511  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
512  A1001201          A10        1   [22.75, 6.0]     A1001  (340, 300)
513  A0607103          A06        7  [35.75, 12.0]     A0607  (170, 220)
514  A0717501          A07       17   [32.5, 19.5]     A0717  (170, 160)
     Unnamed: 0  S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
706         706  706  12/6/2018      3767351  307774    1       307774
707         707  707  12/6/2018      3767349  457146    2       457146
708         708  708  12/6/2018      3767348  290863    1       290863
709         709  709  12/6/2018      3767348  450077    1       450077
710         710  710  12/6/2018      3767335  448097    1       448097
711         711  711  12/6/2018      3767333  370755    3       370755
712         712  712  12/6/2018      3767333  370756    3       370756
713         713  713  12/6/2018      3767334  435623    1       435623
714         714  714  12/6/2018      3767331  267281    1       267281
715         715  715  12/6/2018      3767405  452968    1       452968

     Location Alley_Number  Cellule          Coord AlleyCell        Size
706  A0220107          A02       20   [47.5, 21.0]     A0220  (360, 340)
707  A0307101          A03        7   [45.5, 12.0]     A0307  (110, 120)
708  A1011204          A10       11  [22.75, 15.0]     A1011  (360, 240)
709  A0920204          A09       20     [24, 21.0]     A0920   (50, 240)
710  A0220103          A02       20   [47.5, 21.0]     A0220  (180, 260)
711  A0809302          A08        9  [29.25, 13.5]     A0809  (190, 100)
712  A1021303          A10       21  [22.75, 22.5]     A1021   (90, 160)
713  A0715104          A07       15   [32.5, 18.0]     A0715  (330, 220)
714  A0901302          A09        1      [26, 6.0]     A0901   (380, 40)
715  A0619101          A06       19  [35.75, 21.0]     A0619  (290, 380)
     Unnamed: 0  S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
898         898  898  12/7/2018      3770586  337151    1       337151
899         899  899  12/7/2018      3770586  465577    1       465577
900         900  900  12/7/2018      3770584  399573    1       399573
901         901  901  12/7/2018      3770584  402695    1       402695
902         902  902  12/7/2018      3770576  370790    1       370790
903         903  903  12/7/2018      3770576  465708    1       465708
904         904  904  12/7/2018      3770572  240821    1       240821
905         905  905  12/7/2018      3770572  361208    1       361208
906         906  906  12/7/2018      3770572  399573    1       399573
907         907  907  12/7/2018      3770508  403963    1       403963

     Location Alley_Number  Cellule          Coord AlleyCell        Size
898  A0206406          A02        6   [47.5, 10.5]     A0206  (380, 180)
899  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
900  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
901  A0314408          A03       14  [44.25, 16.5]     A0314   (330, 20)
902  A0902301          A09        2      [24, 6.0]     A0902  (310, 240)
903  A1004502          A10        4   [20.75, 9.0]     A1004  (110, 240)
904  A0616201          A06       16   [34.5, 18.0]     A0616   (390, 60)
905  A0908301          A09        8     [24, 12.0]     A0908   (80, 200)
906  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
907  A0305302          A03        5   [45.5, 10.5]     A0305  (330, 140)
      Unnamed: 0   S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
1082        1082  1082  12/9/2018      3774964  445070    1       445070
1083        1083  1083  12/9/2018      3774965  292954    1       292954
1084        1084  1084  12/9/2018      3774944  445070    1       445070
1085        1085  1085  12/9/2018      3774941  263736    1       263736
1086        1086  1086  12/9/2018      3774942  366685    1       366685
1087        1087  1087  12/9/2018      3774898  259767    1       259767
1088        1088  1088  12/9/2018      3774899  452650    1       452650
1089        1089  1089  12/9/2018      3774875  450077    1       450077
1090        1090  1090  12/9/2018      3774873  263737    1       263737
1091        1091  1091  12/9/2018      3774874  353788    1       353788

      Location Alley_Number  Cellule          Coord AlleyCell        Size
1082  A0921501          A09       21     [26, 22.5]     A0921  (200, 260)
1083  A0416201          A04       16   [41.0, 18.0]     A0416   (370, 80)
1084  A0921501          A09       21     [26, 22.5]     A0921  (200, 260)
1085  A0406401          A04        6   [41.0, 10.5]     A0406   (110, 60)
1086  A0104504          A01        4   [50.75, 9.0]     A0104  (180, 360)
1087  A0911101          A09       11     [26, 15.0]     A0911   (330, 40)
1088  A0901304          A09        1      [26, 6.0]     A0901  (120, 140)
1089  A0920204          A09       20     [24, 21.0]     A0920   (50, 240)
1090  A0413203          A04       13  [42.25, 16.5]     A0413  (260, 320)
1091  A0906503          A09        6     [24, 10.5]     A0906  (300, 100)
      Unnamed: 0   S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
1267        1267  1267  12/10/2018      3777000  449733    1       449733
1268        1268  1268  12/10/2018      3776999  459896    1       459896
1269        1269  1269  12/10/2018      3776943  348815    1       348815
1270        1270  1270  12/10/2018      3776943  397345    1       397345
1271        1271  1271  12/10/2018      3776940  465577    1       465577
1272        1272  1272  12/10/2018      3776887  348799    1       348799
1273        1273  1273  12/10/2018      3776886  340387    1       340387
1274        1274  1274  12/10/2018      3776886  440469    1       440469
1275        1275  1275  12/10/2018      3776886  440470    1       440470
1276        1276  1276  12/10/2018      3776880  440530    1       440530

      Location Alley_Number  Cellule          Coord AlleyCell        Size
1267  A0918104          A09       18     [24, 19.5]     A0918  (200, 160)
1268  A1107404          A11        7   [19.5, 12.0]     A1107   (110, 80)
1269  A0904101          A09        4      [24, 9.0]     A0904  (200, 160)
1270  A0914202          A09       14     [24, 16.5]     A0914  (240, 180)
1271  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
1272  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
1273  A0920103          A09       20     [24, 21.0]     A0920  (300, 220)
1274  A1007401          A10        7  [22.75, 12.0]     A1007  (400, 220)
1275  A1007403          A10        7  [22.75, 12.0]     A1007   (390, 60)
1276  A1002101          A10        2   [20.75, 6.0]     A1002  (360, 360)
      Unnamed: 0   S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
1447        1447  1447  12/12/2018      3783234  449731    1       449731
1448        1448  1448  12/12/2018      3785231  466405    2       466405
1449        1449  1449  12/12/2018      3784779  399573    1       399573
1450        1450  1450  12/12/2018      3784779  464707    1       464707
1451        1451  1451  12/12/2018      3784695  353788    1       353788
1452        1452  1452  12/12/2018      3784688  370784    1       370784
1453        1453  1453  12/12/2018      3784576  353788    1       353788
1454        1454  1454  12/12/2018      3784476  348799    1       348799
1455        1455  1455  12/12/2018      3784404  446856    1       446856
1456        1456  1456  12/12/2018      3784392  263736    1       263736

      Location Alley_Number  Cellule          Coord AlleyCell        Size
1447  A0918103          A09       18     [24, 19.5]     A0918  (400, 120)
1448  A1007503          A10        7  [22.75, 12.0]     A1007  (300, 280)
1449  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
1450  A0321403          A03       21   [45.5, 22.5]     A0321  (290, 320)
1451  A0906503          A09        6     [24, 10.5]     A0906  (300, 100)
1452  A1014504          A10       14  [20.75, 16.5]     A1014   (60, 320)
1453  A0906503          A09        6     [24, 10.5]     A0906  (300, 100)
1454  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
1455  A0902401          A09        2      [24, 6.0]     A0902  (230, 340)
1456  A0406401          A04        6   [41.0, 10.5]     A0406   (110, 60)
      Unnamed: 0   S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
2271        2271  2271  12/13/2018      3802428  309462    8       309462
2272        2272  2272  12/13/2018      3802428  432234    1       432234
2273        2273  2273  12/13/2018      3802371  335346    1       335346
2274        2274  2274  12/13/2018      3802371  397537    1       397537
2275        2275  2275  12/13/2018      3802282  263738    1       263738
2276        2276  2276  12/13/2018      3802249  290863    2       290863
2277        2277  2277  12/13/2018      3802249  401696    1       401696
2278        2278  2278  12/13/2018      3802249  421048    1       421048
2279        2279  2279  12/13/2018      3802249  465577    1       465577
2280        2280  2280  12/13/2018      3802216  421829    1       421829

      Location Alley_Number  Cellule          Coord AlleyCell        Size
2271  A1107203          A11        7   [19.5, 12.0]     A1107   (240, 20)
2272  A0407103          A04        7  [42.25, 12.0]     A0407   (70, 160)
2273  A1011303          A10       11  [22.75, 15.0]     A1011  (430, 300)
2274  A0802504          A08        2    [28.0, 6.0]     A0802  (420, 220)
2275  A0412503          A04       12   [41.0, 15.0]     A0412  (360, 120)
2276  A1011204          A10       11  [22.75, 15.0]     A1011  (360, 240)
2277  A0422502          A04       22   [41.0, 22.5]     A0422  (160, 260)
2278  A0312307          A03       12  [44.25, 15.0]     A0312    (70, 60)
2279  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
2280  A0604101          A06        4    [34.5, 9.0]     A0604  (110, 220)
      Unnamed: 0   S/N       DATE  OrderNumber     SKU  PCS  ReferenceID  \
3438        3438  3438  12/8/2018      3773634  450401    1       450401
3439        3439  3439  12/8/2018      3773624  422249    1       422249
3440        3440  3440  12/8/2018      3773621  434125    1       434125
3441        3441  3441  12/8/2018      3773619  401696    1       401696
3442        3442  3442  12/8/2018      3773619  434122    1       434122
3443        3443  3443  12/8/2018      3773619  450401    1       450401
3444        3444  3444  12/8/2018      3773619  465577    1       465577
3445        3445  3445  12/8/2018      3773605  360915    1       360915
3446        3446  3446  12/8/2018      3773593  348799    1       348799
3447        3447  3447  12/8/2018      3773587  290863    1       290863

      Location Alley_Number  Cellule          Coord AlleyCell        Size
3438  A1115302          A11       15   [19.5, 18.0]     A1115   (420, 40)
3439  A1115201          A11       15   [19.5, 18.0]     A1115  (100, 140)
3440  A0912502          A09       12     [24, 15.0]     A0912   (90, 200)
3441  A0422502          A04       22   [41.0, 22.5]     A0422  (160, 260)
3442  A1106403          A11        6  [15.25, 10.5]     A1106   (290, 60)
3443  A1115302          A11       15   [19.5, 18.0]     A1115   (420, 40)
3444  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
3445  A0510102          A05       10  [37.75, 13.5]     A0510  (170, 380)
3446  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
3447  A1011204          A10       11  [22.75, 15.0]     A1011  (360, 240)
      Unnamed: 0   S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
3767        3767  3767  12/14/2018      3806400  295842    1       295842
3768        3768  3768  12/14/2018      3806376  348799    1       348799
3769        3769  3769  12/14/2018      3806238  399573    1       399573
3770        3770  3770  12/14/2018      3806238  457090    1       457090
3771        3771  3771  12/14/2018      3806239  290863    1       290863
3772        3772  3772  12/14/2018      3806235  339211    1       339211
3773        3773  3773  12/14/2018      3806233  465577    1       465577
3774        3774  3774  12/14/2018      3806224  290863    2       290863
3775        3775  3775  12/14/2018      3806224  399573    1       399573
3776        3776  3776  12/14/2018      3806224  465577    1       465577

      Location Alley_Number  Cellule          Coord AlleyCell        Size
3767  A0206505          A02        6   [47.5, 10.5]     A0206   (70, 240)
3768  A1009503          A10        9  [22.75, 13.5]     A1009   (200, 20)
3769  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
3770  A0520403          A05       20  [37.75, 21.0]     A0520   (90, 220)
3771  A1011204          A10       11  [22.75, 15.0]     A1011  (360, 240)
3772  A0614203          A06       14   [34.5, 16.5]     A0614   (80, 260)
3773  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
3774  A1011204          A10       11  [22.75, 15.0]     A1011  (360, 240)
3775  A1119504          A11       19   [19.5, 21.0]     A1119  (330, 120)
3776  A1004103          A10        4   [20.75, 9.0]     A1004  (100, 320)
      Unnamed: 0   S/N        DATE  OrderNumber     SKU  PCS  ReferenceID  \
4246        4246  4246  12/15/2018      3809814  399573    1       399573
4247        4247  4247  12/15/2018      3809814  465577    1       465577
4248        4248  4248  12/15/2018      3809788  399573    1       399573
4249        4249  4249  12/15/2018      3809788  465577    1       465577
4250        4250  4250  12/15/2018      3809762  253469    1       253469
4251        4251  4251  12/15/2018      3809745  280053    1       280053
4252        4252  4252  12/15/2018      3809745  329167    1       329167
4253        4253  4253  12/15/2018      3809745  354785    1       354785

# Group orderlines by spatial closeness of majority of goods

## Constraints
1. A single picker handles invoice(s) from start to finish, across 1 or more waves
2. A group can consists of fraction of invoice(s) so long as it can be fulfilled by the end of the day and the waves are handled by the same picker
3. Size of SKU_size * pieces for each orderlines in the invoice(s) should fit on w * l pallet/trolley

## Assumption
1. Pickers will have to stay throughout the entire shift, to completely fulfil their invoices for the day
2. Any weight can be handled by the pallet and the picker

## Compare to
1. Above method
2. Grouping by first come first serve
3. Baseline one by one order

## WHAT NOT TO DO
1. No condensing the closest point of centroid. It's fake haha

## Future considerations 
1. Priorities
2. Installments
3.

# Routing

1. NCL
2. Google OR TOols  #https://developers.google.com/optimization/introduction/python
3. Zig zag, complete an aisle before proceeding to next aisle

# Links

https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.fcluster.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html

## What to do in the future?

1. Make a better map
2. Look into weight/difficulty of moving from one point to another